### ISSUE TITLE
xref in cell/line fails validation

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1000]
An xref inside a "line" element (specifically, a line inside a table cell) fails validation, although we are unable to think of an intentional reason why it should. Maybe it is a byproduct of excluding xref from a line of a poem.

**Comment by Alex-Jordan** [comment]
Too bad #1000 is not a very substantial issue :)

**Comment by rbeezer** [comment]
A `line` of a `cell` was the same as a `line` of an `attribution`.  But not as for a `poem` (those lines have indentation).

Schema reworked to allow some `line` to have both internal (`xref`) and external (`url`) references, others not.

Work at 89f5373728a43c1150e76705f54c6daa1b3ff257.  Also defiled your Lorax table with a test case at 402f94c48a9eec3fbb354e93eb76d5ee1d6e4f09.  Sorry.

Thanks for the report.  Testing welcome (no new false alarms with changes?).
