### ISSUE TITLE
Sections links in index should be internal

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1005]
A "Section" link in the index is not receiving styling.

If it has class="internal", then it would.

**Comment by rbeezer** [comment]
Thanks for teh catch.  I've added the `internal` class to the index entries.  I thought I'd reviewed that, but maybe I'm confusing that with changing over the knowls in the index.  At 991b735ecb28bc45015124c004847a0934114b5f

See #1003 also
