### ISSUE TITLE
Conundrum not renamed in sample article

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1014]
In the Sample Article, proposition is renamed as conundrum, but in the HTML it still
says Proposition.

Proposition 26.1 and 9th bullet in Section 17

**Comment by rbeezer** [comment]
I tried to simplify the "rename" element, and thought it had passed tests, I'll 
investigate.

**Comment by rbeezer** [comment]
Quick catch!  I forgot to un-comment that example after doing my testing.  So code is fine, but sample article source needed repair.

Work at:  47fbe4d2bc9ad142e62d7a54f81e5623df9c275c

Thanks!
