### ISSUE TITLE
Clearly indicate LaTeX relies on MathJax commands/symbols

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1021]
In other words, macros, etc. should only use what is supported here:

http://docs.mathjax.org/en/latest/tex.html#supported-latex-commands

Add to the author's guide, it is alrerady in the sample article.

**Comment by Alex-Jordan** [comment]
We should clear up in MathJax third party extensions are OK too. 

I think we use/allow the `cancel` extension right now. And I found [this](https://github.com/mathjax/MathJax/issues/819) which reveals there is an extension that would enable a horizontal line through a brace, as was asked about recently in the forums. But do we want to support it?

**Comment by Alex-Jordan** [comment]
Now there is also a post suggesting someone might like to use this MathJax extension: http://sonoisa.github.io/xyjax/xyjax.html

**Comment by alexjbest** [comment]
> Now there is also a post suggesting someone might like to use this MathJax extension: http://sonoisa.github.io/xyjax/xyjax.html

For future reference of anyone searching xypic/xyjax in this issue list: This post was <https://groups.google.com/forum/?fromgroups=#!topic/pretext-support/wEKBQRmuOHE> where I have linked to <https://github.com/alexjbest/parity/blob/master/parity.xsl> demonstrating one way to do this currently.

**Comment by rbeezer** [comment]
> We should clear up in MathJax third party extensions are OK too.

This was a documentation issue.  Support discussion has moved to #1036.  Please continue the discussion there.

**Comment by rbeezer** [comment]
MathJax is linked in the Topics chapter of the Author's Guide.  Added it to the Overview chapter, so it won't be missed.  At 70e094670d9441d650142ac63e0234a09a0f2bf0
