### ISSUE TITLE
valign in sidebyside in HTML not respected

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1031]
If there is a sidebyside with two images and `valign="bottom"`, the HTML is not vertically aligning the images at their bottoms. (But PDF is.)

**Comment by davidfarmer** [comment]
Is there a live example in the sample article or elsewhere?

**Comment by Alex-Jordan** [comment]
There might be in the SA but I can't search right now.

Here is one in the nascent showcase:
http://spot.pcc.edu/~ajordan/temp/showcase/html/latex-image.html

The top two sidebysides have `valign="top"` in source. The third sidebyside has `valign="bottom"`.

**Comment by davidfarmer** [comment]
I can't see where the HTML markup is indicating any choice between
top and bottom for the alignment.  Am I missing something obvious?

Note:  I did make one CSS change that I think corrected an error,
but it may have made some cases worse.  Reload to get the change.

**Comment by davidfarmer** [comment]
Correction:  currently those valigns seem backward from what was stated (the first two at the
bottom, and the 3rd at the top).

**Comment by rbeezer** [comment]
Here is the relevant HTML for constructing the CSS that will control this.  Line 5048 of `mathbook-html.xsl`.  Reply if that is not enough of a hint, I've not investigated further.

```xsl
<!-- assumes "sbspanel" class set vertical direction -->
<xsl:text>justify-content:</xsl:text>
<xsl:choose>
    <xsl:when test="$valign = 'top'">
        <xsl:text>flex-start</xsl:text>
    </xsl:when>
    <xsl:when test="$valign = 'middle'">
        <xsl:text>center</xsl:text>
    </xsl:when>
    <xsl:when test="$valign = 'bottom'">
        <xsl:text>flex-end</xsl:text>
    </xsl:when>
</xsl:choose>
<xsl:text>;</xsl:text>
```

**Comment by Alex-Jordan** [comment]
>Correction: currently those valigns seem backward from what was stated (the first two at the
bottom, and the 3rd at the top).

Oops. Yes, I stated it backwards.

**Comment by Alex-Jordan** [comment]
Now when I look at that page, it is aligning correctly.

**Comment by davidfarmer** [comment]
I guess the CSS change I did, which I thought was not actually
related, did the right thing.

**Comment by rbeezer** [comment]
Sounds like we are done with this one.  If not, it can be re-opened.
