### ISSUE TITLE
Migrate to MathJax 3

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1039]
This is a meta-issue for notes, or related issues involved with an upgrade to MathJax 3, which at this writing is still in beta.

**Comment by rbeezer** [comment]
Using the https://cdn.rawgit.com/mathjax/mj3-demos/3.0.0-beta.3/mj3-tex2html-beta.dist.js variant in a very quick-and-dirty way, seems to resolve the bold math problem at #1040.

**Comment by rbeezer** [comment]
Knowls in display math seem to act better with same variant as above.

**Comment by rbeezer** [comment]
Seems to be some changes in font sizes, noticed in #930.

**Comment by rbeezer** [comment]
Just upgraded my testing branch to beta 4, the final one.  So using

https://cdn.rawgit.com/mathjax/mathjax3/tex-chtml.js

Nothing startling to report.

**Comment by Alex-Jordan** [comment]
Just a note to look into the color.js extension with the migration to MJ3.

**Comment by rbeezer** [comment]
I have no reason to believe that MJ will do a better job of keeping text after math for not line-breaking.  But worth testing.

#697

**Comment by rbeezer** [comment]
Looks like MJ3 is not really mature just yet.  We'll want to watch this:

http://docs.mathjax.org/en/v3.0-latest/upgrading/v2.html

**Comment by sean-fitzpatrick** [comment]
With MathJax 2.7.5, superscripts on the | (\vert) character don't render correctly when accessibility is turned on. This can be worked around by using braces: |^2 doesn't work right, but {|}^2 does.
Maybe using \vert instead of the keyboard character would fix things, too.
(Also, \right| seems OK, but \Big| is not.)

**Comment by sean-fitzpatrick** [comment]
Testing using the utility on the MathJax site suggests this is fixed in 3.0

**Comment by Alex-Jordan** [comment]
When moving to MathJax 3, or after the move, monitor these two issues we currently have and see if they go away:

1. Set MathJax to SVG rendering. Then load [this page](https://pretextbook.org/examples/sample-article/html/section-7.html#p-216). Open the example knowl and see if the second equation column is aligned well.

1. Set MathJax to SVG rendering. Go to [here](https://pretextbook.org/examples/sample-article/html/section-7.html#p-227) and see if the knowls that are inside the math function as they should. Current behavior is that you click them, they open, and then instantly close.

**Comment by rbeezer** [comment]
Inline math, followed by punctuation (period, comma) sometimes gets a bad line-break due to MathJax.

In `xsl/pretext-html.xsl` find the new `math.punctuation.include` variable and try changing it from `'all'` to `'display'` and see if this behavior persists.

**Comment by rbeezer** [comment]
Commit 38e98001b39c54d7bf7b7888f17fde8c76518f56 adds some MathJax configuration to the Reveal.js slideshow conversion.  It'll need a look once we upgrade.

**Comment by rbeezer** [comment]
#1354 might wait for MJ3.  Or not.

**Comment by davidfarmer** [comment]
The knowls Javascript calls MathJax, but the way you call MathJax3 is different than MathJax2.
So, at the same time as we upgrade to MathJax3, we also need to move to a new version of
the PTX Javascript (unless it is possible to keep the knowls code backward compatible).

**Comment by rbeezer** [comment]
MJ 3.1.2 has some change in behavior with the super-popular `\text{}` via an extension.  We should follow MJ, but also warn authors when we switch.  Details at:

https://groups.google.com/g/mathjax-users/c/0cibiiq3jxw/m/_aqYBQfWAQAJ

**Comment by davidfarmer** [comment]
Apparently MathJax 3 now looks in the text by default:

https://groups.google.com/g/mathjax-users/c/0cibiiq3jxw

So we probably don't want the textmacros extension.

**Comment by sean-fitzpatrick** [comment]
I notice that the complaint here is about the use of `\text{N^*}` which seems like something a reasonable person just shouldn't do, no? Is the point of textmacros to allow this over the slightly more annoying to type `\text{N}^*` (or perhaps `\mathrm{N}^*`)?

**Comment by davidfarmer** [comment]
I think my point was that PreTeXt expects only text where only
text should be.  So it is asking for trouble if MathJax supports
other behavior.

**Comment by rbeezer** [comment]
Peter K (@pkra) plans to move AMS production to MJ 3 in the start of 2021, so maybe the end of the academic year (May/June) would be a good time to make the move.

**Comment by pkra** [comment]
Following up on @rbeezer's question during the last drop-in meeting: here's the jupyter plugin for mathjax 3 https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/mathjax3-extension

**Comment by rbeezer** [comment]
Upgrade in place via several commits, starting from 9c91af4e107ea75c8f255624aba2d4742ab6b3fb

I'll follow-up on all the pointers here before closing.

**Comment by rbeezer** [comment]
*  Bold math on #1040 seems OK, but pinged OP.
*  Collapsible math (#930) is still an issue, but no worse.
*  Linking to equations fixed at 8fc65822817c1f9da0176ebda5ba82ae00cc64c5, more at #1472
*  No `color.js` exploration (@Alex-Jordan)
*   Line-breaking tested at 17d8d5ef4c44da8d1ebe540e8d5f8e0e0dc32552
*  The alignment problem is no problem - the lines are not specified to be aligned.  (Might change that.)
*  Reveal and MathJax is more complicated, so an independent item.
*  Knowls Javascript is all fixed up at 4da728da43ba5bde78c3c8c31fec67f1cb4a23b5
*  The `textmacros` package turned out to be a non-issue, since we are not using a `-full` MathJax configuration, so it is not being loaded.
* See #1474 for Jupyter.
