### ISSUE TITLE
For some reason sample video doesn't work locally

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#104]
I tried in old Safari (nothing), current FF (warning), and current Chrome (video box but nothing to play when push button).  This is when the sample article is compiled locally.  The correct file seems to be there, and other images are in the html correctly, but I can't get it to play.

**Comment by ladanielson** [comment]
I'm am looking for a way to play an mp4 video which is stored locally and embedded directly in the html.

**Comment by rbeezer** [comment]
@kcrisman Try now.  #585 should be more reliable.  If not, report browsers tested on pull request.  Less than two years to fix this one!

@ladanielson Let us know how it goes.  You owe @Jahrme one. ;-)  Comment on #585.
