### ISSUE TITLE
Implement EPUB preliminary files

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1050]
The current EPUB conversion lists three preliminary files (such as a Table of Contents) in the `manifest` and in the `spine`, but no such files are being generated (an expedient omission).  This was the source of cryptic opening errors in Gitden Reader (Android).

* Maybe check if these are necessary files (i.e. required by the standard).
* Any way, implement these.
* Test in Gitden Reader.
* It'd be a good time to attempt a conversion to Kindle format.

**Comment by mitchkeller** [comment]
We need exactly one manifest item to have the nav property, which should be the table of contents. The conversion that solved Gitden Reader problems is not valid EPUB, and iBooks rejects it as corrupt because it doesn't have something with the nav property.

**Comment by rbeezer** [comment]
Alright, these files **were** being generated (my mistake), but I think it was an empty `head` element that caused Gitden Reader to complain.  In any event, fixed now.  See discussion on `pretext-dev` (coming up).
