### ISSUE TITLE
add example of structured title somewhere visible

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1059]
Now that #309 is in, add this someplace people will see it.  (See also #640.)

**Comment by rbeezer** [comment]
See Chapter 14 at

https://pretextbook.org/examples/sample-article/derivatives.pdf

**Comment by kcrisman** [comment]
Thanks!  I was looking for an addition in the commits you referenced in #309 but I guess this must have made it in before that?  I suppose that is one of the advantages of the Trac system where (in principle) each branch "belongs" to a ticket, is it makes it easier to find references.
