### ISSUE TITLE
In-context links for displayed mathematics do not find their targets on other pages

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1060]
* Section 17 (Cross-Referencing) has a cross-reference to the "range" of equations (7.1)–(7.2).
* Clicking on the cross-reference opens an xref-knowl with the entire display.  Good.
* Click on the "in-context" link (which is correct).
* Goes to the correct page, but not to the location.
* Go to address bar and reload the same URL, seems to work.

(Nothing about the range is critical here, it is just a convenient example.)

Hypothesis: MathJax has not fully loaded the page, so the HTML `id` on the equation has not been loaded.

Solutions:
* Ping `mathjax-users`
* Have the "in-context" link reference the entire display.  We do not allow authors to place an `@xml:id` on the display, but do knowl the entire display for a cross-reference to one row.  We could use the automatic HTML `id` for this purpose.

**Comment by rbeezer** [comment]
MathJax 3 (#1039) does not seem to help.

**Comment by davidfarmer** [comment]
I thought one of the purposes of the containing div.displaymath
was to serve as a target?

Since the id in the MathJax does not exist when the page is
loaded, I don't think this is a MathJax problem.  Possibly some
javascript similar to how the TOC scrolls after MathJax finished,
could take care of this.  But I think the div.displaymath is a
better option.

**Comment by rbeezer** [comment]
> I thought one of the purposes of the containing div.displaymath was to serve as a target?

Perhaps.  I can't recall.  ;-)

Yes, I'm thinking `div.displaymath` is a good option, but might ping MJ anyway, to satisfy my curiousity if nothing else.

**Comment by rbeezer** [comment]
Some good leads from a post on `mathjax-users`:

https://groups.google.com/d/topic/mathjax-users/9iS8Rb2TGBs/discussion

**Comment by rbeezer** [comment]
Reporting in.

1.  Tried the suggested MJ addition, no luck.  See their issue.
1.  We do use `div.displaymath` for a target.  In one (rare) situation.  When a PTX `p` contains display math, the `p` will get exploded into smaller HTML `p`.  If the PTX `p` **begins** with display math (yes, bad practice), then the HTML `id` of the PTX `p` is placed onto the `div.displaymath` element.
1.  Putting an `id` derived from a PTX `men` or `mdn` onto the `div.displaymath` should solve the problem at hand.  As a bonus, the "pink flash" should work (not sure if the MJ approach would do that).
1.  But now display math will get one of two types of HTML `id`, depending on if  the display math is exceptional (item 2 above).  Then to form a cross-reference to display math, you will need to decide which of the two scenarios has been applied.  That will be another brittle layer on top of the need to handle other display items (e.g. lists) which are placed first in a PTX `p`.  So the code to handle the paragraph explosion keeps getting more twisted.

The root problem here is that we allow a cross-reference into a portion of a PTX `p` -- any display math (since they can be numbered, as equations).  We can cross-reference list items (not very well) but they are interior to the list (e.g `ol`) so there is no potential for a clash over an `id`.

If the PTX `p` were to produce a `div` of its own, enclosing all the pieces exploded into HTML `p`, `ol`, etc, then the assignment of values for `id` would be straightforward and consistent.  Then cross-references to those pieces would be straightforward as well.

**Comment by rbeezer** [comment]
Not sure how long this has been broken (or why), but I had a dash in the MathJax label, and it should have been a colon.  Fixed at  8fc65822817c1f9da0176ebda5ba82ae00cc64c5

`div.displaymath` suggestion at #1473

**Comment by pkra** [comment]
> Not sure how long this has been broken (or why), but I had a dash in the MathJax label, and it should have been a colon. Fixed at [8fc6582](https://github.com/rbeezer/mathbook/commit/8fc65822817c1f9da0176ebda5ba82ae00cc64c5)

That was a very recent change (3.1.3) to hack around a Safari bug, https://github.com/mathjax/MathJax-src/pull/671. I'm glad to see I wasn't the only one caught by this change :face_with_head_bandage:

**Comment by rbeezer** [comment]
> That was a very recent change

Great!  Thanks for letting us know.  It doesn't explain why this issue is two years old, but testing just now indicates things are working, so I'm going to leave it be.

**Comment by rbeezer** [comment]
Done at 6aa3d689a9980b45c028df7201549e546540fb3d, plus a couple following.

Went with the `div.displaymath` solution, which does create the expected bug from this div serving two purposes.  `p` lost out, since I'm down on authors cross-referencing a `p` anyway.
