### ISSUE TITLE
latex doesn't process fermat footnote properly

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#108]
I'm not sure why, but while html processes

    <xref ref="footnote-fermat" />

fine, I get errors for this in LaTeX, including the usual `??` in the output.

**Comment by kcrisman** [comment]
I should point out it does process it correctly on the page it occurs on, just not later in the text.

**Comment by rbeezer** [comment]
Thanks, I'd noticed this but could not understand why/how it got broken.  Maybe it never worked?  Fixed in upcoming push at d373d549.
