### ISSUE TITLE
Make EPUB build.sh cross-platform

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#1080]
GNU and BSD sed handle -i differently. Mac users have BSD sed. Not sure what Windows users have, but it's probably GNU, especially if using the Linux install that they can now use.

It appears we can either create backup files (since they do have a consistent syntax for backup file suffix if you're not trying to edit in place) and delete them or use something like is suggested in https://unix.stackexchange.com/questions/92895/how-can-i-achieve-portability-with-sed-i-in-place-editing

I'm pretty sure I can do the required edits, but I'd like to know what's preferred.

**Comment by kcrisman** [comment]
Yes, definitely fix this if possible, great idea; I have noticed precisely this issue when trying to use `sed` tips found online on my Mac.  

----------

(On a separate note, I haven't tried to use an ePub output yet, but is it stable enough to try to open one with Adobe Digital Editions?  I have to use that sometimes anyway for some of our library's e-texts, so it would be easy enough to try either an existing one or to compile for myself.)

**Comment by mitchkeller** [comment]
I have this on a branch (just for the EPUB build.sh at the moment, but could be copied elsewhere if needed) and will hopefully have a PR for @rbeezer yet today that deals with this and something else.

EPUB is still formally unsupported. We hope to have it supported this summer. Likely will be links to sample .epub files for people to test coming to the lists in the near future.

**Comment by rbeezer** [comment]
Addressed on #1089
