### ISSUE TITLE
EPUB conversion things to fix

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#1085]
1.  `example/solution` ~~needs to be not knowled.~~ d4cca1beb15d7cbfba8bc6b0fc219e21cf3be664
1. Validation issues a warning several times because "CSS selector specifies absolute position." These mostly appear to be related to CSS selectors that are not used in the output.
1. How is an aside styled? Lots of the CSS now has the issue noted above with absolute positions.
1. Ensure that all files in the EPUB are declared in the manifest. ~~This appears to be a problem mainly because SVG files are copied over and included in the EPUB but never used, so we want to only copy SVG files that are actually used.~~ However, AC biographies are included in the EPUB but not on the manifest. They are not visible in the EPUB.  I have the `biography` issue (both manifesting it and making readable) resolved on a branch. 0ec931765e7ff87a7ec568cc2c3c70df257fc367
1. ~~Ensure that SVG files used multiple times are only declared once in the manifest.~~ 7781128c13729a674e62764534393678676b66e6
1. ~~Various instances of periods being supplied by both CSS and the conversion. (After exercise numbers and example numbers for sure.)~~ Fixed on a branch.  fa577d22db8391fab9f016215a024e13a04c3b8a
1. Greg's L on the right side of proofs displays inconsistently on the macOS Books app. Sometimes it's great and other times parts of the vertical are missing but the horizontal part shows.

**Comment by mitchkeller** [comment]
Footnotes in my book are garbage in Calibre on macOS. They're beautiful in the macOS Books app, but Calibre and Adobe Desktop Editions are horrible.

**Comment by rbeezer** [comment]
Related, but not on this list: #1089

**Comment by mitchkeller** [comment]
Add CSS for SageMath cells to set them off more, or at least to clearly delineate between `<input>` and `<output>`.

**Comment by rbeezer** [comment]
Hints, answers, and solutions of exercises (and similar) will be un-knowled on next push.  They need some formatting help, since stock HTML assumes they are always presented as knowls.

**Comment by mitchkeller** [comment]
See additional discussion about the TOC on #1148.

**Comment by mitchkeller** [comment]
I'm closing this because things have largely improved as the ebook readers have improved over the last two years.
