### ISSUE TITLE
Link to ImageMagick in H.5 of the Author's Guide is broken

### ISSUE THREAD

**Issue by sean-fitzpatrick** [rbeezer/mathbook#1094]

**Comment by sean-fitzpatrick** [comment]
Correct link:
[https://imagemagick.org/script/download.php](https://imagemagick.org/script/download.php)

**Comment by sean-fitzpatrick** [comment]
Also, there is now a Windows installer for Sage:
[http://www.sagemath.org/download-windows.html](http://www.sagemath.org/download-windows.html)

**Comment by rbeezer** [comment]
Implemented on #1095
