### ISSUE TITLE
exercisegroup referred to in index

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1098]
If you put it in the usual place after title, the (html) index just refers to "exercises", but doesn't give a list of them.  Perhaps that would be a nice upgrade (since the groups themselves are not numbered).  (Probably a knowl would be too difficult to request?)

**Comment by rbeezer** [comment]
This got duplicated accidentally at #1424, which has a slightly better diagnosis.

The "Exercises" mentioned here is the whole division, which is one container too high up in the tree.  Once done right, the locator should automatically end up showing the range of numbers, e.g., "Exercise Group 5.2.87-5.2.93"

**Comment by kcrisman** [comment]
Got it.
