### ISSUE TITLE
TeXShop HTML

### ISSUE THREAD

**Issue by twjudson** [rbeezer/mathbook#1102]
The current TeXShop engine has the following code:

#!/bin/bash
OUTFILE="`basename $1`"
OUTFILE="${OUTFILE%.*}.html"
xsltproc --xinclude $HOME/Library/TeXShop/bin/xsl/mathbook-html.xsl "$1" 1>&2
open "$OUTFILE"  &

This will compile the HTML for PreTeXt in TeXShop and open the HTML in Safari **provided** the XML ID in the document matches the file name.  E.g., <article xml:id="minimal"> requires the file name to be minimal.xml. However, sample-article.xml contains the line <article xml:id="derivatives">.  The file derivatives.html will be created but will not open automatically.  I am not sure what the fix is.

**Comment by kcrisman** [comment]
> requires the file name to be minimal.xml. However, sample-article.xml contains the line . The file derivatives.html will be created but will not open automatically. I am not sure what the fix is.


Is some text missing here?

**Comment by Alex-Jordan** [comment]
@twjudson  may be able to edit his own post, and protect some tag with backticks. That is what I suspect happened here.

**Comment by rbeezer** [comment]
The missing stuff is not crtical, methinks.  I'm pretty sure I know what it says.

**Comment by rbeezer** [comment]
I think we should be **always** building an `index.html`, even if it is a verbatim copy of another file with a "nice" name.

Generally, out-of-the-box behaviour should produce an `index.html`.  Though not always as @twjudson observes.

So where I am going is:  maybe the last line of the engine should read

```bash
open index.html &
```

and then the necessary changes will ensure that always does the right thing.

**Comment by kcrisman** [comment]
> I think we should be **always** building an `index.html`, even if it is a verbatim copy of another file with a "nice" name.
> 
> Generally, out-of-the-box behaviour should produce an `index.html`. Though not always as @twjudson observes.

OT: I thought that we explicitly moved away from this model quite a while ago?  Currently I find I have to create my own.  Or at least it isn't created by `xsltproc ... mathbook-html.xsl ...`

**Comment by mitchkeller** [comment]
I would support always creating index.html as a copy of the main HTML file. (I'd prefer a symlink, but that might be problematic on Windows.)

I would suggest that the TeXShop build script look to see if Firefox is installed and do `open -a Firefox index.html &` if Firefox is available and otherwise default to just `open index.html &`. That will allow those experimenting with PreTeXt via TeXShop to continue using their default browsers but also ensure that their PreTeXt HTML is opened in a browser that will show non-empty knowls when viewing HTML stored locally.

**Comment by twjudson** [comment]
If we decide to always build index.html for any PreTeXt document (and I see good arguments for this), I think that we can easily adjust TeXShop.  The default browser for TeXShop is Safari, but I don’t think that it would be difficult to change it to Firefox or Chrome.

Tom

On Jun 24, 2019, at 5:08 PM, Mitchel T. Keller <notifications@github.com<mailto:notifications@github.com>> wrote:


I would support always creating index.html as a copy of the main HTML file. (I'd prefer a symlink, but that might be problematic on Windows.)

I would suggest that the TeXShop build script look to see if Firefox is installed and do open -a Firefox index.html & if Firefox is available and otherwise default to just open index.html &. That will allow those experimenting with PreTeXt via TeXShop to continue using their default browsers but also ensure that their PreTeXt HTML is opened in a browser that will show non-empty knowls when viewing HTML stored locally.

**Comment by rbeezer** [comment]
I think everything here is squared away.  I can't find teh relevant commit though, at the moment.
