### ISSUE TITLE
Document html.css.extra

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1114]
It turns out one can specify additional places to serve css from - see https://github.com/rbeezer/mathbook/issues/65#issuecomment-79906386 - but I don't think this has been documented someplace outside an xsl file, at least not visibly by doing
```
 grep -r 'html.css.extra' .
```
in the `mathbook` directory.

**Comment by davidfarmer** [comment]
I think it is a good thing to add hurdles in the way of people
who want to add their own custom styling.

For the rare person who actually knows what they are doing,
they can figure it out.

For the vast majority, we are protecting them from themselves.

Feel free to quote me.

ps.  For the question that led to this issue, since no actual example
was posted, there was no way for me to look into an easy CSS fix.

**Comment by kcrisman** [comment]
> Feel free to quote me.

My interpretation of @rbeezer 's comment linked above

> Undocumented and I have only tested that the URLs migrate to the HTML files as expected.

was that it should eventually be documented, but if that is misinterpreted and he concurs, I think that it seems reasonable to close this issue in that case.  

I will say that elsewhere we seem to be encouraging people to provide styling (for instance, by saying it is a "publisher option" and that the AIM css is just an example of one that may or may not be used by a given publisher), but again I may be interpreting that incorrectly.  I certainly don't have the resources to make much of my own for a project this big, except perhaps eventually changing a color or two 😄 though even there the many options available probably will more than suffice.

> p.s. For the question that led to this issue, since no actual example was posted, there was no way for me to look into an easy CSS fix.

I didn't know that CSS was the problem there, so no worries.   I think that, for the moment, I literally can't upload this particular one to a visible server anyway due to firewalls.

**Comment by davidfarmer** [comment]
The long-term plan is to have multiple styling options,
but we seem pretty far from having someone step up to do that.
(And as I have said many times, good designs are local maxima.
Tweaking a good design usually makes it worse, and the path
from one good design to another goes through bad designs.)

We also are in the midst of allowing some publisher options,
particularly as needed for lower-level textbooks.

For colors (in terms of customizing a color scheme) I am happy
to make more and/or accept pull requests.

For colors (in terms of subelements such as assemblages), I accept
that those could use attention and I am expecting to adjust the
existing schemes as those are brought to my attention.

**Comment by kcrisman** [comment]
> Tweaking a good design usually makes it worse, and the path
from one good design to another goes through bad designs.

True.

**Comment by rbeezer** [comment]
We will leave this undocumented for now.  But it is very useful for testing, so it will remain.

**Comment by kcrisman** [comment]
> We will leave this undocumented for now. But it is very useful for
> testing, so it will remain.
>
>
Okay, thanks.

>
