### ISSUE TITLE
If brandlogo picture not found, no error raised

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#112]
I would think there should be an error if the image file in

      <brandlogo url="http://mydomain.com/index.html" source="images/missinglogo.png" />

is not found.  Is that a bug?  I assume so or I wouldn't have made it an issue here.

**Comment by rbeezer** [comment]
`xsltproc` has no good way to see if you have various files laying around in various directories.  And your web browser should show you a "broken image" icon, no?  That'd be your error message and the right time (earliest time?) for it to be discovered.

Short answer: you (the author) are on your own to figure this out.

**Comment by kcrisman** [comment]
>
> Short answer: you (the author) are on your own to figure this out.
>
>

Yes, that's how I noticed it.  Okay.
