### ISSUE TITLE
check for statement inside stage in extracted WW

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1120]
In #1069 we started looking for a statement tag in extracted WW. Because my knowledge of tools for analyzing XML in Python is weak, I just found a way to check if there was a `statement` child of the root `webwork` and called it a day. But this neglected to account for when there is a `stage`, with the `statement` inside the stage, making the `statement` a grandchild of the root, not a child.

So we need a better way.

**Comment by rbeezer** [comment]
I like "lxml" but it does not seem to be part of standard Python.  Sounds like ElementTree is not as powerful/complete.

While poking around, I found this, which sounded helpful for this particular problem, but I won't claim to have studied it very carefully for this particular case:

https://stackoverflow.com/questions/5373902/python-xml-query-get-parent

**Comment by mitchkeller** [comment]
The python documentation makes me think that 

`if problem_root.find('statement') is None:`

can become

`if problem_root.find('.//statement') is None:`

since `//` from XPATH is supported and the example in the documentation says about `//`:

> Selects all subelements, on all levels beneath the current element. For example, .//egg selects all egg elements in the entire tree.

**Comment by rbeezer** [comment]
That sounds right.

**Comment by rbeezer** [comment]
Fied at #1164
