### ISSUE TITLE
latex stylesheet swallows idx in exercise

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1121]
The schema supports `<idx>` elements in `<exercise>` elements (here, in an `<exercises>` division), but somehow the LaTeX conversion just eats them up.
```
    <exercise xml:id="exercise-cryptography-el-gamal">
      <idx><h>encryption</h><h>El-Gamal</h></idx>
      <statement><p>Learn about the El-Gamal public key encryption method.  How is it implemented?  What mathematics used there is similar to what is used in this chapter?  What is different?</p></statement>
    </exercise>
```

works fine in html, but the reference is gone in pdf.  The `.tex` file has
```
\begin{divisionexercise}{12}{}{}{x:exercise:exercise-cryptography-el-gamal}%
Learn about the El-Gamal public key encryption method.  How is it implemented?  What mathematics used there is similar to what is used in this chapter?  What is different?%
\end{division exercise}%
```

However, if one places the `<idx>` _inside_ the `<statement>`, then all is well:
```
    <exercise xml:id="exercise-quadratic-reciprocity-hard-legendre-jacobi">
      <statement><p>Make up and compute some Legendre symbols that seem pretty hard by using the Jacobi<idx><h>Jacobi symbol</h></idx> symbol instead.</p></statement>
    </exercise>
Make up and compute some Legendre symbols that seem pretty hard by using the Jacobi\index{Jacobi symbol} symbol instead.%
```

So I wonder whether there should be something added [here](https://github.com/rbeezer/mathbook/blob/dev/xsl/mathbook-latex.xsl#L5166):
```
        <xsl:otherwise>
            <xsl:apply-templates select="." mode="exercise-components">
                <xsl:with-param name="b-original" select="true()" />
                <xsl:with-param name="b-has-statement" select="$b-has-statement" />
                <xsl:with-param name="b-has-hint"      select="$b-has-hint" />
                <xsl:with-param name="b-has-answer"    select="$b-has-answer" />
                <xsl:with-param name="b-has-solution"  select="$b-has-solution" />
            </xsl:apply-templates>
        </xsl:otherwise>
```
or somewhere nearby.  

----------

I admit I don't really understand the recursive nature of these stylesheets, so I hesitate to waste a lot of time adding
```
<xsl:apply-templates select="idx"/>
```
at random spots to try it out.  But if this is the right sort of thing to do, I'm willing to test a fix if I can be given guidance on placement.

**Comment by rbeezer** [comment]
That is an **application** of the modal template  `mode="exercise-components"'

Find its **definition** (only one, `<xsl:template...mode="exercise-components"`) and try adding the `apply-templates` you have above.

Make versions of the sample article LaTeX output on `dev` and on your branch, and do `git diff` between them to check for unintended consequences.

**Comment by Alex-Jordan** [comment]
@kcrisman Cheering you on here ;)  Find the "only one" Rob mentions quickly with regex search: `match.*mode="exercise-components"`

**Comment by kcrisman** [comment]
Oh, I'm not worried about finding that - I already saw it, I think, and in any case there are only twenty occurrences of that phrase which my browser easily scanned through online  😄 but it will have to wait; another very weird indexing issue came up I want to formulate correctly for another issue.

**Comment by kcrisman** [comment]
I think it will be more subtle than this, for two reasons.
* That line also matches not just webwork and things less likely to have index entries, but `&EXAMPLE-LIKE;`, which is quite likely to.  So you get doubles in the `.tex` file.  Haven't checked if this impacts pdf output yet.
* In addition, I think that the index entries inside `<statement>` tags in exercises may also be doubling.

As far as I can tell, those are the only side effects (I used `$ git diff -U0 --color-words --no-index ntic.tex ntic-old.tex | grep -v -e "@@" -e "g:"` to check this).

I thought about applying this to the template here instead:
```
<xsl:template match="exercises//exercise|worksheet//exercise|reading-questions//exercise">
```
But I think I will still get the second problem.

Again, my issue is really that I don't fully understand how the template system works - it's not quite recursive, because templates seem to get applied a number of times.

Anyway, the good news is that adding this line _somewhere_, possibly in a new template mode properly implemented, ought to do the trick.  I await further instructions 😄

**Comment by rbeezer** [comment]
Are you getting duplicates because you have solutions?  That template gets used for both.  The `b-original` is a boolean that signals if the version of the exercise is the original or a duplicate.  (I got triplicates with a test with the sample article.)

Try adding the new code below, where I have included some context to show where:
```xsl
<xsl:template match="exercise|webwork-reps/static|webwork-reps/static/stage|myopenmath|&EXAMPLE-LIKE;|&PROJECT-LIKE;|task" mode="exercise-components">
    <xsl:param name="b-original" />
    <xsl:param name="purpose" />
    <xsl:param name="b-has-statement" />
    <xsl:param name="b-has-hint" />
    <xsl:param name="b-has-answer"  />
    <xsl:param name="b-has-solution"  />

    <!-- structured (with components) versus unstructured (simply a bare statement) -->
    <xsl:if test="$b-original">
        <xsl:apply-templates select="idx"/>
    </xsl:if>
    <xsl:choose>
```

**Comment by kcrisman** [comment]
No solutions, so I don't think that is the problem (though it may be related).

-----

This also gets the missing index entries, but still has duplicates for examples, e.g.

```
\begin{example}{}{x:example:example-first-eucl-alg}%
\index{Euclidean algorithm!example}%
\index{Euclidean algorithm!example}%
```

Does `b-original` also apply to most `&EXAMPLE-LIKE;` items?

On a separate note, can you explain to me why this apparently does _not_ lead to duplication in exercises that have `<idx>` elements in their statements?  I'm still befuddled; the syntax seems to mean "apply all templates to the idx element" which I thought was recursive to all sub-elements ... but maybe not.  Which shows I shouldn't be contributing to stylesheets until I read a good primer on this 😉

**Comment by kcrisman** [comment]
> I thought about applying this to the template here instead:
> 
> ```
> <xsl:template match="exercises//exercise|worksheet//exercise|reading-questions//exercise">
> ```
> 

I should have done so.  Immediately after this line, if one tries
```
diff --git a/xsl/mathbook-latex.xsl b/xsl/mathbook-latex.xsl
index 7208e5b..6818106 100644
--- a/xsl/mathbook-latex.xsl
+++ b/xsl/mathbook-latex.xsl
@@ -5068,6 +5068,7 @@ along with MathBook XML.  If not, see <http://www.gnu.org/licenses/>.
     <!-- depending on what type of division the "exercise" lives in. -->
     <!-- For each, exactly one "ancestor" is true, and then the      -->
     <!-- expression will evaluate to the corresponding global switch -->
+    <xsl:apply-templates select="idx"/>
     <xsl:variable name="b-has-statement" select="true()"/>
     <xsl:variable name="b-has-hint"
         select="(ancestor::exercises and $b-has-divisional-hint) or
```
it seems to work, without creating any double entries from examples (obviously).  Exactly the same number of entries, and as far as I can tell, exactly the same (previously missing) entries.

> But I think I will still get the second problem.

Or any from that source either.  I really don't understand why, but I'm glad I don't see any extras.

**Comment by kcrisman** [comment]
(And if @rbeezer thinks this sounds good, I'll make a PR for it.)

**Comment by kcrisman** [comment]
Note that this change does NOT get `<idx>` as a direct subelement of `<exercisegroup>`.

**Comment by Alex-Jordan** [comment]
Looks like this is the same as what I tried to address in #1203.

**Comment by kcrisman** [comment]
Yes indeedy.  And now I recall something about my comment there I need to say.
