### ISSUE TITLE
fix-deprecations.xsl utility is mis-identifying a table with a title as a schema violation

### ISSUE THREAD

**Issue by sean-fitzpatrick** [rbeezer/mathbook#1143]
Recent change to the schema has tables using titles rather than captions.
The fix-deprecations utility correctly changes captions to titles in tables.
However, if a title is already in place, it identifies this as a schema violation and changes the table to a sidebyside.

**Comment by rbeezer** [comment]
Thanks.  I caught this in the warnings in the main stylesheets, but missed it here.

**Comment by rbeezer** [comment]
Fixed at 3b9828f91f5e149256a0754d54ea1e23898dc045
