### ISSUE TITLE
In Context not working in local server

### ISSUE THREAD

**Issue by h5bedi** [rbeezer/mathbook#1150]
sample-book/section-division-algorithm.html

Theorem 2.2.2 on the above mentioned page of sample book works on the hosted site as in context.

But, when I downloaded it on the local machine, and produced the html output it no longer works. The blue box shows up, but it is empty. 

I was able to find the file at
./knowl/theorem-integers-gcd.html
locally, but it does not render. 

But, everything else seems to be working fine.

**Comment by mitchkeller** [comment]
https://pretextbook.org/doc/guide/html/faq.html



-- 
Mitch Keller

**Comment by rbeezer** [comment]
@mitchkeller, you are just too quick.  First question at FAQ.  

@h5bedi - thanks for the report.  The "pretext-support" group is another great place to post with problems like this.
