### ISSUE TITLE
Make chapter reset within parts configurable

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#116]
On the HTML side this will wait until numbering is improved.   Trivial to customize on the LaTeX side.

**Comment by kcrisman** [comment]
Thanks - I'll definitely wait on this to use `<part>`, then.

**Comment by rbeezer** [comment]
See #550 also

**Comment by Alex-Jordan** [comment]
Unless I misunderstand, this has been done, right? You can have parts be decorative, and chapter numbers do not reset.

**Comment by rbeezer** [comment]
Thanks.  This is implemented.
