### ISSUE TITLE
Organizing slides by section

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1184]
Somewhere in the porting of https://github.com/StevenClontz/pretext-slides/ to this repo, the organizing of each section of slides vertically in revealjs seems to have been lost. That is,

```
section
  slide
  slide
```
should appear as
```
section
  section
  section
```
in the transpiled HTML to organize each section of slides vertically. (I will make a PR to fix this.)

**Comment by rbeezer** [comment]
Almost certainly my fault.  Just gave a presentation, with no problems, but I don't think it had any "section".

Holler if you need advice or counsel on the XSL.

Rob

**Comment by StevenClontz** [comment]
I believe the fix I snuck into #1185 is sufficient (it was a minor reordering of `apply-templates`).

**Comment by rbeezer** [comment]
Fied now as part of #1185 at d483470b05437fcd0ce27ea47a7c9913fecb7006
