### ISSUE TITLE
Display navigation in Reveal.js output

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1187]
As noted in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pretext-dev/f72Z_pwvkNg/1-MQYeQtAQAJ our current Reveal.js output doesn't display navigation arrows, so it is not clear when slides are available below the current slides (so pressing right would skip content, perhaps unintentionally). The theme used in https://revealjs.com/#/ has navigation arrows; we should investigate including them in our default output.

**Comment by rbeezer** [comment]
This has been added, and I think may be optionally adjusted or squelched.  In any event, it gave rise to #1260, so let's follow any progress there.
