### ISSUE TITLE
minipages: parskip and parindent are set to 0

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#119]
In LaTeX, a minipage has /parskip and /parindent set to 0. This was apparently an arbitrary call by Leslie Lamport. 

This is affecting the content of `<p>` children of a `<paragraphs>` inside a `<sidebyside>`. And probably other children of a `<sidebyside>`, if they have any `<p>` in them.

I think maybe something like here:
http://tex.stackexchange.com/questions/43002/how-to-preserve-the-same-parskip-in-minipage
would be good to preserve the ambient values of /parskip and /parindent inside minipages. 

Are there other places minipages are used? I was using them with my attempts to have columns for exercisegroups.

**Comment by rbeezer** [comment]
I think some XML tags got eaten in this:  "children of a inside a ."  ;-)

Can you rebroadcast, maybe with tags in quotes, or post via the web with tick marks?

**Comment by Alex-Jordan** [comment]
I noticed that, with this and a few others. I already edited the post on
GitHub. Can you see it there? I don't think that me editing would cause a
re-broadcast to you, but you should be able to see the post directly now.

On Wed, Jun 24, 2015 at 3:51 PM, Rob Beezer <notifications@github.com>
wrote:

> I think some XML tags got eaten in this: "children of a inside a ." ;-)
>
> Can you rebroadcast, maybe with tags in quotes, or post via the web with
> tick marks?
>
> On 06/24/2015 03:20 PM, Alex Jordan wrote:
> > In LaTeX, a minipage has /parskip and /parindent set to 0. This was
> apparently
> > an arbitrary call by Leslie Lamport.
> >
> > This is affecting the content of
> >
> > children of a inside a . And probably other children of a , if they have
> any
> >
> > in them.
> >
> > I think maybe something like here:
> >
> http://tex.stackexchange.com/questions/43002/how-to-preserve-the-same-parskip-in-minipage
> > would be good to preserve the ambient values of /parskip and /parindent
> inside
> > minipages.
> >
> > Are there other places minipages are used? I was using them with my
> attempts to
> > have columns for exercisegroups.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rbeezer/mathbook/issues/119>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rbeezer/mathbook/issues/119#issuecomment-115036938>.
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by davidfarmer** [comment]
I suggest avoiding minipages at all costs.  They are a hack
which (until I see a counterexample) I believe do not have a
place in a structured document.

**Comment by Alex-Jordan** [comment]
But they have already been employed for making `<sidebyside>` work.

**Comment by Alex-Jordan** [comment]
Actually, the culprit here seems not to be the minipage, but the parbox that comes from `<paragraphs>`.

**Comment by rbeezer** [comment]
And presumably the technique in that StackExchange post would work for adjusting the behavior of all the parboxes (which are maybe all nested inside minipages?).

Defining a new environment in the preamble would make the body more sematic (and less portable).  But it would isolate the minipage and maybe sometime a btter alternative could be employed.

**Comment by Alex-Jordan** [comment]
Currently, it seems that the only \parbox's and the only minipage's in use are from sidebyside elements.

**Comment by rbeezer** [comment]
Many \minipage and \parbox now in the LaTeX output for `sidebyside`.  Not semantic, but `sidebyside` is more layout than anything else, a deviation from vertical flow to horizontal flow.

Is this still an issue?  In other words, can it be closed or is it still relevant?

**Comment by davidfarmer** [comment]
I suggest closing this and opening another issue about refactoring sidebyside in LaTeX.

What I would like to see (unless for some reason there are technical issues) is the
LaTeX markup be transparently equivalent to the MBX markup, using a "sidebyside"
macro that is defined to do whatever it needs to do.  It is perfectly fine if the definition
of the macro uses minipage and parbox.

**Comment by Alex-Jordan** [comment]
Not answering your question, but in CLM, I set `\parindent` to 0 globally, so I skirt one of the issues. 

Consequently, I set `\parskip` to be nonzero to clear up when new paragraphs begin. But I'm not sure if there are any more instances where the `\parskip` setting would matter in sidebysides in CLM. I may not have any more `paragraphs` in sidebysides.

If helpful, here is a section I threw into minimal to see. Additionally set `\parskip` to nonzero to see that inconsistency too:

```
        <section>
            <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>
            <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>
            <sidebyside widths="47% 47%">
                <paragraphs>
                    <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>
                    <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>
                </paragraphs>
            <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>
            </sidebyside>
            <p>This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph. This is a paragraph.</p>
        </section>
```

**Comment by rbeezer** [comment]
With recent work (see #477) the sample article and LaTeX code have no `\minipage`.  There are very limited uses of `\parbox` in the "contributors" section and a throw-away error message for unimplemented side-by-side stuff.
