### ISSUE TITLE
Broken link to MathJax documentation in Guide

### ISSUE THREAD

**Issue by sean-fitzpatrick** [rbeezer/mathbook#1194]
Section 4.8 of the guide points to the following URL:
http://docs.mathjax.org/en/latest/tex.html#supported-latex-commands

This link no longer appears to work.
The correct link (I think) is http://docs.mathjax.org/en/latest/input/tex/macros/
but it's also version-dependent. (This is for MathJax 3.0; there's also one for 2.7.)

Apologies for the issue rather than a pull request -- trying to meet other deadlines at the moment.

**Comment by rbeezer** [comment]
Thanks very much for the heads-up!  Fix in place at 05e8001a72f1aabea04a719a8bcf5c1449a753f8 but no website update just yet.
