### ISSUE TITLE
Paragraphs containing too much or too little

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1195]
Part of the PreTeXt Javascript adds id's to paragraphs that
do not have one.  Probably that should be obsolete, because
all HTML p should get an id.  Here are some examples that do not.

In the sample article
https://pretextbook.org/examples/sample-article/html/section-sage-cells.html
immediately aboge "Titled Sage Cells." there is a p with no is and which only contains white space.

In the sample article

The last two p, such as the one containing "Here is a local cross-reference:" do not have an id.  (These are split apart
from a PTX p that contains display math.)  (By the way:
the javascript appends -part2, -part3, etc, to the id of
the first p in the group.)

Similarly in the sample article
https://pretextbook.org/examples/sample-article/html/graphics.html#subsection-30
in the two HTML p following the p with
"There are suggestions online that"

Finnally, what actually got me started on this issue is
cases where an HTML p contains content is should not have
(such as a div), so the browser inserts more p's,
which of course do not have an id.

This link will probably change:
http://alir.jsturcotte.profweb.ca/sec-vec.html
but what it illustrates is that if you have a `<sage>` 
inside a `p`, then that persists to the HTML.  The sage
becomes a div, which is not legal.  So extra p's are created.
See the paragraph beginning
A-t-on été chanceux avec ces exemples?

I suggest putting a sage in a p in the sample article,
or banning it from the schema.

**Comment by kcrisman** [comment]
> I suggest putting a sage in a p in the sample article, or banning it from the schema.

My understanding was that we weren't supposed to put `<sage>` in a `<p>`, and the [current schema](https://pretextbook.org/doc/schema/schemas/pretext_xsd/elements/sage.html) seems to support that contention.  Logically speaking I've often wanted to do so, but refrained from it for precisely this reason.  So hopefully that would remove at least some of the potential extra `p`s.

**Comment by rbeezer** [comment]
The schema does not allow a "sage" inside a "p", as KDC notes.  So I'm going to close this one.

**Comment by davidfarmer** [comment]
Should I resurrect the first two items (which take examples from
the sample article) in another issue?

**Comment by rbeezer** [comment]
Re-opened.  I did not understand that the run-in was disjoint from the `sage` material.  Felt like explanation (since I'm not sure how these `p` are not getting ids!)  I'll investigate.

**Comment by rbeezer** [comment]
> Immediately aboge "Titled Sage Cells." there is a p with no is and which only contains white space.

The content is a bunch of "idx" used to test sorting.  Code should recognize that the processed content distills down to nothing (i.e. pure whitespace).  In other words, I thought this was happening already.

> The last two p, such as the one containing "Here is a local cross-reference:" do not have an id.

Do you remember where we discussed this before?  That is, what we were going to do to the id of subsequent "split out" `p`?  There was the situation of having no (or empty) `p` for the very first one, which needs an accurate id as a target of cross-references.

**Comment by rbeezer** [comment]
> The content is a bunch of "idx" used to test sorting. Code should recognize that the processed content distills down to nothing (i.e. pure whitespace). In other words, I thought this was happening already.

The whitespace nodes in this "paragraph" are being removed at #1153, so this HTML `p` (I think it is this one) is now recognized as totally empty and is gone from output.  So is another one.
