### ISSUE TITLE
remove all whitespace between the children of headings

### ISSUE THREAD

**Issue by mxdubois** [rbeezer/mathbook#12]
I'm doing the spacing for environment and section headings in the CSS, as mentioned in mxdubois/fcla-styles/issues/25. Part of it was broken before, but it's fixed now, so it will be important that you remove the whitespace from between the `<span>` elements so that the browser doesn't interpret it as a single space.

There are a couple of different ways to do this:

```html
<span class="type">Proof</span><span class="codenumber">1.2.3</span><span class="title">Loch Ness Monster Proof</span>
```

```html
<span class="type">Proof</span
><span class="codenumber">1.2.3</span
><span class="title">Loch Ness Monster Proof</span>
```

```html
<span class="type">Proof</span><!-- no whitespace
--><span class="codenumber">1.2.3</span><!-- no whitespace
--><span class="title">Loch Ness Monster Proof</span>
```

There also might be some XSLT specific ways to handle whitespace. [This looks promising](http://stackoverflow.com/questions/1468984/xslt-remove-whitespace-from-template).

**Comment by rbeezer** [comment]
This space (and many others) has gone away as a result of cae344d0.

However, it remains to get reasonably easy-to-read indented output instead.
