### ISSUE TITLE
sidebyside paragraphs not flush in LaTeX

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#120]
I've tested the following in the sample-article, so I'm sure this is not specific to my project.

If I have 
```
<sidebyside>
   <paragraphs>
       <content/>
   </paragraphs>
   <paragraphs>
       <content/>
   </paragraphs>
</sidebyside>
```

The left `<paragraphs>` extends a hair or two out into the left margin. It's not aligned with the ambient non-sidebyside content. I've seen this in my project with `<paragraph>-<figure>` and `<paragraph>-<table>` combinations too, and also combinations with more than two items in the `<sidebyside>`. And maybe this is happening on the right too, but it's harder to see.

**Comment by cmhughes** [comment]
Is this happening in Latex and in HTML? Could you provide a bit more detail
about the content inside the paragraphs element?

**Comment by cmhughes** [comment]
It'd be great if you could provide a small, complete minimum working
example to demonstrate this, as I don't see it happening in any of the
examples in sample-article. I suspect that the contents are a little too
wide for their boxes.

**Comment by Alex-Jordan** [comment]
I think it does happen in the sample-article, but it's too subtle to see in the existing sample-article examples. I added:
```
          <p>Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins.</p>
          <sidebyside>
              <paragraphs>
                  <p>Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins.</p>
              </paragraphs>
              <paragraphs>
                  <p>Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins. Lots of text so we can see the margins.</p>
              </paragraphs>
```
in the section on `<sidebyside>`. Be sure to put it somewhere so that all of this appears on the same page. I put it right after the first sidebyside example with two trefoils. I put a screen shot demonstrating the result at http://spot.pcc.edu/~ajordan/sidebysideflushissue.png. (I may not keep this file there forever, for future readers of this thread.) 

It's quite subtle, but the sidebyside extends a hair into the margin. It stands out more clearly in the calc lab manual when there is a page with a lot of expository text in regular paragraphs, and a sidebyside that has paragraphs on its left.

**Comment by cmhughes** [comment]
Right, I see it now, thanks for the sample code.

It's a matter of a couple of missing % marks at the end of lines, my
apologies.

Rob, there are two parts in *xsl/mathbook-latex.xsl* that currently look
like this (in the current *dev* version, these are lines 2522 and 2538):


* <xsl:text>}&#xa;</xsl:text>*

They both need to be changed to the following (very subtle change, just a
%):



* <xsl:text>}%&#xa;</xsl:text>*

If you prefer, I can submit a pull request, but it sounds like you have a
lot of development going on at the moment, so I figured you might prefer me
simply to point to them.

**Comment by rbeezer** [comment]
Dear Alex and Chris,

Excellent!  The catch, the fix *and* the delivery.

(Yes, I've had my head down all week and made a lot of very fundamental progress).

When I push in a few hours, this will be at  f78bff90  if you want to double-check.

Thanks again,
Rob
