### ISSUE TITLE
Issue with table titles in pdf

### ISSUE THREAD

**Issue by nordstromjf** [rbeezer/mathbook#1230]
I changed all the table captions to titles. Works just fine in HTML. The titles appear below the table (as a caption). In the pdf from latex, however, they appear as titles above the table. For example, see the attached screen shot.
[Screen Shot table.pdf](https://github.com/rbeezer/mathbook/files/4022859/Screen.Shot.table.pdf)

**Comment by rbeezer** [comment]
A "title" for a "table" belongs above.  Its the HTML that has not caught up.

There is a thread somewhere with a lot of discussion about what should be called 
a table.

The upshot of that is that what you have there is probably a "figure", even if 
you call it something like a "payoff table".

Make it a "figure", the "caption" will be below, and name the thing in the caption?

Rob

**Comment by nordstromjf** [comment]
That seems complicated. Basic latex has tables with captions below (not titles), so that would be more standard in math papers. Are you suggesting I wrap all my tabular environments in figure tags? Thus, they would all be labeled as Figure, rather than Table? I’ll think about it, especially since I think I prefer referencing “tables” rather than “figures” throughout the text. I have a lot of tables.

It doesn’t really matter whether they are above or below, but I really have to think about what I want in the long-run, and how I might rephrase tables/figures/ titles/ captions, and referencing them.

Thanks for the quick response. It is still an “issue” that they don’t match ☺ in the HTML and PDF.

Jen

------------------------------------------
Jennifer Firkins Nordstrom
Department of Mathematics
Linfield College

jfirkins@linfield.edu

**Comment by rbeezer** [comment]
LaTeX does not always do things right.  ;-)  For example, I now know that their index is a bit of a mess.

Here's the thread, initiated by @davidfarmer.  Try reading the whole thing, not just the first post.

https://groups.google.com/d/topic/pretext-dev/w1e4dERKZ6M/discussion

I could say more, but gotta run right now.

Yes, still an issue!

**Comment by rbeezer** [comment]
Titles of `table` in HTML output are now at the top, via cd5043de7004fa08f7ebd9fc207003d547c0c071

Thanks, Jen, for the report.
