### ISSUE TITLE
rawgit is going away (affects smart code coloring)

### ISSUE THREAD

**Issue by adam-a-smith** [rbeezer/mathbook#1244]
According to https://github.com/google/code-prettify/blob/master/README.md, the rawgit domain has been deprecated and will be disappearing soon. This will affect smart coloring of code. They have provided a new link for run_prettify.js:

<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

References to rawgit should be replaced by this.

**Comment by rbeezer** [comment]
Thanks for the heads-up!  I'll try to patch this up very soon.

**Comment by rbeezer** [comment]
Done, at 6f4b2f02b143efa1ef5935b8630a3bb30363392b.  Seems to be working fine.

Thanks very much for the heads-up.
