### ISSUE TITLE
typo in Publisher's Guide

### ISSUE THREAD

**Issue by adam-a-smith** [rbeezer/mathbook#1245]
Small typo that needs fixing:

“You can add a watermark to your pdf which will render as large, light grey text, at an angle across teh (sic) page.”

**Comment by Alex-Jordan** [comment]
I made a commit on an open branch that turns all 'teh' typos in the project to 'the'.

**Comment by Alex-Jordan** [comment]
This was addressed in 4aafba890cc9883280204c3a1ccfac8ce4c7a98f, and the issue can be closed.

**Comment by rbeezer** [comment]
Thanks, both!
