### ISSUE TITLE
Math in RevealJs proofs

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1257]
Right now, the black magic being used from (I think) `mathbook-common.xsl` is causing MathJax to ignore math markup found in a theorem's proof:

![image](https://user-images.githubusercontent.com/1559632/76175199-5c8e7b00-6179-11ea-8c3e-1d36194673bf.png)

There's obviously some cruft with the `hidden-content` that isn't appropriate here, which is probably related. But the specific culprit is `tex2jax_ignore` - once that class is removed then the math renders as desired.

**Comment by rbeezer** [comment]
It's being rendered as a "born-hidden" knowl I expect.  A quick fix is to set the switch for that to not knowl (I guess).

I think for slides we likely don't want **any** knowls?  So best to warn if a switch is set and then revert to now knowls?  After these switches become publisher options?

**Comment by StevenClontz** [comment]
Was this closed by accident? I don't believe the issue is resolved.

I don't believe anything in slides should be knowled - in slides, noninteractive content should always be visible without having to interact with the slide.

I haven't worked with how PreTeXt XSL handles knowls yet, so I'm not sure where to start looking. But I'd like to learn, so give me a hint on where to start and I can dig in.

**Comment by rbeezer** [comment]
Accident!  Thanks.

Slideshow converter imports the HTML converter, without "starting" it.  Pass in the "stringparam"  `html.knowl.proof` set to 'no` on the command line to see if behavior fixes itself.

Then in reveal.js conversion override that `xsl:param` by giving it a default value of `no`.  Maybe look for others?

Leave a note that when these become publisher switches we should more actively inform the author that such a choice is a no-go for a slideshow.  And we will then have an internal variable we can set to `no`.  My suggestion of changing the default will allow an author to turn on knowled proofs, but they will soon notice they are bad.

Too much work to make a friendly enforced decision and then rip it out as we move to publisher switches.

A PR killing all knowls this way would be highly welcome!

**Comment by rbeezer** [comment]
#1271 says to close this one.
