### ISSUE TITLE
Enable permalinks for "major items"

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1266]
Where major items definition remains TBD.   See https://groups.google.com/forum/#!topic/pretext-dev/l0fXgoaqX58 and especially https://groups.google.com/forum/#!msg/pretext-dev/0SYn1GAQ3A0/9qiuGkSMBwAJ for some details of why this would be good and how it might be implemented.

**Comment by rbeezer** [comment]
We now have rather extensive permalinks on items in HTML output.  Improvements can be suggested on the lists or noted in new issues.
