### ISSUE TITLE
Better doc for localizations

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1299]
Currently the readme for localizations is the only place where they are documented (see https://groups.google.com/forum/?hl=en#!topic/pretext-dev/VpXRmjgGbgw).  Tasks to fix this, according to @rbeezer:

1.  New subsection in "Overview" that is for the casual reader (curious, newbie, 
etc.) 

2.  Careful usage details for an author in "Topics" 

3.  Cross-reference (1) and (2) both ways 

4.  Developer part:  mention that contributions by email (send me entire edited 
file, so I can make an easy commit) are welcome, if a PR is too daunting. 
Pointing to the README, and the  en-US  file as a template/explanation, should 
be sufficient for anybody who goes this far.  I don't want to duplicate much of 
what is already in README and then have two copies to maintain and sync.

**Comment by kcrisman** [comment]
(Yes, I'm volunteering.)

**Comment by rbeezer** [comment]
> (Yes, I'm volunteering.)

Excellent!  I just **assigned** this issue to you.  That's a first.  ;-)

Off to work on #1298

**Comment by kcrisman** [comment]
Hah, I didn't know that was possible.  Oh what have I gotten myself into!

**Comment by kcrisman** [comment]
Possibly relevant: https://www.w3.org/International/questions/qa-i18n on which word to use.  Since the directory is already called l10n and since those files are the actual implementations as opposed to the infrastructure enabling their development, probably let's stick with that word.

**Comment by kcrisman** [comment]
See #1300

**Comment by rbeezer** [comment]
Implemented at #1300
