### ISSUE TITLE
Sage cell immediately before knowl evaluate button may leak into knowl

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1313]
It seems that if you have a Sage cell immediately before a knowl, in some browsers the "evaluate" button is nearly impossible to actually evaluate.  Pictures are easier here.  These are with Firefox on Mac, though Safari also produced this (did not test Chrome).

Here is the picture at [An Interesting Corollary](https://pretextbook.org/examples/sample-article/html/interesting-corollary.html#mNo).  Note that the evaluate button seems fine, though not highlighted for evaluation, and that the little "hook" on the side of the Example seems to go up into the Evaluate button, though it's hard to see.
![Screen Shot 2020-06-16 at 12 16 44 PM](https://user-images.githubusercontent.com/1775728/84800558-ff9e2e80-afcb-11ea-918f-ede26a3630b6.png)

Here, I have initially placed the cursor at the _exact_ top of the evaluate button, and now it is highlighted.  This was the only way I could get the button to appear; even one pixel up or down and it wouldn't.
![Screen Shot 2020-06-16 at 12 17 06 PM](https://user-images.githubusercontent.com/1775728/84800559-ff9e2e80-afcb-11ea-8202-1fc680cfab96.png)

Here I have clicked on the knowl instead, and now it is clearer the evaluate button is still somehow in the knowl.
![Screen Shot 2020-06-16 at 12 17 35 PM](https://user-images.githubusercontent.com/1775728/84800560-0036c500-afcc-11ea-87a5-113b940bbdf2.png)

Here I did manage to evaluate the Sage button, and the problem has gone away.
![Screen Shot 2020-06-16 at 12 17 43 PM](https://user-images.githubusercontent.com/1775728/84800563-0036c500-afcc-11ea-94df-2012a73d2ede.png)

**Comment by kcrisman** [comment]
This was originally mentioned in a related discussion at #981

**Comment by davidfarmer** [comment]
This is fixed.  The problem was not what it appeared to be.

**Comment by kcrisman** [comment]
That is great.  Can you point to a commit, for reference? (I imagine it is a CSS issue.)

**Comment by davidfarmer** [comment]
https://github.com/PreTeXtBook/CSS_core/commit/b3591538cf394eec2cd934bbe5328dbd3fa4619e

**Comment by kcrisman** [comment]
Great, thanks - also love how eventually all the PTX stuff will be in one organization, make it much easier to track stuff down.
