### ISSUE TITLE
Make HTML index creation less recursive

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1318]
@sean-fitzpatrick reports exceeding the default recursion depth (3000) and success when set to 6000.  The `group-by-heading` template implicates index creation in the HTML conversion.

Limited research suggests XSL processors do not perform optimization when tail recursion is used, so that is not a solution.  Perhaps these grouping tasks (`group-by-letter` also) can be written another way.

This is the most authoritative post I found, but is not XSLT 1.0.  (There are other posts.)

https://stackoverflow.com/questions/58385867/tail-call-optimization-in-xslt-saxon

**Comment by rbeezer** [comment]
Details, if needed:

https://groups.google.com/d/topic/pretext-support/wxP5UNQ4fU8/discussion

**Comment by sean-fitzpatrick** [comment]
I can add that I only exceed the default if I'm trying to build the entire APEX Calculus book. I haven't tested to see just how much I can include before it goes over. 8 chapters is fine. 15 is too many, unless I leave out the back matter and index.

**Comment by rbeezer** [comment]
Good progress at 19f29df9274c10e263586b3ebe72197d91468985.  If testing (reported in `-support` Google Group) confirms, we'll close this and relegate further improvements to "code cleanup" and not specify as a bug.

**Comment by rbeezer** [comment]
@sean-fitzpatrick confirms on the Google Group that the motivating large APEX calculus project behaves at default recursion (3000) and also at 500.  A/B testing on the sample article presents no changes in HTML output.  So, problem solved it appears.

#1322 suggests similar further improvements, but we will not categorize the current situation as a bug.
