### ISSUE TITLE
Fixup dedications

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#133]
The `<dedication>` section of the `<frontmatter>` needs some attention.

See: https://groups.google.com/d/msg/mathbook-xml-support/gx055ylRbyQ/AiSSXHLw1mgJ

**Comment by rbeezer** [comment]
This has been reworked for LaTeX output at 09b03626

HTML renders legibly and properly, but the styling is a bit weak - that will improve with time.

**Comment by klevasseur** [comment]
Dedication title seems fine in html, but doesn't appear in latex.
