### ISSUE TITLE
WW PG problems provoking Python errors

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1343]
Discovered these three in Active Calculus (or more properly, Nebraska's fork).  Last two definitely make a fatal Python error with `last[0]` having an index out of range, and the first makes an error (iirc) but I forget the situation.

Can we catch these and fail more gracefully without having to chase down the source location and comment them out?
```xsl
<webwork source="Library/WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/5_The_Integral/5.5_Net_Change_as_the_Integral_of_a_Rate/5.5.18.pg" />
<webwork source="Library/Michigan/Chap9Sec1/Q19.pg" />
<webwork source="Library/Michigan/Chap11Sec2/Q01.pg" />
```

**Comment by rbeezer** [comment]
I tried to assign this to  @Alex-Jordan, but a ping will have to do.

**Comment by Alex-Jordan** [comment]
If the `last[0]` issue is what I think it is, I brought this up [in the forums](https://groups.google.com/d/msg/pretext-dev/HOG6DUnhbpc/4tT1oXL2AQAJ).

**Comment by rbeezer** [comment]
I think a bunch of those are being caught in AC already and handled gracefully.  Maybe 20 or so?  More than 10, less than a hundred.  So this is new, or a variant?  I think.  I'm not qualified to dig into what's happening on the server.  :-)

**Comment by Alex-Jordan** [comment]
Today Mitch edited about 20 OPL problems with the unstructured solution like in the last two problems here. The OPL PR was accepted and earlier tonight I pulled to the AIM server's OPL. Mitch will report tomorrow which problem files still cause trouble.

**Comment by Alex-Jordan** [comment]
The first one (`<webwork source="Library/WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/5_The_Integral/5.5_Net_Change_as_the_Integral_of_a_Rate/5.5.18.pg" />`) has two issues.

Table construction macros that I've never tried to support. I could look into that, but even if successful it would be a 2.16 thing, not the current 2.15.

Unstructured solution, like the 20 others and anything with the `last[0]` issue. Except this one happens to have markup like an `alert` tag in the solution, so `last[0]` is not the problem. But an unstructured `solution` gets past the representations build and no idea what might happen next. This is the kind of thing that makes me think not to let this fail gracefully. Maybe in the future when we have an actual PTX validation step during extraction. Then we could say "this `solution` did not pass PTX validation, so we are omitting it entirely from the representations file" and that could be a graceful fail.

**Comment by Alex-Jordan** [comment]
Last two were on Mitch's list that he patched today: https://github.com/openwebwork/webwork-open-problem-library/pull/756

So I expect that if you do a fresh representations build (tomorrow, not tonight :) ) these won't cause trouble. 

The WHFreeman problem was not on Mitch's list. But as noted, it has bigger problems.

**Comment by rbeezer** [comment]
Thanks!  Yes, tomorrow.  ;-)

**Comment by mitchkeller** [comment]
The WHFreeman problem must be in the UNL edition, because it's not in our repo. I ran grep across our exercises files and only found one WHFreeman exercise, but it's 6.1.6.pg

**Comment by mitchkeller** [comment]
Oh, last[0] error is now fixed on everything that's in the official ACS repo.

**Comment by Alex-Jordan** [comment]
Unsure if there is still an issue here. In a sense, maybe there never was? Some OPL problems use code that we just do not (and cannot) support. The only options are to code the problem yourself in your PTX source, or edit the problem on the server (often, in the OPL) to use more modern tools. So if there is an action item, I guess it would be to say this somewhere more clearly in the documentation.

**Comment by rbeezer** [comment]
Sounds like we have done all we can, and this should be closed.  Holler or re-open if that is not correct.
