### ISSUE TITLE
Translation of "Evaluate" in sagecells

### ISSUE THREAD

**Issue by JeanSebastienTurcotte** [rbeezer/mathbook#1344]
It seems that if a Sagecell is inside a know, the Evaluate button does not get translated to the book's language.

See the sagecell inside http://alir.jsturcotte.profweb.ca/sec-prodmat.html#ex-prodmatchemins

and compare to those just under the linked example. Also, the programming language used is not displayed.

**Comment by rbeezer** [comment]
I think this is a symptom of #981 - the setup in the `head` has the french version and it is used elsewhere.  Translation happens with the XSL, not with Sage, Sage Cell, or Javascript.  I'm going to close this in favor of it being a clue on the other issue.

**Comment by rbeezer** [comment]
This has been fixed, but will require rebuilding HTML.  See announcement in a few minites on "-announce" list.
