### ISSUE TITLE
handle spaces in @alignat-columns

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1348]
The following PreTeXt chokes when building HTML.

```
        <md alignment="alignat" alignat-columns=" 5 ">
          <mrow>x &amp; &amp;  &amp;+&amp; 2 \, z &amp;+&amp; 6 \, {w} &amp;=&amp; -6</mrow>
          <mrow> &amp; &amp; y &amp; &amp;  &amp;-&amp; 2 \, {w} &amp;=&amp; -3</mrow>
          <mrow> &amp; &amp; 2 \, y &amp;+&amp; z &amp;-&amp; 2 \, {w} &amp;=&amp; -8</mrow>
        </md>
```

In particular it seems that MathJax doesn't like the spaces around 5:

![image](https://user-images.githubusercontent.com/1559632/90092342-466b8480-dcee-11ea-8c14-d07783055137.png)

Removing those spaces allows MathJax to render correctly. So a `normalize-spaces(.)` in the right place might be called for.

**Comment by rbeezer** [comment]
Why would you do this?  ;-) ;-) ;-)

I think MJ can take some of the blame.  But you are right, sanitization is needed, and easy.  Thanks.

**Comment by rbeezer** [comment]
Fix is in, and cursory testing.  Holler if anything is up.  At fbe157f9e1becffd6611a7f8c1c266d412abc9dd

Will you report upstream?  Thanks for the alert!

**Comment by StevenClontz** [comment]
Great thanks! We found it because the author passed the number of columns as a Sage integer, and CheckIt converts non-String data via its latex method, adding the spaces.
