### ISSUE TITLE
Environment references--numberless undefined.

### ISSUE THREAD

**Issue by LaserTron** [rbeezer/mathbook#1359]
Mathbook compiles perfectly to html but when compiling to latex I get:

```
IntroCGGT.tex:513: Environment references--numberless undefined.
IntroCGGT.tex:513: leading text: \begin{references--numberless}
IntroCGGT.tex:521: \begin{document} ended by \end{references--numberless}.
IntroCGGT.tex:521: leading text: ...., April 2017\end{references--numberless}
make: *** [makefile:11: latex] Error 2
```
This may be because I have a "References" section at the beginning of my book.

**Comment by rbeezer** [comment]
> This may be because I have a "References" section at the beginning of my book.

Almost certainly.  Please read:

https://pretextbook.org/doc/guide/html/topic-divisions.html

Then consider setting up schema validation, it would have warned you about this:

https://pretextbook.org/doc/guide/html/schema.html

I suspect this is not a bug.  In which case the "pretext-support" list is a good 
place to ask for more explanation.

**Comment by LaserTron** [comment]
Ahh! I (sort) of understand. At any rate following the indications of [https://pretextbook.org/doc/guide/html/topic-divisions.html](https://pretextbook.org/doc/guide/html/topic-divisions.html) gets rid of the latex compilation errors, so it's not a bug.
