### ISSUE TITLE
Add publisher support for merging project-like and theorem-like numbering

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1361]
My understanding https://groups.google.com/g/pretext-support/c/-lxoiZTGzAU/m/X2KwhFlVAQAJ is that there's no current way for a publisher to have Project-likes and Theorem-likes share the same numbering scheme.

If I can contribute to this, let me know.

**Comment by rbeezer** [comment]
In `pretext-common.xsl` find

```xsl
<xsl:variable name="b-number-project-distinct" select="true()" />
```

Override it in extra XSL and report any bad behavior.  Waiting on a better publisher switch.
