### ISSUE TITLE
behavior of is-structured-division template

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1366]
This template from -common has me scratching my head.

https://github.com/rbeezer/mathbook/blob/9766f85ebff4e8c7361dda95ecf36fbccae75ad5/xsl/pretext-common.xsl#L3555

The commentary suggest that I could have a chapter with some unstructured content and then at most one of each specialized subdivision. Like one `exercises` or one `worksheet`. Or I could have a chapter that is fully structured with sections. And I gather the purpose of this template is to distinguish which type of chapter I have. But it returns true any time the chapter has an `exercises` or a `worksheet`. So it returns true even when I have an "unstructured" chapter.

My question is, is this template working as it is supposed to work? Or should the test for the `if` simply be `part|chapter|section|subsection|subsubsection`? Or do I misunderstand the function of this template?

**Comment by rbeezer** [comment]
Yep, that is a head-scratcher.  I have no explanation.  Look at Section 32 of the sample article online, and see how wrong it is.  I'll leave it up for a bit before rebuilding with new code, which makes it right.  I've been aware of this bug for some time, but never chased it down, so thanks very much for spotting it.

Minor change, at 0f544f959edda80c74a7184f65a681fa0879ecf2

**Comment by Alex-Jordan** [comment]
OK, I see section 32, if you want to update anything that is posted. I found this while making a worksheet in an unstructured chapter, and was similarly getting a numbered worksheet when I thought it would be unnumbered.

It's natural to only have one `exercises` in an unstructured division. With `worksheet`s, it may be natural to have more than one. But I guess we would say "sorry, you have to structure the division first". Does that sound right?

**Comment by rbeezer** [comment]
> It's natural to only have one `exercises` in an unstructured division. With `worksheet`s, it may be natural to have more than one. But I guess we would say "sorry, you have to structure the division first". Does that sound right?

Yes, that is the compromise to not have visible numers on the situation like the lone `exercises` you describe.

But we need to "solve" the problem where a division is 100% `worksheet` - right now that will not be recognized as a structured division.  In the groups, not here.
