### ISSUE TITLE
squelch redudant headings for answers in backmatter

### ISSUE THREAD

**Issue by byoshiwara** [rbeezer/mathbook#1370]
Discussed in https://groups.google.com/g/pretext-support/c/rTv5gZjpjbU/m/psXb7GAgCAAJ

Every answer is labeled "Answer" even if the backmatter is collecting only answers.

**Comment by rbeezer** [comment]
Implemented for LaTeX, discussion coming on originating thread.  2a0eb21bfb82a44861216672ea6124a47b738ea0
