### ISSUE TITLE
Remove dependency on menukeys

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1379]
The `menukeys` package is used for `\kbd` and nothing else (if I have read the
source correctly).

`menukeys` uses `catoptions`, which has caused problems:

https://groups.google.com/g/pretext-support/c/bK1ej7e3u8c

I believe it should be possible to avoid loading `menukeys` by directly
authoring the `\kbd` macro, which can be copied from the package.

**Comment by rbeezer** [comment]
The LaTeX team pinging the `menukeys` author here:

https://github.com/tweh/menukeys/issues/59

Note the very last post has a (temporary) workaround which would mean manually adding one line to our latex output at the very beginning of the file.

`\RequirePackage[2020-02-02]{latexrelease}`

**Comment by rbeezer** [comment]
Tried to chase my way through the various macros chained together to define `menukeys` `\keys` command.  No real luck.  So I suspect defining our own from scratch might be a better approach.

**Comment by rbeezer** [comment]
A careful experiment indicates that `menukeys` is the only package that relys on `catoptions`.

**Comment by rbeezer** [comment]
Perhaps some shovel-ready `TikZ` code here:

https://tex.stackexchange.com/questions/5226/keyboard-font-for-latex

**Comment by rbeezer** [comment]
Replacement should not make a line of text any taller or deeper than normal, so as to not mess up line-spacing (as much as possible), and should respond to the ambient font size (`em` or `ex` units).

**Comment by mdoob** [comment]
Late to the show. Judy slipped on the next-to-bottom stair in our place and broke her ankle in three places. Snce we have no family here in Winnipeg, I'm the duty nurse, among other things. Expected recovery time is eight weeks.

Would the from-scratch code I wrote when I was visiting you in December be useful, or do you wish to
limit yourself to packages on CTAN that are being supported.

**Comment by rbeezer** [comment]
> Late to the show. Judy slipped on the next-to-bottom stair in our place and broke her ankle in three places. Snce we have no family here in Winnipeg, I'm the duty nurse, among other things. Expected recovery time is eight weeks.

Hadn't seen you and was hoping it wasn't bad news.  At least it is not worse.  Please give my best to Judy.

> Would the from-scratch code I wrote when I was visiting you in December be useful, or do you wish to
limit yourself to packages on CTAN that are being supported.

I'm imaging a macro (`kbd` may be what we have now), that only depends on `tikz` for visual effects, and no more packages than what we already depend on.  Can't recall the exact details for what you put together that week.  Thanks for looking into this one.

Rob

**Comment by davidfarmer** [comment]
I think a good solution involves no packages,
except maybe for tikz?

**Comment by Skillmon** [comment]
Just to let you know, I've created a PR on `menukeys` to remove the `catoptions` dependency such that it should work with the latest LaTeX kernel. You can see it [here](https://github.com/tweh/menukeys/pull/60).

**Comment by mdoob** [comment]
I guess I should let this thing sit as is until I hear otherwise. In passing, Figure D.7.1 
 https://pretextbook.org/doc/guide/html/vi.html
is done entirely with asymptote, while the surrounding text uses kbd.

**Comment by rbeezer** [comment]
@Skillmon - thatks for letting us know.  I just subscribed to that PR.

@mdoob - yes, let's wait on tht PR and re-evaluate the situation then.

**Comment by Skillmon** [comment]
Just out of curiosity I wanted to ask what the current state of this is?

**Comment by rbeezer** [comment]
@Skillmon - we've made no changes, so author's projects should be including this package if they choose to have certain keys displayed.  I'm going to close this, but it'll be around until CTAN migrates into places like TeXLive and then migrates into distributions, etc.  Somehow I missed the merge on this, despite being subscribed.  Thanks for pinging this one, and of course, thanks for the fix.
