### ISSUE TITLE
\pmatrix doesn't compile in latex

### ISSUE THREAD

**Issue by LaserTron** [rbeezer/mathbook#1396]
I thought I should bring it to your attention that MathJax and LaTex implement the `pmatrix` differently.

In MathJax `$\pmatrix{1\\0\\0}$` makes a nice curvy column vector. This doesn't work in latex which prefers `$\begin{pmatrix}1\\0\\0\end{pmatrix}$`.

This is not a big deal as I simply defined a macro that gives me the MathJax functionality, but maybe you want to fix this given the PreText promise to write once, compile everywhere.

Leaving things as-is is also understandable.

**Comment by Alex-Jordan** [comment]
This is interesting, but we usually chalk up inconsistencies between
MathJax and LaTeX as an issue for one of those projects, not PreTeXt.
[Although we might want to have a page in the author guide that lists
known discrepancies. But I would think such a reference would be
useful outside of PreTeXt.]

There is a lot to read here, but to me the gist is that people are not
supposed to use \matrix{} and similar commands when using LaTeX.
https://tex.stackexchange.com/questions/26434/where-is-the-matrix-command
And then maybe MathJax just decided to do more by making them work there.


On Thu, Dec 17, 2020 at 11:56 AM LaserTron <notifications@github.com> wrote:
>
> I thought I should bring it to your attention that MathJax and LaTex implement the pmatrix differently.
>
> In MathJax $\pmatrix{1\\0\\0}$ makes a nice curvy column vector. This doesn't work in latex which prefers $\begin{pmatrix}1\\0\\0\end{pmatrix}$.
>
> This is not a big deal as I simply defined a macro that gives me the MathJax functionality, but maybe you want to fix this given the PreText promise to write once, compile everywhere.
>
> Leaving things as-is is also understandable.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by rbeezer** [comment]
Thanks, @LaserTron! This discepancy is now addressed in a new section of "Notes" about authoring mathematics.  Thanks, @Alex-Jordan  - that link was very helpful.

At 4173bc78679465cbc9cdc9fdd65ad78701ce3d20

And https://pretextbook.org/doc/guide/html/topic-mathematics.html#mathematics-notes

We could expand that should anybody want to solicit more gotchas from the fora and make a PR.
