### ISSUE TITLE
tasks need titles

### ISSUE THREAD

**Issue by twjudson** [rbeezer/mathbook#1397]
An exercise can have a title.  Why not a task.

**Comment by rbeezer** [comment]
Good question.  Put it out there on `-dev` for discussion?

**Comment by rbeezer** [comment]
Implemented at 77b9641b6fb471c06d3ed6780e4ef07d6e2d5c21 and following.

Some more info at:  https://groups.google.com/g/pretext-dev/c/tWFotAmwOgI/m/UW0M2VcBCgAJ
