### ISSUE TITLE
image in aside

### ISSUE THREAD

**Issue by sean-fitzpatrick** [rbeezer/mathbook#1398]
I think I've spotted an item that got missed with sidebyside removal for atomic elements.
In `pretext-latex.xsl`, line 6320, we have `<xsl:apply-templates select="p|&FIGURE-LIKE;|sidebyside" />`.

I think this needs to become `<xsl:apply-templates select="p|&FIGURE-LIKE;|sidebyside|image|tabular" />`

(Noticed this running a diff on my LaTeX output from September against the output from yesterday. There's an image in an aside that was missing.)

**Comment by sean-fitzpatrick** [comment]
Image in assemblage is also not implemented for LaTeX output.

**Comment by rbeezer** [comment]
Fixed now at bde255c8532fbb5cbad5b701805e7d4b7804f811, with updates to the schema that match, at 491c86334159f51b6f5b5bb8d8d4679e36ae5571.

Thanks for the reminder on tnhis one.  Must have been lost during the holidays...
