### ISSUE TITLE
LaTeX appendices in 

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1443]
As an example document for this issue, here is the online PreTeXt guide:
https://pretextbook.org/doc/guide/html/guide.html

It has parts I, II, III, IV, and V. Followed by Appendices.

Here is the same document in PDF:
https://pretextbook.org/doc/guide/pretext-guide.pdf

At least while using Firefox to view the PDF, the navigation panel on the left that lets me jump to a chapter, section, etc. seems to think that the Appendices are _within_ Part V, rather than a peer to Part V.

**Comment by rbeezer** [comment]
Getting warm after **many** iterations and combinations, so recording progress.  We already write the `\appendix`.  This works in the Guide, which has other parts.

```latex
\appendix
% \part*{AppendicesFoo}
\phantomsection
\addcontentsline{toc}{part}{AppendicesBar}
```

**Comment by rbeezer** [comment]
Many improvements, as announced on `pretext-announce`.  New code at c852e31f4bea10b41cf7c3fee4ef9b2b3ac1c951

Thanks for sending me down another LateX rabbit hole.  ;-)
