### ISSUE TITLE
A link for content born as a knowl is too vertical

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#145]
For example, hover on knowl link for Figure 9.1 at  http://beezers.org/knowlized/section-9.html  and you will see vertical bars at the eleft end that extend well above and below.

I had to put an `article` and an `h5.heading` *inside* of the knowl's `a` to get the formatting of the link text to be correct (font, spaces, etc).  That seems to be the source of the height.

Going "inside-out" (putting the knowl anchor inside the article and heading) meant the text was not formatted (and I expect space would still be there).

**Comment by davidfarmer** [comment]
Fixed by the last several lines in
http://aimath.org/mathbook/mathbook-add-on.css

**Comment by rbeezer** [comment]
This finally went away with more CSS.  Some details at:

https://groups.google.com/d/msg/mathbook-xml-support/ZPacr-yIOUk/5rpE_PWJBwAJ
