### ISSUE TITLE
Document possible workarounds for big latex images

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#1466]
Some tikz or other `latex-image` images can be very wide, but resize nicely in various html outputs.  Because we currently use document class article for our conversion to pdf of such images, they can get cropped (unintentionally) on the right.  

Some workarounds suggested at this thread are:

- Make a separate standalone class document and use pdf2svg separately (not with pretext script)
- Use resizebox
- Use geometry package to resize fonts or other shapes

**Comment by rbeezer** [comment]
A (supported) workaround is now described.

Work at 2fa39bd6594069f85e158286347a61882334cc11

Some explanatory discussion on `pretext-dev`.

Thanks, @kcrisman
