### ISSUE TITLE
tabular/row/@header="yes" overrides things like @bottom="minor"

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#1502]
When setting`@header="yes"` on a `tabular/row`, `pretext-html.xsl` is only adding the appropriate CSS class to produce header row formatting (bold) and is not providing the necessary selectors to enable things like `@bottom="minor"` on the `row`. (This may also be an issue for LaTeX, but I have not looked into it.)

**Comment by rbeezer** [comment]
LaTeX seems fine.  I strongly suspect this is a CSS issue.  So looping in @davidfarmer.

Brand-new Table 13.23 should have a `major` border below the header and a `minor` border below the last row.  I see classes `b3` and `b1` (respectively) and only the latter is visible.  Selection on `tr.header-horizontal` must be interferring with the `b3` on the `th`, **OR** perhaps the `th` never got all the classes for the various borders, such as already exist for `td`.

https://pretextbook.org/examples/sample-article/html/table-calisthenics.html

**Comment by davidfarmer** [comment]
Somehow the th were never styled, only the td.

Added that for this case, and will go back later and
take care of the others.

Please check for desired behavior before closing.

**Comment by rbeezer** [comment]
Looking good.  So closing this.  Probably missed because I included no good examples.  :-(

I've added another example to the end of

https://pretextbook.org/examples/sample-article/html/table-calisthenics.html

which puts various rules into/across the two-row header, which should be useful for the testing subsequent CSS additions.

Thanks!

**Comment by rbeezer** [comment]
Forgot to push before rebuilding website versions.  Wait about 10 minutes....

**Comment by davidfarmer** [comment]
I didn't see the two-row header with rules, but maybe it is
not live yet.  When it is, the CSS should work.

**Comment by rbeezer** [comment]
I see that you've found it.  Or did some CSS blindfolded?  Looking good...
