### ISSUE TITLE
Wrap li content in p (if not authored) in pretext-html.xsl

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#1517]
For both EPUB (to fix formatting on Kindle) and HTML (for @davidfarmer's in-browser editing), we need an li without structured content in PreTeXt source to produce li/p in the output HTML. Since both HTML-driven formats want this, can change in `pretext-html.xsl`.

**Comment by rbeezer** [comment]
Done at a44963ee3408aa5ea0915776cd6e1fee94cdbb7d.

*  Well-tested on the sample article.  Pretty clean to implement.
*  One mild weakness.  Needs to follow the schema to determine a list of elements that can be used to indicate a structured list item.  A structured list item composed of **only** schema violations (say, one list item with a `definition` and a `theorem`) will get wrapped in a `p`!  Be on the lookout, especially if the schema violation seems common and reasonable.  List is
```
p|blockquote|pre|image|video|program|console|tabular|&FIGURE-LIKE;|&ASIDE-LIKE;|sidebyside|sbsgroup|sage
```
* The manufactured "p" might need an HTML `id`?  I put a derived `id` on such a `p`, somewhat contrived to preserve uniqueness.  That can easily change in any way, including deletion.  If so, please advise.
* Website update will come in the next couple days.  Until then, you'll need to build your own examples to test/employ.

**Comment by sean-fitzpatrick** [comment]
I have probably lost track of something along the way, but:
Two years ago we implemented using `<li><m>` as a way to get automatic display style in lists of equations.

Is that affected by this change? (I vaguely recall that there was some later update to this but can't track it down now.)

**Comment by davidfarmer** [comment]
li containing only an  m  will still be a special case which
gets displaystyle automatically.  (And the  m  will be wrapped
in a p).

**Comment by rbeezer** [comment]
The behavior you are asking about is a property of the `m` and its surroundings, as **authored**.  I thought to add the "missing" `p` with the pre-processor, but *did* remember that this would wreck the auto-displaystyle.  And the "extra" `p` is just needed for HTML output, so it happens only in tht conversion and the `m` element processing is universally unchanged.

**Comment by sean-fitzpatrick** [comment]
Ah, got it! (I think.)
So in PTX source we keep 
```
<li>
  <m>mathmathmathmath</m>
</li>
```

and XSL will turn that into (in HTML)
```
<li>
  <p>
    \(\displaystyle mathmathmathmath\)
  </p>
</li>
```
with no pre-processing required.

**Comment by rbeezer** [comment]
Exactly.
