### ISSUE TITLE
EPUB: Spine has things it shouldn't

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#1525]
`manifest` in EPUB is being done smartly (avoiding duplicates), but `spine` is not and this means that some things are winding up on the `spine` that are not in the `manifest` (and do not exist as files). Exemplar of this is @oscarlevin's DMOI, which has an `exercises` in each `section`, and there is no `.xhtml` file for the `exercises` as they are in the enclosing `section`'s `.xhtml` file. EPUB validator doesn't like this. EPUB readers seem OK with it, but Kindle Previewer barfs.

**Comment by rbeezer** [comment]
Should be fixed up at d97859af85dc85a388a4c8af3f69e003010e3907, and examples added into `epub-sample.xml` at 84465a9007796c12099925c81b42a8d3ab9bf99e

While in the neighborhood, I turned on indentation for some (all?) of the generated files.  Validator and calibre both seemed happy with that.  East to revert if Apple or Amazon are unhappy.

**Comment by mitchkeller** [comment]
Kindle Previewer app is still barfing on the Sampler, but it loads properly online. I will put some effort into getting the Sampler in a form that can reliably load into the app for testing. Hopefully @oscarlevin can try building DMOI again using my most recent `epub-test-ol` branch and confirm that Kindle Previewer is no longer finding cause to complain.

Amazon and Apple are happy with the indented XHTML, and it's a lot easier to deal with if going in to debug something.

**Comment by oscarlevin** [comment]
Building DMOI as kindle now opens with the kindle previewer.  Yay!
