### ISSUE TITLE
Standalone worksheet should mimic embedded HTML structure

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1526]
The standalone HTML of a worksheet (after clicking A4 or US) should be the same as
the structure when it appears on an HTML page surrounded by other material.

In other words, the contents of #content on this standalone page:

https://pretextbook.org/examples/sample-article/html/worksheet-1-A4.html

should be #worksheet-1 on this page:

https://pretextbook.org/examples/sample-article/html/worksheets.html

The standalone page has classes on the body which are needed, and which are okay as-is.

**Comment by rbeezer** [comment]
Beta at: https://pretextbook.org/beta/2021-07-03

Don't panic if images are messed up.  Did not preview.

Making two new worksheets was a bit of a hack.  Making two new worksheets, very much like any other division seems even weirder.  ;-)  So code is a mess (hack on hack).  **Confirm** carefully this is what you want, then I can refactor with confidence, checking my work as I go.

**Comment by davidfarmer** [comment]
Yes, that is what I wanted.

Now I need to make the javascript handle this structure.

Closing.

**Comment by rbeezer** [comment]
Division creation refactored to support this at 4b934c35a31af4e373552a4a7bd370f8953fad45.  Two hacks replaced by proper work to generate the standalone worksheets as desired, at 6fccfadc8811eb52da4ca3f16b1c2ce3421e1c7a.  Only change from hacks-version is multiple stray SVG namespace declarations consolidated on the overall "section" element meant for the entire worksheet.

Rebuilding website examples right now, wait a few minutes.
