### ISSUE TITLE
Allow image inside assemblage

### ISSUE THREAD

**Issue by sean-fitzpatrick** [rbeezer/mathbook#1531]
Right now a sidebyside is allowed in an assemblage, but not a 'naked' image.
Image should be allowed without being in a sidebyside.

**Comment by rbeezer** [comment]
And other un-numbered, recently-liberated rigid items, like a `tabular`.

At 9ab5e0b8ed6fbb1383d14a786834d28195f7aae7

Thanks, @sean-fitzpatrick

**Comment by sean-fitzpatrick** [comment]
By the way, I just noticed that I reported this a while back in #1398, which I think might have been overlooked.
