### ISSUE TITLE
Improve documentation/implementation for frontmatter

### ISSUE THREAD

**Issue by sean-fitzpatrick** [rbeezer/mathbook#1537]
The [documentation for the frontmatter](https://pretextbook.org/doc/guide/html/overview-frontmatter.html) has one typo and one admission: the `acknowledgment` tag should be `acknowledgement` (PreTeXt uses the latter in XSL.)

It would also be useful to clarify the ordering of elements: e.g. `acknowledgement` must become before `preface`, although there can be more than one `preface`, as long as there is nothing between them.

Also, `foreword` is implemented in XSL, but is not in the schema.

**Comment by rbeezer** [comment]
I've fixed the typo (f55efa6a45b5828b31c3912563cfeab7fa17be8c), and drastically updated the documentation of the front matter (though it is still not complete) (55028efb12c92182ad4a3f27f6c7369f44717cb8).  Live on website now, or soon.

Appears I may have Acknowledgements out-of-order, according to the Chicago Manual of Style.  <egg-on-face/>  see #1539.

Foreword is on an existing issue, for another day.  See #706.

Thanks, Sean, for bringing this forward.
