### ISSUE TITLE
update Gallery link to Understanding Linear Algebra

### ISSUE THREAD

**Issue by StevenClontz** [rbeezer/mathbook#1562]
The link on https://pretextbook.org/gallery.html to Understanding Linear Algebra is broken.

I believe this is the correct link: https://davidaustinm.github.io/ula/ula.html

**Comment by rbeezer** [comment]
Thanks very much.  Got done based on a second (offline) suggestion.

Repository is here: https://github.com/PreTeXtBook/pretext-projects

https://github.com/PreTeXtBook/pretext-projects/commit/5163597e8a57fb72e2e65623d00662269260f2c1
