### ISSUE TITLE
permalinks on exercisegroups missing/misplaced

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1571]
The permalink for this exercisegroup:

Exercise Group: Two Derivative Problems 
https://pretextbook.org/examples/sample-article/html/section-11.html#p-440

is placed left of the introduction sentence, not left of the title. 

Further down there is an exercise group with title "Two More Derivative Problems" that has no introduction, and it seems to have no permalink.

**Comment by Alex-Jordan** [comment]
Also happening with "paragraphs". See: 

Paragraph 
https://pretextbook.org/examples/sample-article/html/interesting-corollary.html#p-206

**Comment by Alex-Jordan** [comment]
Nevermind about `paragraphs`. I was seeing the `p`'s permalink. There is another for the `paragraphs` in the right place.

**Comment by davidfarmer** [comment]
The permalink on an exercisegroup *with a title* should now be okay.

Once you merge the pending pull request which always puts a title,
please check and then close this issue.

**Comment by rbeezer** [comment]
Looking good - thanks, both.  "Extensive" testing in

Section 11: Further Reading 
https://pretextbook.org/examples/sample-article/html/section-11.html#section-11
