### ISSUE TITLE
Period in wrong place for Hint title

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#1584]
Hints with numbers have the period in the wrong place:

Hint. 1

instead of

Hint 1.

https://pretextbook.org/examples/sample-article/html/exercises.html#exercise-117

Also, the period is plain text, but it should be wrapped in a span.period .

**Comment by rbeezer** [comment]
See change at #1520, which placed the period prematurely.

Also review #1518, and 973736bc9d1e51d38cf29f07018b7a1cc8f012bf

Pinging @mitchkeller.

**Comment by jjrsylvestre** [comment]
Same thing happens with numbered solutions to ExampleLike.

https://sites.ualberta.ca/~jsylvest/books/EF/section-permutations-counting.html#problem-74

(Built using aa872180bd6d7474a5db96bba5b888cb0702665a.)

**Comment by davidfarmer** [comment]
Also in the title of li and example here:
https://sites.ualberta.ca/~jsylvest/books/EF/section-logic-equiv-prop-calc.html

Apparently
`template name="period-styled"`
is not being called

**Comment by rbeezer** [comment]
Fixed up the override in EPUB previously, but didn't think to look back at base HTML.  Corrected in `heading-simple` template, which I think is just used for `SOLUTION-LIKE` (testing indicates this is so).  Before/after testing, visual inspection, all look good.  Rebuild to take effect.

Note that this also affects heading like `Hint.` in HTML, but no visual distinction.

Titles in list items and examples:  I understood `span` with `.class` equal to `period` and `space` to be **necessary** when **we** create a heading/title that looks like

```
Theorem 5.6.3.
```

perhaps followed (optionally) by an author-provided title.  We manipulate that author-provided title by adding a period, but **not** if the author has punctuation there already, like a question-mark.  This happens in -common for consistency.  To now mark-up that period specifically for HTML would be a big change.

Thanks, Jeremy, for the heads-up (in exactly the right place).  Examples re-built at website.

Rob

**Comment by rbeezer** [comment]
Forgot to close this.  Changes at 4712a4caa53a7d6b863ce761f55ec92dd868bcbd
