### ISSUE TITLE
LaTeX tabular: scale down, not up

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1615]
For a tabular in LaTeX, there is an ambient width. Sometimes author-declared, sometimes implied. Currently the tabular is scaled (up or down) so it fits that width.

Proposal is to make it scale down when needed. But leave the tabular at its "natural size" when it is small enough to fit. And then center it in the available space.

**Comment by rbeezer** [comment]
Now implemented at 2ac5d0711a9378bcaa423a0e62746d6c257a7e21, with a related modification at 45519650d277d832c24fd4cd155fdedc322361f1.  More on -announce shortly.
