### ISSUE TITLE
xelatex element

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#1616]
We have `<tex/>` and `<latex/>`. We actually use and reference XeLaTeX more than TeX (but less than LaTeX). Maybe we should have a `<xelatex/>` element.

**Comment by rbeezer** [comment]
PR welcome.  Should be easy to find instances with a case-sensitive search (and maybe also for mis-typed cApiTaliZations!)

**Comment by rbeezer** [comment]
Done, sort of.  Plus `XeTeX`.  Read about shortcuts in the `-common` part of 571a015374f0a4c112397c3aaab8839f9ea7edf2

We actually do not mention `XeLaTeX` very much, it is usually the executable `xelatex`.
