### ISSUE TITLE
label=""  writes the word "none" in the latex-output

### ISSUE THREAD

**Issue by antfp** [rbeezer/mathbook#163]
When we define a list like the following
```
<ul label="">
<li><p>one item</p></li>
<li><p>another item</p></li>
</ul>
```

the latex output writes the word "none":

none one item
none another item

This can be fixed by replacing in matchbook-latex.xsl

```
<xsl:when test="@label=''">none</xsl:when>
```
by
```
<xsl:when test="@label=''"></xsl:when>
```
Regards
António

**Comment by rbeezer** [comment]
Dear António,

Thanks very much for the careful report.  I appreciate the help.

That was the correct string for the HTML output. A bad cut/paste job. ;-)

Fixed at 35500af8.

Thanks, 
Rob
