### ISSUE TITLE
en dash on references for exercisegroup

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#164]
I think when you xref an exercisegroup it should use an en dash instead of a hyphen.

**Comment by rbeezer** [comment]
You noticed. ;-)

I think so, too.  Wanted to try being fancy and do it "generically" with 
something like an "abstract" template.  But have not decided the best way yet, 
since there are many places to do this sort of thing carefully (esp. 
non-breaking spaces).

**Comment by rbeezer** [comment]
This, and more, implemented at f1933fe1  Thanks for the push.

A nice feature (which I should now mention in the sample article) is that with an <q>autoname</q> you will get a non-breaking space between the name and the reference, in both LaTeX and HTML and ...

There are probably more places to consolidate two nearly-identical templates (say, for LaTeX and HTML) into the <q>common</q> file by simply handling a few special characters (or simple markup) in an identical, or similar, way.
