### ISSUE TITLE
Safer HTML file generation with pretext/pretext script

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1646]
At a13b360cb629f9652de181e76c48b9888157f7a4 there is a fix allowing HTML output from the `pretext/pretext` script to overwrite that of a previous run.  Capturing a further suggestion here.

Perhaps an even safer approach is to copy the destination directory to a backup name like
```
*.bak-2021-12-27-14:23:47
```
or similar.  The question would be how much do we trust a publisher to do exactly what they ask for, versus how much we should be messing with a publisher's file system to prevent accidents (should the destination directory have other, unrelated files in it).

This shouldn't be an issue for the PreTeXt-CLI (@StevenClontz, @oscarlevin) since it does more project management.  So right now, I come down on letting the script be a bit more dangerous, and the CLI is safer.

**Comment by StevenClontz** [comment]
My philosophy with the CLI is that output is always disposable, up until you run `pretext publish`. Then the CLI does a bit of moving the most recently-generated output files into a `docs/` directory and Git commits/pushes to be served by GitHub Pages.

So yeah, I have no problem with keeping pretext/pretext.py simple.

**Comment by rbeezer** [comment]
This was addressed at 2d66e7eb9365bb593ca8667f413b141a937a21f1 by using a different Python function for copying a whole tree of files, `distutils.dir_util.copy_tree()`.

Likely it can be replaced as we ratchet up the minimum Python version.
