### ISSUE TITLE
[html] `summary-links` anchors missing `internal` class

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/mathbook#1653]
I may be misunderstanding the intent of the `internal` class, but it is missing inside `<a>..</a>` tags contained inside a `<nav class="summary-links">` tag. Is `class="internal"` supposed to be set on all links that reference internal material? If so, it should be added to those links.

**Comment by rbeezer** [comment]
Cross-references within a project (`<xref>` element) are realized by knowls for "small" units of content.  But if an `xref` points to something "big", like a `subsection`, then it is realized as "traditional" hyperlink.

So `a.internal` is meant to signify the latter.  `a.xref` is the former.

The "summary links" are kind of their own thing as a sort of navigation device.  A "summary" page does not really have a good analogue in an non-hypertext setting.

So, @davidfarmer can weigh in, but I don't think `.internal` **needs** to be added.  But perhaps it would be useful in some way.

**Comment by siefkenj** [comment]
It would be useful for my work if all hyperlinks were identified as `internal` `external` or `knowl`. I am working on a caching mechanism, so the default behavior of all the `internal` links needs to be overridden.

**Comment by davidfarmer** [comment]
I don't object to  `.internal`  on summary links.

Does not the same thing apply to the TOC?  Those are some of the same links.

Recall that `nav.summary-links` is the current way we handle the start of a chapter,
and it fails to handle all the existing (or planned) use cases.  But I don't think anyone
has proposed a good alternative.

**Comment by rbeezer** [comment]
`.xref` is a misnomer at present, `.knowl` would be better.  I could liberally **add** `.internal` `.external` and `.knowl`, and the next time @davidfarmer versions the JS we could remove `.xref` (or adjust anything else that is a breaking change).

**Comment by siefkenj** [comment]
> Does not the same thing apply to the TOC? Those are some of the same links.

I'd be happy if the TOC links also had `.internal`.

**Comment by rbeezer** [comment]
OK, I did a survey of what we have.  About 70 places in the HTML conversion where we generate an `a` element.

There are two types of knowls, which get styled different.  "Born hidden" which is  "original content" - knowl hides the "first" occurence of the content.  These are `.original`.  Other knowls are duplicates of content, come from files, and are the result of cross-references (including index locators).  These knowls are always labeled `.xref`.  (But sometime a  cross-reference is implemented as an internal hyperlink, for "large" content.)

Which is a long way of saying a proposed `.knowl` is really a union of `.original` and `.xref`.  They get styled a bit different?  So anyway, I take back what I said in favor of `.knowl`.  ;-)  It could be **added** if necessary.

I'm going to add `.internal` to ToC and "summary-nav" and see if any styling gets clobbered.  We can add more as this evolves.

**Comment by rbeezer** [comment]
Added `.internal` to the ToC and summary links at d82172265f8f0d2cbe11ec48a63c53b51c47615a.  There are plenty of other places that might need this treatment - just ask.

@davidfarmer - I didn't see any effect on styling, so I pushed this out.  Website examples will be updated in next 10 minutes.
