### ISSUE TITLE
Add Open Graph attributes to generated HTML

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/mathbook#1657]
Open Graph annotations help search engines better understand webpages. Most relevant annotations can be autogenerated. They go in the `<head>` of each page.

This website suggests some tags for books: https://webcode.tools/generators/open-graph/book

**Comment by rbeezer** [comment]
That's nice.  And I'm working on support for ISBN just the past few days.  We have ways to populate most everything else.

**Comment by rbeezer** [comment]
Thanks, @siefkenj , for the suggestion.

Initial foray at: c0448bfed4a6ebe19959724d8918d89a8de32501

I'm going to close this, though the four categories implemented here could be expanded.  More discussion comong on -dev shortly.
