### ISSUE TITLE
Wider variety of TeX executables for pretext/pretext script and CLI

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#1658]
Thinking through some proposed changes to executables for the `pretext/pretext` script.  Coordination with the CLI (@StevenClontz , @oscarlevin) would be desirable.

* Add `latex`, `pdflatex`, `xelatex` executables in `pretext.cfg`
* Deprecate current `tex` executable
* Act on a `--method` switch with values identical to the new executable keys, perhaps first for the PDF build
* Respect current `tex` executable, if no better option is present and **not** if a method has been given.  But warn of deprecation (so opt-in to new scheme)

**Comment by StevenClontz** [comment]
Thinking about https://github.com/PreTeXtBook/pretext-cli, I think that this translates to changing

```xml
<executables>
  <tex/>
</executables>
```

to 

```xml
<executables>
  <latex/><pdflatex/><xelatex/> <!-- for backwards compatibility allow <tex/> instead of <pdflatex/> -->
</executables>
```

and changing

```xml
<target name="pdf">
  <format>pdf</format>
</target>
```

to

```xml
<target name="pdf">
  <format>latex</format> <!-- or pdflatex or xelatex -->
</target>
```

**Comment by rbeezer** [comment]
Thanks, @StevenClontz.  Ithink that would map nicely to what I imagine for the core - an extra parameter to specify the executable ("format" or "method", to the publisher) for functions like `pdf()`.  And maybe a recyclable helper function to sort out which to provide and manage the deprecation.

**Comment by oscarlevin** [comment]
What does `<format>latex</format>`  produce?  Does that process the .tex with the program `latex` (getting a dvi?) analogous to `pdflatex` and `xelatex`?  If so, what do you put as your format if you want to get the .tex file back?

**Comment by rbeezer** [comment]
`source` yields `*.tex`.

Yes, `latex` would produce (old-style) `*.dvi`.

**Comment by StevenClontz** [comment]
Hmm. Now I'm wondering if this isn't what we want.

```xml
<target name="pdf">
  <format method="pdflatex">pdf</format> <!-- pdflatex is default, can replace with xelatex -->
</target>
<target name="dvi">
  <format>dvi</format> <!-- uses latex -->
</target
```

In particular, this change wouldn't break current behavior of CLI, which builds pdf format using pdflatex.

**Comment by oscarlevin** [comment]
Current behavior is, I believe, `<format>latex</format>` produces the *.tex, and `<format>pdf</format>` produces a pdf processed with whatever executable is given in `<tex>`.

**Comment by StevenClontz** [comment]
I believe so. So a more complete proposal would be this.

```xml
<target name="latex">
  <format>latex</format> <!--produces *.tex -->
</target>
<target name="pdf">
  <format method="pdflatex">pdf</format>
  <!-- method="pdflatex" is default, uses <executables><pdflatex/></executables> 
      or <executables><tex/></executables> for backwards compatibility  -->
  <!-- can replace with  method="xelatex" and use <executables><xelatex/></executables> -->
</target>
<target name="dvi">
  <format>dvi</format> <!-- uses <executables><latex/></executables> -->
</target
```

**Comment by StevenClontz** [comment]
Since my time is running short this afternoon and I believe Rob said in Sococo/Zoom that he'd be getting this taken care of on the mathbook side this evening, I'll plan to tidy up a PreTeXt-CLI release candidate on Monday that includes this change as well as the fix for sageplot image generation.

**Comment by StevenClontz** [comment]
@rbeezer can you direct me to the relevant commit for this functionality? Also if there's some recent in-development React work that I should avoid merging into this release until things stabilize, let me know.

**Comment by rbeezer** [comment]
May not have existed when you asked.  Been busy with React all weekend.

See your  https://github.com/PreTeXtBook/pretext-cli/issues/194

Patience!  ;-)

**Comment by rbeezer** [comment]
Done, primarily at https://github.com/rbeezer/mathbook/commit/99f07bb5bee71e09d57ddac9a68bd35a343f120c

Plus a commit on either side.

**Comment by rbeezer** [comment]
> Also if there's some recent in-development React work that I should avoid merging into this release until things stabilize, let me know.

Everything is hidden behind undocumented switches.  So you should be safe.
