### ISSUE TITLE
Sage cells without Javascript

### ISSUE THREAD

**Issue by siefkenj** [rbeezer/mathbook#1662]
If sage cells were `pre` instead of `div` and there were a CSS rule `pre > script[type="text/x-sage"] { display: block }` then the code inside of sage cells would show up without Javascript. Since `sagecell.js` removes the `script` tag when it does it's work, this wouldn't affect the functionality when Javascript is active.

One possible side effect is some flickering when the page loads.

**Comment by siefkenj** [comment]
There's no need for hardcoding. We can wait for the CSS to change. For now the <pre> content will just be hidden.

The sagecell selectors in the initialization scripts will also need to be changed to `pre` instead of `div`

**Comment by rbeezer** [comment]
Understood.  If the change survives testing, perhaps it'll go straight into production.

**Comment by rbeezer** [comment]
Change seems to be fine functionally, spacing via CSS needs (cosmetic) reworking, it seems.  I'll ping David on -dev in a minute.

**Comment by rbeezer** [comment]
I meant to check, and say, removing Javascript sort of went as expected - they are indeed totally AWOL (hidden).

**Comment by rbeezer** [comment]
Closed via cad7b83e3440bff4331ad1a888f672c9bed22b3f

Great suggestion @siefkenj  - thanks.
