### ISSUE TITLE
Autonaming with titles should be split out

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#172]
`autoname='title'` really does not fit with the autonaming scheme.  It is a portion (or all) of the text of a cross-reference.  So perhaps we need
1. `title='suffix'` that incorporates the title as a parenthetical comment after something like Theorem 2.17.
2.  `title='only'` to make the entire cross-reference text just the title.  This is useful (and necessary) when targets are not numbered, like fine subdivisions, or when they explicity have their numnbers turned off (which will happen someday).

Original discussion at: https://groups.google.com/forum/#!topic/mathbook-xml-support/Wel4PjpAxSU

**Comment by rbeezer** [comment]
Well, this was broken.  Works now, but still perhaps advisable to consider changes suggested here.  Might be possible within new `xref-prefix` template or with a new `xref-suffix`.  Fix at ef54785f

**Comment by rbeezer** [comment]
Attaching to #385

**Comment by Alex-Jordan** [comment]
Close? `@autoname` is no longer a thing.
