### ISSUE TITLE
Add a <listing> tag for program listings

### ISSUE THREAD

**Issue by rplantz** [rbeezer/mathbook#180]
Something like
&lt;listing xml:id="listing-hello-world"&gt;
     &lt;caption&gt;...&lt;/caption&gt;
     &lt;program&gt;
        ...
     &lt;/program&gt;
&lt;/listing&gt;
so that program listings can be xref-d, similar to &lt;figure&gt;.

**Comment by rbeezer** [comment]
Original discussion at:  https://groups.google.com/forum/#!topic/mathbook-xml-support/mvHg-JmL68Y

Implemented at:  ae3e13a9

Limited testing, please report anything I missed.
