### ISSUE TITLE
Verbatim "code" displayed incorrectly with LaTeX

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#184]
Two reports of odd behavior rendering `<c>` with `xelatex`.  The culprit does not appear to be updates to the `listings` package.  Reports:

https://groups.google.com/forum/#!topic/mathbook-xml-support/gXrv1CxXrvQ

https://groups.google.com/forum/#!topic/mathbook-xml-support/WIAuD0FR1Ww

**Comment by rbeezer** [comment]
I see no change in behavior in Bob's example (pasted below) with an update to listings.  I have no problems either way with an Ubuntu 15.04 installation of TeXLive.   Bob has errors with Ubuntu 15.10.  Alex is on a Mac.

```bash
rob@lava:/tmp$ kpsewhich listings.sty
/usr/share/texlive/texmf-dist/tex/latex/listings/listings.sty

rob@lava:/tmp$ cat `kpsewhich listings.sty` | grep "\\\\file" | head -n 2
\def\filedate{2014/09/06}
\def\fileversion{1.5e}

rob@lava:/tmp$ kpsewhich listings.sty
/home/rob/texmf/tex/latex/listings-2015-11-29/listings.sty

rob@lava:/tmp$ cat `kpsewhich listings.sty` | grep "\\\\file" | head -n 2
\def\filedate{2015/06/04}
\def\fileversion{1.6}
```

Bob Plantz's test example:

```latex
\documentclass{article}
\usepackage{bera}
\usepackage{ifxetex}
\ifxetex
   \usepackage{xltxtra}
   \usepackage{fontspec}\newfontface\listingsfont[Path]{fvmr8a.pfb}
   \usepackage{fontspec}\newfontface\listingsboldfont[Path]{fvmb8a.pfb}
\else
   \edef\oldtt{\ttdefault}\usepackage[scaled]{beramono}\usepackage[T1]{fontenc}
   \renewcommand*\ttdefault{\oldtt}\newcommand{\listingsfont}{\fontfamily{fvm}\selectfont}
\fi
\usepackage{listings}
\lstset{basicstyle=\listingsfont}

\begin{document}
Does random() = \lstinline?random()?
\end{document}
```

**Comment by antfp** [comment]
I'm on a Mac, with  listings version 1.6. With xelatex and pdflatex the test example has no problems for me.

**Comment by rplantz** [comment]
I filed a bug report with Ubuntu regarding this issue. I've attached a .tex
file that illustrates the problem for me, running Ubuntu 15.10.

--Bob

**Comment by Alex-Jordan** [comment]
What I see on my Mac OS 10.8.5:
 
```
SYST104M4138mc:examples alexjordan$ kpsewhich listings.sty
/usr/local/texlive/2014/texmf-dist/tex/latex/listings/listings.sty

SYST104M4138mc:examples alexjordan$ cat `kpsewhich listings.sty` | grep "\\\\file" | head -n 2
\def\filedate{2015/06/04}
\def\fileversion{1.6}
```

With `xelatex` on the sample article, I get the bad spacing errors you can see on page 2 here: http://spot.pcc.edu/~ajordan/derivatives.pdf

**Comment by rbeezer** [comment]
Right, an extra space between each character.  And Bob sees characters shifted 
by one (ie an 'a' becomes a 'b').  And I have no problems under new or old 
"listings".

I believe listings is not at fault, which makes me suspect something about fonts 
is amiss, especially since the errors are different (and feel like encodings or 
glyphs).  Below is info on my system for the Bitstream Vera Mono fonts, as used 
under xelatex.  I'm not sure how to tell if the font has changed somehow.

Rob

rob@lava:~$ kpsewhich fontspec.sty
/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty

rob@lava:~$ cat `kpsewhich fontspec.sty` | grep -A 1 -B 1 "ProvidesPackage"
%%
\ProvidesPackage{fontspec}
   [2014/06/21 v2.4a Font selection for XeLaTeX and LuaLaTeX]

rob@lava:~$ kpsewhich fvmr8a.pfb
/usr/share/texlive/texmf-dist/fonts/type1/public/bera/fvmr8a.pfb

rob@lava:~$ ls /usr/share/texlive/texmf-dist/fonts/type1/public/bera
fveb8a.pfb  fver8a.pfb  fvmb8a.pfb  fvmbo8a.pfb  fvmr8a.pfb  fvmro8a.pfb 
fvsb8a.pfb  fvsbo8a.pfb  fvsr8a.pfb  fvsro8a.pfb

**Comment by Alex-Jordan** [comment]
Here's my corresponding output:

```
alexjordan$ kpsewhich fontspec.sty
/usr/local/texlive/2014/texmf-dist/tex/latex/fontspec/fontspec.sty

alexjordan$ cat `kpsewhich fontspec.sty` | grep -A 1 -B 1 "ProvidesPackage"
%% 
\ProvidesPackage{fontspec}
  [2015/03/14 v2.4c Font selection for XeLaTeX and LuaLaTeX]
alexjordan$ kpsewhich fvmr8a.pfb
/usr/local/texlive/2014/texmf-dist/fonts/type1/public/bera/fvmr8a.pfb

alexjordan$ ls /usr/local/texlive/2014/texmf-dist/fonts/type1/public/bera
fveb8a.pfb	fver8a.pfb	fvmb8a.pfb	fvmbo8a.pfb	fvmr8a.pfb	fvmro8a.pfb	fvsb8a.pfb	fvsbo8a.pfb	fvsr8a.pfb	fvsro8a.pfb
```

**Comment by rplantz** [comment]
My texlive installation is a mess. I originally installed from the Ubuntu
15.10 repositories. When I tried to update, I got error messages. I removed
it and tried to start over again, but it won't completely install. I'm
going to try a ctan install to see if it works any better. Sigh.

--Bob

**Comment by antfp** [comment]
On my Mac, in matchbook-latex.xsl  the "Path" in
<xsl:text>\usepackage{fontspec}\newfontface\listingsfont[Path]{fvmr8a.pfb}&#xa
never gets replaced. Maybe replacing Path by the path to the font helps (on my system it is
 /usr/local/texlive/2015/texmf-dist/fonts/type1/public/bera).

**Comment by rplantz** [comment]
Okay, I did a full install of texlive from ctan, and the xelatex font
problem exists with this latest software. For me, the problem has changed a
bit. With the test-font.tex program I attached earlier, I used to get an
off-by-one error, and now I get an extra space between each (monospaced)
character. I believe my previous fontspec was version 2.4c, and now it's
2.4e.

I have:

bob@bob-ubuntu-desktop:~$ kpsewhich fontspec.sty
/home/bob/texlive/2015/texmf-dist/tex/latex/fontspec/fontspec.sty
bob@bob-ubuntu-desktop:~$ cat `kpsewhich fontspec.sty` | grep -A 1 -B 1
"ProvidesPackage"
%%
\ProvidesPackage{fontspec}
  [2015/09/24 v2.4e Font selection for XeLaTeX and LuaLaTeX]
bob@bob-ubuntu-desktop:~$ kpsewhich fvmr8a.pfb
/home/bob/texlive/2015/texmf-dist/fonts/type1/public/bera/fvmr8a.pfb
bob@bob-ubuntu-desktop:~$ ls
texlive/2015/texmf-dist/fonts/type1/public/bera/
fveb8a.pfb  fvmb8a.pfb   fvmr8a.pfb   fvsb8a.pfb   fvsr8a.pfb
fver8a.pfb  fvmbo8a.pfb  fvmro8a.pfb  fvsbo8a.pfb  fvsro8a.pfb
bob@bob-ubuntu-desktop:~$


--Bob

**Comment by Alex-Jordan** [comment]
Bob, the extra space sounds like the error I have. It's nice to not be the only one anymore. When you have inline `<c>` within a paragraph, do the characters write over the following characters outside the `<c>`? In other words, n units of space are reserved for the string that winds up taking 2n units of space.

**Comment by rplantz** [comment]
Alex, I have attached two files. MonoFont-a.pdf was produced by pdflatex,
and MonoFont-b.pdf was produced by xelatex. It adds the extra spaces after
each character, but the original computation of the block of space required
remains the same.

I emailed a message, with my previous example, to the maintainer of
fontspec earlier today.

--Bob

**Comment by rbeezer** [comment]
This could be fixed at 95d23fbb with proper incorporation of the `sourcecodepro` package to make the default `tt` font be SourceCodePro (for both `pdflatex` and `xelatex` processing).

Please test and report.

**Comment by rbeezer** [comment]
Bob and Alex, is this still a problem?

**Comment by rbeezer** [comment]
@Alex-Jordan @rplantz I'm closing this with all the surrounding recent work. Let me know if it needs to be reopened.
