### ISSUE TITLE
knowl opens in wrong place

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#188]
The knowl directly above Proposition 4.24 on this page:
http://abstract.ups.edu/aata/section-mult-group-c.html
opens at the bottom of the page.

The cause is invalid html because of the interlacing of article and p tags.

(This has been discussed previously and may be fixed in the conversion code
but this is old html?)

**Comment by rbeezer** [comment]
Thanks, David.  I just rebuilt a local copy and the knowl functions as expected. 
  So you are seeing stale HTML.  Sorry about that.

I'll double-check my local build and push that up later today so it is place as 
an up-to-date example.

Rob

**Comment by rbeezer** [comment]
AATA has been updated.  I had to refresh that page to see the knowl open in the right place.  Thanks for pointing that one out.
