### ISSUE TITLE
Sectioning exercises

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#192]
An `exercises` section could sometimes have sections of its own.  A `title` on an `exercisegroup` would be one approach, but maybe does not seem right.

Perhaps `exercises` should not be implemented as a list, and then "regular" sectioning might behave properly (if numbers were hard-coded).

See example here: 

http://faculty.uml.edu/klevasseur/ads-html/

which has "A Exercises" and "B Exercises" obtained as plain text (`p`) in an `introduction` to an `exercisegroup`.

**Comment by Alex-Jordan** [comment]
APEX has "Terms and Concepts", followed by "Problems". 

Two "exercises" sections back to back with titles could mimic this, but there's just something I don't like about different sectioning numbers for these.

I thought I could just drop "Problems" and put "Terms and Concepts" in an exercisegroup with a title, but I see that a title for exercisegroup is not implemented.

**Comment by Alex-Jordan** [comment]
There is now `subexercises` in translations, though not yet in schema. Close if it makes it into schema?

**Comment by rbeezer** [comment]
Now in schema, at dab792d3647e4bcf12fef2142ae7a466c6298b07.
