### ISSUE TITLE
make first compilation have no error messages

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#20]
This is probably not the ideal intro to MBX for those who haven't already seen you give lots of presentations on it.  Yes, I am on the dev branch.
```
$ xsltproc xsl/mathbook-html.xsl examples/sample-article.xml
examples/sample-article.xml:1068: element biblio: validity error : ID biblio-strang-article already defined
                <biblio type="raw" xml:id="biblio-strang-article">Gilbert Strang
                                                                 ^
URL: demonstration-1.html
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: <cite provisional="just-a-test"> is deprecated, convert to <xref provisional="just-a-test">
MBX:WARNING: <cite ref="biblio-only-a-test> is deprecated, convert to <xref ref="biblio-only-a-test">
MBX:WARNING: unresolved <xref> due to ref="pointer-to-nowhere-as-test"
MBX:WARNING: Cross-reference (xref) with no ref or provisional attribute, check spelling
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "note" into language for code "en-US"
MBX:WARNING: could not translate string with id "backmatter" into language for code "en-US"
```

**Comment by kcrisman** [comment]
Also, my browser can't find
```
file://releases.flowplayer.org/5.4.6/flowplayer.min.js
file://releases.flowplayer.org/5.4.6/skin/minimalist.css
```
not that I have any idea what that is about.

**Comment by rbeezer** [comment]
Thanks, KDC.  I know about all of these and plan to fix them - I should have 
more time to work on MBX in the coming months.  The dangling cross-references 
were "on purpose", but I can see that was not a good idea.

Thanks for the report.

Rob

**Comment by rbeezer** [comment]
FlowPlayer is a JavaScript widget I use to show video files.  I was going to 
suggest you try demos at:

https://flowplayer.org/

but that site will not load for me.  And it is odd that the links you provide 
begin with "file://".  Maybe FlowPlayer is dead and I need to find a replacement 
widget?

Can you try that URL all the same?

**Comment by kcrisman** [comment]
URL works, though slow.  Probably it's assuming that I have these css and js locally?

**Comment by rbeezer** [comment]
Intentional errors have been moved out of the sample document via f3d19730.

All errors are now real.  Some missing strings are reported for HTML output creation, those are genuine.  LaTeX output is created cleanly.

The FlowPlayer widget is working perfectly for me.  More could be done with this feature, but I do not think anything major is particularly broken.

Thanks for making this a ticket so that it got addressed.

Rob
