### ISSUE TITLE
Proofs could use cases

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#203]
A proof often has a case-by-case structure.

Default would be "Case 1", "Case 2", etc.  These could be integrated into the xref, xml:id, numbering schemes, have titles, and so on.

For an "iff" proof maybe 

```xml
<case direction="forward|backward">
```

could draw nice implication arrows with Unicode characters.

**Comment by rbeezer** [comment]
Partial progess - you can mark cases of a prrof as being
```
direction="forward|backward"
```
for an "iff" statement.  No `xml:id` or other goodies yet.

**Comment by rbeezer** [comment]
General cases could have a `title` and earn a number.  The word "Case" should be localized.

Cross-references could be smart - just a serial number within the proof, but fully-qualified (with a colon?) across the proof boundary.

**Comment by oscarlevin** [comment]
I would prefer at least the option to have completely customized title text.  "Inductive case:"  rather than "Case 2 (inductive case)"

See here: https://groups.google.com/d/msg/mathbook-xml-support/fPKEKzwJAHU/-i72KjqcAgAJ

**Comment by rbeezer** [comment]
I decided that numbering options might become a rathole we did not want to go into.  So just implication arrows and/or a title.  More info at link just previous.  I think we are done here.

Changes at  531cafb9
