### ISSUE TITLE
Various minor points to possibly address in author guide

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#210]
Dumb points:
* I think that going straight from the philosophy to the fairly technical formatting section is a mistake.  At the very least, there should be a warning to skip ahead if you aren't ready to start typing yet - and, better, a whole (short) section telling what source is, what kind of outputs one might like, recommending where to get information on command-line on all relevant platforms, etc.
* LaTeX is not (just) a markup language.  Just sayin'.
* Apparently you can use OpenOffice, StarOffice, AbiWord, or other programs to create your documents, since you only list four not to use...
* You should probably not put command-line editors first, or at least point out that these editors vary by platform and in interface.  At least, you should do this if you are actually trying to get people who are used to using word processors to create materials.
* Links should be included to as many preferred options' websites as possible.
* Links to a few places showing *how* to configure editors?  I sheepishly - or proudly? - admit that I type every. single. character. in my source...
* This will be completely mystifying to command-line newbies:

  > At a command prompt in your terminal or console adjust the pathnames for the two files and execute:
* In (current) section 2.4 Extending.. you have `@xml:id` - what is the at symbol for?  Also, that explanation should go after the example, otherwise it's confusing to the reader.

Feel free to ignore or not as you wish.

**Comment by rbeezer** [comment]
Thanks very much Karl.  I've incorprated a lot of this.  See repo in a while (days?).  Some comments:

  *  I do not want to write too much about other projects, and not maintain links.  So for example, I don't intend the documentation to list too much about editors.
  * That said, appendices with helpful editor hints is a great idea.  I'll do the same for `git`.
  * I also don't plan on explaining how to use a shell.  Yes, I'm limiting the audience some, but that is the right place to be now, I think.  Documentation *will* help grow the audience, but it won't be for everybody immediately.  Only so much time in the day.  :-(

Thanks again - keep 'em coming.

Rob
