### ISSUE TITLE
End of line characters

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#211]
Often when I edit a file in the repo, then check with `git diff`, my text editor has automatically added a newline character to the last line of the file which was previously not there. I know that when this shows up in Rob's review of a future pull request, it will raise questions. So I find a way to manually remove that character so that my edits are minimal.

However I would suggest that these newline characters are actually appropriate, and that there could be a single commit that adds one to each file in the repo not currently having one. And since the lack of such a character is so prevalent, that we all investigate our text editors to see if they can be included by default from now on (for the sake of any future files added to the repo).

Here are some threads about why to include newline characters at the end of a file:
http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
http://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

**Comment by davidfarmer** [comment]
I like this.  I had a bug in SL2X which took me a long time to track
down.  It was caused by \input files which lacked a newline at the
end of the file.

**Comment by Alex-Jordan** [comment]
Here's another reason to do this. I just ran `cat` on the README for the DTD, and I get:

```
syst203m4138:dtd alex.jordan$ cat README.md 
# MathBook XML Document Type Definition

This can be employed in the following manner.  Look inside `mathbook.dtd` for more information

`xmllint --xinclude --postvalid --noout --dtdvalid schema/dtd/mathbook.dtd examples/sample-book/sample-book.xml 2> dtdinfo.txt`syst203m4138:dtd alex.jordan$ 
```
Note the "syst203m4138:dtd alex.jordan$" at the end of the last line. Of course this is my terminal prompt, but because this README file has no newline at the end of its last line, the last line melds into the prompt.

Anything that concatenates multiple files will bleed a last line into a first line if there is no ending end of line character. Not sure where that would come up in MBX, but someday it might.

**Comment by rbeezer** [comment]
Yes, I'll try to be more conscientious about this.  Though I don't plan to 
automate any sort of massive fix.

Feel free to simply add names of "problem" files (or collections) here and I'll 
drop in later to fix a few in a batch.

**Comment by rbeezer** [comment]
Moot due to PR #272.  Thanks, Alex.
