### ISSUE TITLE
Programming code in index

### ISSUE THREAD

**Issue by rplantz** [rbeezer/mathbook#212]
When I write,

    <c>STDOUT_FILENO</c><index><main><c>STDOUT_FILENO</c></main></index> is defined in the    system header file, <c>unistd.h.</c>

the DTD gives me,

    ./02-data-storage.xml:2152: element main: validity error : Element main was declared #PCDATA but contains non text nodes

and `STDOUT_FILENO` does not show up in the PDF index.

The "fix" is to write,

    <c>STDOUT_FILENO</c><index><main>STDOUT<underscore />FILENO</main></index> is defined in the system header file, <c>unistd.h.</c>

then 'STDOUT_FILENO' is in the index, but it is not in monofont.

I can live with this, but since `STDOUT_FILENO` is actually computer code (a constant), it would be better if I can tag it as such in the index.

**Comment by rbeezer** [comment]
Dear Bob,

Thanks.  This is perhaps a result of changes made to allow structured and unstructured content in the index element.

DTD may be an oversight.  And I think your authoring is spot-on.

Short answer:  don't attempt workaround yet and keep reporting in.  Wednesday might be a good time for me to clean this up, especially if you bumped this issue late Tuesday.  :-)

Rob

**Comment by rbeezer** [comment]
DTD has been updated at 16a70669

This was slap-dash stuff that never got another hard look when I was cleaning up the DTD.

It looks like the actual processing should put the right thing into the index (using a monospace font in this case), but hopefully there is no "moving" argument that needs to be `\protect`'ed or something like that.

Thanks for the report.  Holler if this needs more work.

Rob
