### ISSUE TITLE
Exercises as peer to subsection

### ISSUE THREAD

**Issue by rplantz** [rbeezer/mathbook#215]
It would be nice to have <exercises> as a peer to <subsection> so that "Exercises c.s.n" could be created in Chapter 'c', Section 's', with n = 1, 2, ... within each c.s.

**Comment by davidfarmer** [comment]
Do you mean

Chapter 3

Section 3.1

Subsection 3.1.1

Subsection 3.1.2

Exercises 3.1.3

Subsection 3.1.4

Section 3.2


Can you put an exercise in a subsection?  Can there be definitions
and theorems inside Exercises 3.1.3?  Do you number an exercise
in the same scheme as a definition or theorem, wherever it happens
to appear?

In other words, is "Exersises" exactly like "Subsection", with the
only difference being that one word when you display the title?

**Comment by rplantz** [comment]
David, that's very close. Ideally, I would like something like
Chapter 3
Section 3.1
Subsection 3.1.1
Exercises 3.1.1
Subsection 3.1.2
Exercises 3.1
Subsection 3.1.4
Section 3.2

Scanning through my textbooks, the placement of exercises is all over the place. In my current book (written with LaTeX) I have all exercises at the end of each chapter, with reference back to the appropriate section.

My sense is that section-level granularity is a good compromise, giving something like
Chapter 3
Section 3.1
Subsection 3.1.1
Subsection 3.1.2
Subsection 3.1.4
Exercises 3.1  (or Exercises 3.1.5)
Section 3.2

Looking at xmllint's message, I see that a section can be organized as a leaf node with lots of different content --- (title , index* , author* , ((p | md | mdn | ul | ol | dl | blockquote | pre | sidebyside | sage | figure | table | listing | poem | program | image | tabular | paragraphs | theorem | corollary | lemma | algorithm | proposition | claim | fact | definition | conjecture | axiom | principle | remark | example | exercise | contributors | list-of | solution-list | notation-list | todo)* --- or as a structured node --- (introduction? , (subsection | exercises | references)+ , conclusion?)).

Rob has suggested that I could do it as a structured node with (introduction exercises), or if there are subsections, (introduction subsection subsection exercises). This seems quite good.

I wonder, though, if there should be a <body> tag so that a section could be organized (introduction? , (body | subsection | exercises | references)+ , conclusion?)). The terminology might be a little more intuitive.
