### ISSUE TITLE
DTD needs xmlns:xi attribute in structure elements

### ISSUE THREAD

**Issue by rplantz** [rbeezer/mathbook#218]
I get:

    intro-co-rpi.xml:15: element mathbook: validity error : No declaration for attribute xmlns:xi of element mathbook
    ./01-introduction.xml:3: element chapter: validity error : No declaration for attribute xmlns:xi of element chapter

in my book. The same occurs for the sample book.

**Comment by rbeezer** [comment]
Thanks, Bob.  I'm aware of this one, and I think I had trouble getting it right 
for some reason.  I'll be in there today and see what I can do.

Rob

**Comment by rbeezer** [comment]
This should be covered at  805ed69b

But there may need to be more, so just pass along the involved elements.
