### ISSUE TITLE
analytic in DTD

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#219]
As mentioned here: https://groups.google.com/forum/#!topic/mathbook-xml-support/coVhUYKa91s

The DTD is missing the elements for running analytics:
`analytics`
`statcounter`
`project`
`security`
`google`
`tracking`

**Comment by kcrisman** [comment]
The DTD is also missing `search`, which seems sufficiently relevant to add it here.

**Comment by Alex-Jordan** [comment]
All this stuff is in the schema now.
