### ISSUE TITLE
Add example to article of using lt in Sage code

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#23]
There are several examples of `<c>&lt;</c>` for obvious reasons.  I think this is necessary in Sage cell code too.

**Comment by rbeezer** [comment]
Yes, it is necessary, such as in the constraints of a linear programminng 
example I did last week.  I'll add such a thing in a Sage example.

**Comment by kcrisman** [comment]
I feel like maybe you did this in one of the updates?

**Comment by rbeezer** [comment]
It is now there explicitly.  Thanks.
