### ISSUE TITLE
Width parameter units in LaTeX output

### ISSUE THREAD

**Issue by avangron** [rbeezer/mathbook#231]
Latex output doesn't produce correct units when specified in percentages. (At least for png images.)
   `<image width="50%" source="img.png"></image>`
Results in the latex 
  `\includegraphics[width=50%pt,]{img.png}`

[https://groups.google.com/d/msg/mathbook-xml-support/0m-IFs6a7K4/8Rl4s7BXCgAJ](url)

A.

**Comment by rbeezer** [comment]
Thanks very much, Anthony.  I implemented a quick fix at  aee0bd5e

One shortcoming - a non-integral percentage will fail.  I plan to seriously clean up a lot the image sizing code this summer, so this will done properly soon.  Thanks for the help.
