### ISSUE TITLE
url should be allowed (in DTD) to have...

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#232]
url should be allowed (in DTD) to have:
- `<c>` children
- special character children: ampersand, dollar, underscore, hash, percent

**Comment by rbeezer** [comment]
Thanks, Alex.  I've erred a bit in the other direction.  Lots of markup is now allowed, but also am now allowing nesting `url` and a `url` can contain an `xref`.  Those situations are fictions.

Eventually, I'll refine the really basic stuff like this and get it squared away.

Fix at  1c0413be
