### ISSUE TITLE
First line indent of raw text clips remaining lines

### ISSUE THREAD

**Issue by rplantz** [rbeezer/mathbook#236]
If the first line of line-broken raw text is indented, either with a tab or with spaces, the first few characters of all remaining lines are lost. I've created an example, but github won't allow me to attach a compressed file, so I'll attach it to my response on Google: [https://groups.google.com/forum/?hl=en#!topic/mathbook-xml-support/-zfesDBuTbI](url)

**Comment by rbeezer** [comment]
Two very similar routines, and not always calling the right one.

Consolidated at b00f6618

**Thanks** for the very careful report.  Be **very** careful to always use tabs or always use spaces.  Since we do not ever know how wide a tab is, there is no way to uniformly strip notation.
