### ISSUE TITLE
Implement an "abbr" tag

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#239]
Write as-is into HTML, and help LaTeX with periods and spaces.  Motivated by

https://groups.google.com/d/topic/mathbook-xml-support/coEowjfVDUk/discussion

(Add to DTD.)

**Comment by Alex-Jordan** [comment]
Note: use this to implement `<vs />` and various other things. See https://groups.google.com/d/msg/mathbook-xml-support/coEowjfVDUk/a8iEIk_9DQAJ

**Comment by davidfarmer** [comment]
The special treatment of abbreviations seems like a temporary measure.  If we had an "s" sentence
tag wrapper around sentences, then you would know that the "." inside the sentence should not
get extra space after it.

**Comment by rbeezer** [comment]
I'm not so sure about the temporary nature.  A web browser might do something with text wrapped in `abbr`.  With a sentence tag, we still might not know when  `MBA` or `et al.` was an abbreviation, and I think we would have a hard time deciding exactly where it started.

I am not convinced that an MBX `abbr` will allow the LaTeX output to properly handle every period, but with `abbr` and a sentence tag, the undecidable special cases might be very limited.

In any event I see `abbr` as something you use to get the best possible output (a book), but not for less valuable things (Sage in-class worksheet).  So optional, in a way.  If it is absent, we do our best to infer no bad decisions.

And if I can abstract `abbr` on a per-format basis, then things like `vs.` will become one-shot definitions down in `mathbook-common.xsl`, which is a long-term goal for maintenance and stability.

**Comment by rbeezer** [comment]
Abbreviation, acronyms, and initialisms implemented as `<abbr>`, `<acro>` and `<init>` at 237cd660

See also #263
