### ISSUE TITLE
Document linked Sage cells

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#24]
On a "per-subdivision" basis.  Suggested by kcrisman.

**Comment by kcrisman** [comment]
Actually, apparently this was done in https://github.com/rbeezer/mathbook/commit/bb74d11786fedbfc3850fcb349da12c5a48a23bd - does that sound right, Rob?  E.g.

    +                <p>Sage cells share their results on a per-webpage basis, so if you move to a new chapter, section, or subsection that happens to be on another webpage, your Sage computations are gone and you start fresh.  But maybe you need some results from elsewhere.  As an author, you can make an exact copy of a cell in another location.  As a reader you are suggested to <q>replay</q> the cell.  You have seen the next cell before.  More typically such a cell might define a function or set some values of a variable.</p>
    +

**Comment by rbeezer** [comment]
Exactly.  Thanks.
