### ISSUE TITLE
base64 breaks with special characters

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#243]
`<title>Mt.<nbsp/>Hood Precaclucus</title>`

leads to bad behavior with WeBWorK cells. This line is supposed to end up in the pg:

`## TitleText1(Mt. Hood Precaclucus)`

It's fine in the .pg output file, but the base64 string ends up being unintelligible to the WeBWorK server, and by decoding it, I traced the issue to where the nbsp would be.

Also, the archiving process for the pg and def files ends up creating _two_ copies. One in a root folder named `Mt_Hood_Precaclucus` and another in a root folder named `Mt_Hood_Precaclucus`.

I haven't tested if this is specific to nbsp, or likely an issue with special markup in titles. Also not sure if special markup somewhere else in a webwork would cause similar trouble with the base64.

**Comment by rbeezer** [comment]
The non-breaking space is some Unicode character, likely outside of the list of 
characters the base64 conversion table knows about.

We should just define <nbsp /> to be a "plain" space in WW, or do we already 
have something else ([$NBSP] or such?)?

**Comment by Alex-Jordan** [comment]
The nbsp that is causing trouble is not inside PG code. It's the title for
the whole project, which then goes into a comment in the preamble to the
.pg file. So yes, nbsp needs to be handled specially for the base64 prep.
But it's not about [$NBSP], which is something to use inside a PG problem's
PGML environment.

On Fri, Apr 22, 2016 at 10:07 PM, Rob Beezer <notifications@github.com>
wrote:

> The non-breaking space is some Unicode character, likely outside of the
> list of
> characters the base64 conversion table knows about.
>
> We should just define <nbsp /> to be a "plain" space in WW, or do we
> already
> have something else ([$NBSP] or such?)?
>
> On 04/22/2016 09:29 PM, Alex Jordan wrote:
> > |<title>Mt.<nbsp/>Hood Precaclucus</title>|
> >
> > leads to bad behavior with WeBWorK cells. This line is supposed to end
> up in the pg:
> >
> > |## TitleText1(Mt. Hood Precaclucus)|
> >
> > It's fine in the .pg output file, but the base64 string ends up being
> > unintelligible to the WeBWorK server, and by decoding it, I traced the
> issue to
> > where the nbsp would be.
> >
> > Also, the archiving process for the pg and def files ends up creating
> /two/
> > copies. One in a root folder named |Mt_Hood_Precaclucus| and another in
> a root
> > folder named |Mt_Hood_Precaclucus|.
> >
> > I haven't tested if this is specific to nbsp, or likely an issue with
> special
> > markup in titles. Also not sure if special markup somewhere else in a
> webwork
> > would cause similar trouble with the base64.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rbeezer/mathbook/issues/243>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rbeezer/mathbook/issues/243#issuecomment-213666360>
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
When this issue was posted, we only translated into PG in one way. The same PG translation that made a .pg file was used to make the pg that was translated into base64. That is no longer true. Now what happens is when it's going to be encoded in base64, a minimal, compact pg translation is made, and this version does not contain things like the book's title in some OPL metadata tags. So the nbsp is not included. The only characters that are included are either actual descendants of the `webwork` element or they are directly inserted by some hard coding of the XSL. The point is that special characters are not a problem (unless the author has put them into their `webwork` source, which they shouldn't do).

So this issue has fixed itself with the passage of time.
