### ISSUE TITLE
author guide attribute tag looks weird in pdf

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#244]
In the quickstart (current section 2.4) I see `<attribute>xml:id</attribute>` as `@xml:id`.  Maybe that is "correct", but if so it sure will be confusing to a newbie who then sees just plain old `xml:id` in the actual markup in the example itself.

**Comment by rbeezer** [comment]
Dear KDC,

The official version is now at:

http://mathbook.pugetsound.edu/doc/author-guide/mathbook-author-guide.pdf

Off of:

http://mathbook.pugetsound.edu/documentation.html

and says (from the source):

"The <q>at</q> symbol is a way of reminding you that it is an attribute, it is 
not part of what you author."

(I think I put that in at your suggestion!)

Is there a stale version someplace that does not have that?

Rob

**Comment by kcrisman** [comment]
Never mind, I read too fast.
