### ISSUE TITLE
clarify first example with whitespace in paragraph tag

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#245]
You have a screed about whitespace being evil, but then (to the newbie) the first example of a multiline paragraph tag looks like this:

```
<p>This is a longer sentence that is followed by another sentence.
    Two sentences, and a second paragraph to follow.</p>
```

Now, if you try to copy it it's clear this has no extra whitespace (no doubt due to a nice convenient editor) but since it's the first time this appears, you should probably mention it again, so no one is confused when they try writing their own thing.  Especially because the indentation would make it look like this.

**Comment by rbeezer** [comment]
Previous paragraph should have:

"Remember, <em>do not</em> include any newlines (carriage returns, line feeds, 
hard wrap) in the longer lines.  (We have to format things differently so you 
can see exactly what is happening.)"

**Comment by kcrisman** [comment]
Aargh, my eyes just go straight to what looks wrong - sorry for wasting both of our time.

**Comment by rbeezer** [comment]
No problem.  Only mild head-scratching.  ;-)

Keep the suggestions coming.
