### ISSUE TITLE
In article, a html section is rendered differently than the latex/pdf

### ISSUE THREAD

**Issue by dqnykamp** [rbeezer/mathbook#247]
For an article, this snippet
<section><title>A section</title></section>
is rendered as
1 A section
in latex and as
Section 1 A section
in html.

**Comment by rbeezer** [comment]
Corrected at cd4c8376, along with a few similar things that needed to change so that titles in HTML matched titles in LaTeX, for articles and for books.

Thanks for the catch, Duanne.
