### ISSUE TITLE
issues in author guide overview

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#249]
> `<paragraphs>` are exceptional. 

But is it plural?  Maybe put the s after the tag? (Later you put it that way, in "Mathematical Results".)

> A subdivision may be unstructured, in which case you fill it with paragraphs

Does that mean `<paragraph>` or `<p>`, or are those aliases for each other?

Also, are there divisions or only subdivisions?

Note that some people call the octothorp(e) the pound sign...

> But first, two features you do not want to miss.

Verb?

> Subdivisions always need titles, you accomplish this with a `<title>` tag first thing. 

This is somewhat colloquial.  Also, it seems (only seems, I think) to conflict with the suggestion that they only can have introduction, subdivisions, and conclusions, since `<title>` is at the same level as those, right?

>  and if you switch to to one of the supported languages,

I don't know that you mention these before - maybe that should be early in the document that there are a number of supported translations (and where to click to look for the current list).

> Note that the dynamic formats (including the Sage Cell) will run Sage “interacts,”

_May_ run, right?

On a side note, there is something weird about the supposedly monospaced font for things like `<definition>` or `<figure>` - there is something where "fl" or "fi" has a different spacking, there is a name for this but it escapes me.

While I'm at it, in "Processing ..."

> The ones that you will use as an author all fave

"fave"?

> So for example, two `<chapter>` cannot go into the same file.

`<chapter>s`.  I would submit a PR for these but I think it's easier for you to do these all at once than for me to monkey around with it (reference to the author guide intended).

> Stringparam (Section 4.4) are an easy way to effect global changes in the presentation of your writing. 

Stringparams?

**Comment by rbeezer** [comment]
On 04/25/2016 06:10 PM, kcrisman wrote:
>     |<paragraphs>| are exceptional.
>
> But is it plural? Maybe put the s after the tag? (Later you put it that way, in
> "Mathematical Results".)
>
>     A subdivision may be unstructured, in which case you fill it with paragraphs
>
> Does that mean |<paragraph>| or |<p>|, or are those aliases for each other?

The DTD says the tag is <paragraphs> and so plain "paragraphs" is the word, 
implemented as "p"  There is no <paragraph> anymore (deprecated).

> Also, are there divisions or only subdivisions?

Splitting hairs here.

> Note that some people call the octothorp(e) the pound sign...

Likely to be handled carefully in Topics.

>     But first, two features you do not want to miss.
>
> Verb?

Added.

>     Subdivisions always need titles, you accomplish this with a |<title>| tag
>     first thing.
>
> This is somewhat colloquial. Also, it seems (only seems, I think) to conflict
> with the suggestion that they only can have introduction, subdivisions, and
> conclusions, since |<title>| is at the same level as those, right?

colloquial is fine in this overview.

>     and if you switch to to one of the supported languages,
>
> I don't know that you mention these before - maybe that should be early in the
> document that there are a number of supported translations (and where to click
> to look for the current list).

For the Topics chapter.  Temporary  xref  dropped here.

>     Note that the dynamic formats (including the Sage Cell) will run Sage
>     “interacts,”
>
> /May/ run, right?

Changed.

> On a side note, there is something weird about the supposedly monospaced font
> for things like |<definition>| or |<figure>| - there is something where "fl" or
> "fi" has a different spacking, there is a name for this but it escapes me.

Ligatures?  Likely to be switching the LaTeX font, but I should hope there are 
not any ligatures.  In HTML or LaTeX?

> While I'm at it, in "Processing ..."
>
>     The ones that you will use as an author all fave
>
> "fave"?

"have", fixed

>     So for example, two |<chapter>| cannot go into the same file.
>
> |<chapter>s|. I would submit a PR for these but I think it's easier for you to
> do these all at once than for me to monkey around with it (reference to the
> author guide intended).

Fixed by adding "elements"

>     Stringparam (Section 4.4) are an easy way to effect global changes in the
>     presentation of your writing.
>
> Stringparams?

Fixed.

Thanks for the review!

Rob

**Comment by rbeezer** [comment]
Edits at 50116937

**Comment by kcrisman** [comment]
> The DTD says the tag is <paragraphs> and so plain "paragraphs" is the word, implemented as "p" There is no <paragraph> anymore (deprecated).

I think that when I wrote this I didn't know about them.

I did see some ligatures (thanks), I assume in HTML.  I won't be looking tonight.  Thanks for the rest!

**Comment by rbeezer** [comment]
On 06/04/2016 05:55 PM, kcrisman wrote:
> I did see some ligatures (thanks), I assume in HTML. I won't be looking tonight.
> Thanks for the rest!

I found a monospace "figure" and did not see this.  If you see it again, please 
let me know the specific location.  Thanks.
