### ISSUE TITLE
mbx calls locally selected python, requires python2

### ISSUE THREAD

**Issue by leingang** [rbeezer/mathbook#251]
The `mbx` script starts with `#!/usr/bin/env python`, which may be python 2 or 3 depending on the user.  But the script's syntax requires python 2.

    $ /usr/bin/env python --version
    Python 3.4.4
    $ ./mbx -h
    File "./mbx", line 706
    print 'MBX: {}'.format(msg)
                  ^
    SyntaxError: invalid syntax
    $ /usr/bin/python2.7 mbx -h
    usage: mbx [-h] [-v] [-c COMPONENT] [-f FORMAT] [-r XMLID] [-s SERVER]
           [-i DATA_DIR] [-o OUT] [-d DIR]
           xml_file
    
    MathBook XML utility script
    ...

`2to3` provides a patch which seems to make the script run in both 2 and 3.

**Comment by rbeezer** [comment]
Script is working with Python 2.7 or Python 3, so this is now moot.  Thanks, Matthew.  See #252.
