### ISSUE TITLE
Listings won't span multiple PDF pages

### ISSUE THREAD

**Issue by rplantz** [rbeezer/mathbook#258]
Programs (program tag) within a listing should span multiple pages in PDF. Now they are cut off if the program goes beyond bottom of page. There should also be a way to turn borders off/on.

**Comment by rbeezer** [comment]
Now I am confused, since I don't know what a "code listing" is.

Does a "program" not span several pages?  I understood your original post to 
suggest the problem only surfaced when you wrapped a "program" in a "listing".

Rob

**Comment by rplantz** [comment]
Oops. I should have said "program." I was using programmer jargon instead
of MBX-ese.

I'll edit the github.

--Bob

**Comment by rbeezer** [comment]
`listing` is a no longer implemented as a floating environment in LaTeX, so a `program` should be free to span several pages.

At a8e1f4d4
