### ISSUE TITLE
hidden knowl content not hidden

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#267]
I was getting ready to put together a minimal example when I saw that it occurs in the
next-to-last paragraph here:

http://mathbook.pugetsound.edu/gfa/html/friends.html

The very long link text is not supposed to appear.

**Comment by rbeezer** [comment]
Dear David,

That was an artifact of me using a "list" element that had absolutely zero 
implementation, in the run-up to the workshop.  My apologies for the confusion.

I've properly implemented "list" and updated the online version of GFA.

Also, I worked on my website script, so it pulls both from MBX (e.g., for 
updates to lists) and it also pulls from GFA (actual content).  Then the PDF and 
HTML get built and rsync'ed to the website.  So all four public components (MBX 
repo, GFA repo/source, GFA PDF, GFA HTML) should be syncronized whenever I run 
the script (eventually a nightly cron job?).

Sample article and sample book are next up for syncronization.  Sorry for all 
teh uncertaintity this has been causing.

Rob

**Comment by davidfarmer** [comment]
I saw this problem originally in a knowlified example in Active Calculus.
I'll pull from master and check if it fixed that case, too.

**Comment by rbeezer** [comment]
This is no longer an error, though perhaps the text of the knowl link is not entirely what I wanted.  `xref` is going to get a refactor, so I'll leave that for later.  I'd be surprised if this was still about in Active Calculus (but if so, would love to hear).
