### ISSUE TITLE
Allow collapsible subsection stuff on the left

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#27]
The little mini-toc on the left of a typical MBX output is not collapsible by chapter.  Likewise, it is not "uncollapsible" in the sense that if one clicks on a subsection with sub subsections, that one would want to see a list of the subsubsections on the left.

**Comment by davidfarmer** [comment]
My guess is that we would first need a decision on issue #26, and then we would need someone
to do it, or some money to pay someone to do it.

**Comment by rbeezer** [comment]
Right.  A "collapsible tree widget" on the left might be a nice option.

The current mini-toc will go two-deep from your top level (eg parts + chapters). 
  There is a lot of complicated javascript to make all the scrolling behave, and 
it took money to have somebody (Michael DuBois) implement it all for us. 
Unlikely to get any attention until some grant support comes through.

On the plus side, there is good logic in the XSL to support something else and 
if it were to exist, it would require just setting a switch by an author.  All 
presentation.

Rob

**Comment by rbeezer** [comment]
This looks a lot like #44.

**Comment by rbeezer** [comment]
I'm closing this as the duplicate, but will comment on #44
