### ISSUE TITLE
List of outcomes and/or objectives at start of subdivision

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#271]
Some discussion at:

https://groups.google.com/d/topic/mathbook-xml-support/X1dLnVC_-WY/discussion

The `xml:id/xref` mechanism might be useful to match text objects with listed outcomes.

**Comment by rbeezer** [comment]
The "Motivating Questions" in the [Active Calculus](http://faculty.gvsu.edu/boelkinm/Home/Active_Calculus.html) series are an example.  No one trm seems to describe these, even if they seem to have the same flavor/purpose.

**Comment by davidfarmer** [comment]
I am in the midst of trying to figure out, so far not too
successfully, how to mark up that particular item in Active Calc.

Any thoughts about:

"paragraphs"

"introduction" to the section, with a title on that introduction
(probably not, because then I can't put a sentence before it)

This is a common thing to do, so I'd rather not do it in a hacked
together way.

**Comment by rbeezer** [comment]
introduction
   title "Motivating Questions"
   p lead-in
   ol
    li
    li
   p lead-out

Haven't looked to see the "sentence before it" problem.  Could that be something 
that moves, or is banned?  I'd like to force "objectives" to go before 
"introduction" in a subdivision?

Will that work for now?  Campus stuff for 1.5 more days.  Let me doodle on ideas 
while at teaching workshop and maybe we can suggest MBX XML in advance and hack 
up XSL quickly.

**Comment by rbeezer** [comment]
OK, I see the sentence.  I'd accomodate an introduction in the "objective"
block.

Put that in the "p" I sent earlier.

**Comment by davidfarmer** [comment]
"objectives" as an optional division before "introduction", or an optional
division within "introduction?  The latter sounds better to me, because
the idea of introduction before the first subsection has held up pretty
robustly since we first came up with that idea.

**Comment by rbeezer** [comment]
Yes, that is a good idea to consider as I doodle this afternoon.

**Comment by rbeezer** [comment]
Initial implementation at  e30713bc

Details on thread referenced above, see also #408
