### ISSUE TITLE
Add examples of all statement-requiring environments to sample article

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#28]
Such as definition.  Wasted 10 minutes trying to get the definition to actually show up!

**Comment by rbeezer** [comment]
Yes, good suggestion.  Noted.

**Comment by rbeezer** [comment]
There is now a complete definition example in the sample article.  Pushing soon.

There is discussion about the possibilities but not an example of each and every one.  It should now be easier to extrapolate.  Buried in Subsection 4.3 of the sample article.
