### ISSUE TITLE
title in colophon

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#280]
> 2) Colophon has no title - I recall seeing in an earlier version that one could
> change it... anyway, I doubt that many people know what a colophon is even if
> they seem them regularly as a copyright info page (sometimes quite lengthy in
> commercial texts).

That is an omission in the DTD, looks like the HTML conversion will employ a
provided title (at least in front).  But note that LaTeX will not use that
title, just drop all that stuff verso of title page.  Mind making an issue?

**Comment by rbeezer** [comment]
Title added to colophon in DTD at 63f315bf

Thnaks!
