### ISSUE TITLE
sample article needs new "list" element

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#282]
The new `<list>` thing isn't in there yet.

**Comment by rbeezer** [comment]
Read slower. ;-)

List 12.3 Colors of the Rainbow.

**Comment by kcrisman** [comment]
> Read slower. ;-)
>
> List 12.3 Colors of the Rainbow.
>
>
>
Well, `<list>` isn't because you gave it an `xml:id`, which is why I
couldn't find it by a search.

**Comment by rbeezer** [comment]
On 05/27/2016 05:07 AM, kcrisman wrote:
>  > Read slower. ;-)
>  >
>  > List 12.3 Colors of the Rainbow.
>  >
>  >
>  >
> Well, `<list>` isn't because you gave it an `xml:id`, which is why I
> couldn't find it by a search.

Hah!  Me either. ;-)

Read slower?  No.  grep better!  This has bit me before.

**Comment by davidfarmer** [comment]
What the sample article needs is a good index!
