### ISSUE TITLE
Can't have hash/pound/sharp character in latex

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#30]
```
! You can't use `macro parameter character #' in horizontal mode.
l.991 ...thon, comments on them are given after '#
                                                  ' signs.%
```
Replacing it by `<c>#</c>` works, but maybe sometimes I don't WANT to make it code.

**Comment by rbeezer** [comment]
Use <hash />.

**Comment by kcrisman** [comment]
I don't understand why this is closed.  I don't understand that answer (just period?), and if you didn't add it to the sample article, then this shouldn't be closed.  (In my humble opinion!)

**Comment by davidfarmer** [comment]
I noticed that in some of my postings, the tags I was typing did not show up: the system
was too clever and did not show them literally.  I am guessing that Rob tried to tell you what to
write, and he needs to tell you again, leaving a space around the < and > of the tag.

**Comment by kcrisman** [comment]
Or you could put them in backticks. `<foo>`

**Comment by rbeezer** [comment]
Ooops.  langle hash slash rangle, what is known as an "empty" tag, with hash inside.

For me and everybody else, use triple back-ticks in the web interface to GitHub 
to protect XML syntax.

Thanks, David and Sorry, KDC.

Rob

**Comment by kcrisman** [comment]
Like so? `<# />`  Would that work for any given character?

**Comment by rbeezer** [comment]
Sorry: `<hash />`

**Comment by kcrisman** [comment]
Oh, that is not at all what I was expecting!  Is that a MBX-specific thing?

**Comment by rbeezer** [comment]
As you discovered, LaTeX wants the hash for two purposes, HTML does not care so 
much.

To effect both outputs, MBX needs to know what you really want.  Hence, an element.

Rob
