### ISSUE TITLE
sidebyside vs svg

### ISSUE THREAD

**Issue by jirilebl** [rbeezer/mathbook#301]
It appears that (at least in the html output)

```
<sidebyside>
  <image source="foo" />
  <image source="bar" />
</sidebyside>

```
Does not work when I have foo.svg and bar.svg ... if I also have .png variants of those and do

```
<sidebyside>
  <image source="foo.png" />
  <image source="bar.png" />
</sidebyside>

```
It works as expected.

**Comment by rbeezer** [comment]
Big push this week to refactor side-by-side, so will likely pick this one up along the way.

**Comment by rbeezer** [comment]
Examples like this now in the sample article and behaving as expected.  At 36c802c0

Thanks for the report.
