### ISSUE TITLE
index seealso

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#304]
We have see but not seealso, which I feel like is something I saw (!) an awful lot in years of yore, though I haven't looked recently.

**Comment by rbeezer** [comment]
`see` and `seealso` are now both fully implemented on both HTML and LaTeX conversions.  See announcement on Google Group, or examples in sample article.

LaTeX: bccc547e
HTML: 4dfdce2c

**Comment by kcrisman** [comment]
Awesome!

**Comment by kcrisman** [comment]
See followup at #481
