### ISSUE TITLE
Allow structured main titles

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#309]
Use `line` to specify breaks on a main title, for example, in use on a title page.

**Comment by rbeezer** [comment]
Work to accomplish this is at ff400f681e6724dc004b18dcac56973febf9a51a where a code comment indicates which titles:

* Books:    title, subtitle, titles of parts, titles of chapters
* Articles: title, subtitle, titles of sections

This needs to be added to the schema, and perhaps we should explicitly kill `title/line` when not matching the above situations, so the (new) default `line` template is not invoked.

**Comment by rbeezer** [comment]
Now in the schema (82008cc4424b1a1059367d4fdb77b8eafd1d115d) and added in titles of sections in books (f138ebb9f903b39d104e00a866ab8fa9c5dd6f35).

**Comment by kcrisman** [comment]
Useful to know!  Do you think this is something *recommended* for longish titles?

**Comment by rbeezer** [comment]
If you don't like hyphens in your titles (especially on a title page!) then this 
is the fine-tuning remedy.  Not much effect now for HTML output.

**Comment by kcrisman** [comment]
Okay, I added #1059 for that.
