### ISSUE TITLE
Author biographies for multi-author books

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#314]
I've got two issues with the way the LaTeX is produced for author biographies on a multi-author book.

1. The titles from the MBX are ignored, which means that if you have one biography called "About William T. Trotter" and another one called "About Mitchel T. Keller", you just get them dumped out after the title page one after the other with no indication where one ends and the next begins. Even worse, the last paragraph of the first biography and the first paragraph of the second biography get merged.

2. If the biography/biographies are long (as the ones in our book are), what should be the verso winds up spanning multiple pages. It seems it might make more sense to structure these as \chapter*'s like is done for `<acknowledgement>`. 

I'm willing to take a stab at figuring out some modifications to the XSL to achieve some of these (at least titles and breaking up the biographies), but thought I'd make an issue in case it's something you can see a quick fix for or there are some stylistic objections to more structure to resolve the second item above.

**Comment by rbeezer** [comment]
Yep, not done particularly carefully.

*  Enabling "title" will be easy.
*  A gap between is trivial.

You can have multiple "preface", you can title them whatever you want, you can 
use "paragraphs" to get a lightweight heading for each other.

The "preface" will need to be adjacent to the "real" one (before or after). 
Will that meet your needs?

If you *want* try contributing to the XSL, let me know and I'll send a couple 
suggestions on forming a pull request and maybe the code.  If you have better 
things to do, I can take care of it, should not take me long (famous last words).

Thanks,
Rob

**Comment by mitchkeller** [comment]
I thought about hacking it as an additional preface, since that's what I've done with the Prologue that introduces our cast of characters. That seems like a perfectly reasonable use of multiple prefaces, but moving the biographies out of the designated element and using a preface instead seems like we're losing the structural aspect of things.

Speaking of structural, would it perhaps make sense to move `biography` under `author` instead of having `biography` as a child of `frontmatter`? Then there could be sensible default behavior triggered by the presence of `biography` elements:

- Produce a \chapter* called About the author or About the authors, depending on the number of authors detected.
- Produce a \section* (or something similar) for each biography, titled with the biography title if there is a biography title, and if not, titled "About (author name)", drawing the value of the `personname` that goes with the `author` element from which the `biography` is drawn.

The HTML output right now for multiple biographies is pretty good, so I suspect that the only meaningful change needed there would be to match the titling behavior, making each biography its own HTML page.

I'm realizing this is likely a bigger can of worms than I was going to open originally, so I think I'll defer to your XSL skills rather than send myself down a rabbit hole of learning cool things I shouldn't be learning this summer. If you think an on-list discussion of some of this would be good, let me know, and I'll launch it. 

It seems that at least outputting the biography titles into the LaTeX (which should resolve the lack of a paragraph break between biographies) would be a quick step if the rest sounds like it's going to take more work.

**Comment by rbeezer** [comment]
I was going to suggest you do the Cast this way, so I'm glad you've come to the 
same conclusion.

OK, I'll work up some XSL for the present LaTeX side.  Anytime you see something 
easy - consult me for advice first and then you can have it.  I can see that 
you'd love having XSL in your toolkit.

Let's discuss moving bios into authors on the list.  That'll be a change (I 
think we can deprecate gracefully).

I'm uncertain if the *number* of authors should be the trigger for another 
frontmatter section.  I'll suggest now that maybe we have

latex.biography = "colophon|preface"

(or similar) to handle where it goes?  We get the structure right in MBX, then 
the original request becomes a question of processing (since HTML seems to work 
just fine in all cases).

**Comment by mitchkeller** [comment]
I like the latex.biography option suggested. I wasn't enamored with the idea of forcibly putting things as a preface, since some (many?) may want a short item that works well as part of the back of the title page, while others may like something longer. (I doubt I would have written the biographies we have in our book if I'd been tasked with it, but I kind of like the way Tom wrote them and think they fit well with the rest of the book.)

Launching discussion on list momentarily.

**Comment by rbeezer** [comment]
Deficiencies with LaTeX output are fixed at 8ef4dc20

I'm going to close this for the bugs and open a new issue for the new optional behavior
