### ISSUE TITLE
Footnotes broken in HTML

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#315]
Knowls are being created for footnotes, but the text for the footnote is being put into the body as its own paragraph rather than into the knowl. (See the footnote in Section 2 of the sample article for an example of this.)

**Comment by rbeezer** [comment]
Should be fixed now at bb2ff431.  Thanks very much for the report.  Keep 'em coming.  (Bugs first for me - I'll get to your other things in a bit.)

@davidfarmer It would appear that if a hidden knowl clickable appears at span-level (footnote here), and you embed the content right afterwards (span-level) then the embedded content cannot be block-level (previously a p here).   The content seems to bleed out of its enclosure (span-level), before even being used, which seems to be totally understandable.  

Not a problem for current conversion, just wanted to see if this was expected or alert you if it needs work.  Not sure if I'll need it or not as I work through more of this refactoring.

**Comment by davidfarmer** [comment]
> @davidfarmer It would appear that if a hidden knowl clickable appears at span-level
> (footnote here), and you embed the content right afterwards (span-level) then the
> embedded content cannot be block-level (previously a p here). The content seems to
> bleed out of its enclosure (span-level), before even being used, which seems to be
> totally understandable.

I recall that our first attempts to hide knowl content in the page
had problems because we tried to make something block level and
also invisible.  That fact that it was a block affected how other
things appear, even though it wasn't visible.

Just let me know if there turns out to be an issue.

**Comment by rbeezer** [comment]
Exactly - that's why my first solutions failed.  We also had to manufacture an extra div to use in some cases, so a hidden knowl had something to open against, we use a `hidden-knowl-wrapper` class for that.

If I see a place where the problem might arise again, I'll try to tackle it sooner rather than later.
