### ISSUE TITLE
Notation references undefined in LaTeX output

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#323]
https://groups.google.com/d/topic/mathbook-xml-support/LlH6TIQkE7o/discussion

**Comment by rbeezer** [comment]
Skipping over the template for notation that drops a link behind.  Left a few notes where I might subsequently make the same mistake in later refactoring.  Checking HTML `duplicate` scheme now.

Fixed at c2fbf05e

@kcrisman - thanks for the report.

**Comment by kcrisman** [comment]
Yourrrrr'e welcome!
