### ISSUE TITLE
Refactor side-by-side

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#327]
As it says.

See #301 and #256

**Comment by rbeezer** [comment]
Just a reminder of things to add as candidates for contents of side-by-side panels:  `poem`, `list`, `pre`, `listing`, `console`, `program`.

Some have titles, some have captions, some are atomic.

**Comment by mitchkeller** [comment]
* #301 is still a problem
* `<sidebyside><pre>` just outputs [pre] (both HTML and LaTeX) in that panel and ignores the content.
* latex-image-code inside sidebyside seems very, very broken. (I can’t actually get the LaTeX image code written into the .tex file, and the output for HTML is equally baffled.)

**Comment by rbeezer** [comment]
#256 is still outstanding, and I'll do `listing`, `console` and `program` when requested.  But mostly this is complete at 05764a8a and subsequent commits up until 7f3db152
