### ISSUE TITLE
deleted element

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#331]
Markup for `<deleted>deleted text</deleted>`. Possible implementations include strikeout text. See https://groups.google.com/d/msg/mathbook-xml-support/fvjRVYo3YXo/NaUMVEeeBgAJ

May go along with highlighted text.

**Comment by rbeezer** [comment]
A good discussion with lots of CSS suggestions:

http://html5doctor.com/ins-del-s/

**Comment by rbeezer** [comment]
Implemented at  03cae565  (`insert`, `delete`, `stale`).

See thread above for lots of discussion, explanation.  Please put requests for extensions onto a new issue.

One more CSS link: http://stackoverflow.com/questions/2539207/
