### ISSUE TITLE
sidebyside knowl css panel reconfiguration

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#335]
Clicking the knowl in this paragraph:

http://mathbook.pugetsound.edu/examples/sample-article/html/section-side-by-side.html#p-475

causes some reconfiguration of the encompassing sidebyside so that the second panel moves below the knowl. (Observed in Firefox at least.)

**Comment by davidfarmer** [comment]
The way a knowl decides where to appear is simple: find the nearest
enclosing block element (in this case, the "p" containing that
text), and then go immediately after it.  That places the knowl inside the
div.sidebyside, which looks bad because that puts it between the
text and the image, and the pre-set sizes do not let everything fit.

I can look into having the knowl code look further out to see if there
is an enclosing block level element which is "better" than the first
one it found.  It would be good to know of possible other cases before
I start fiddling around with that.

I submitted an issue in the knowls repository.

**Comment by Alex-Jordan** [comment]
Take a look here to see the behavior of a knowl inside a table.
http://spot.pcc.edu/~ajordan/MTH253Summer2016/section-calendar.html

It appears following below the tr. I kind of like this behavior, rather
than the know appearing in the cell (too narrow) or after the table
(possibly off screen).

Something to consider if you consider any changes.

On Wed, Jul 13, 2016 at 10:26 AM, davidfarmer <notifications@github.com>
wrote:

>
> The way a knowl decides where to appear is simple: find the nearest
> enclosing block element (in this case, the "p" containing that
> text), and then go immediately after it. That places the knowl inside the
> div.sidebyside, which looks bad because that puts it between the
> text and the image, and the pre-set sizes do not let everything fit.
>
> I can look into having the knowl code look further out to see if there
> is an enclosing block level element which is "better" than the first
> one it found. It would be good to know of possible other cases before
> I start fiddling around with that.
>
> I submitted an issue in the knowls repository.
>
>
> On Wed, 13 Jul 2016, Alex Jordan wrote:
>
> >
> > Clicking the knowl in this paragraph:
> >
> >
> http://mathbook.pugetsound.edu/examples/sample-article/html/section-side-by-side.html#p-475
> >
> > causes some reconfiguration of the encompassing sidebyside so that the
> second panel moves below the
> > knowl. (Observed in Firefox at least.)
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the
> > thread.[AAM6LLAD2zG-iTRKBucsAJ7ELrBvhu2Hks5qVRt3gaJpZM4JLo9I.gif]
> >
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/rbeezer/mathbook/issues/335#issuecomment-232426808>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEg3ACpvpMPfL3_ONNYyzrUK8X4ktMoVks5qVR-pgaJpZM4JLo9I>
> .
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by davidfarmer** [comment]
Yes, I won't break that table behavior.

In the context of my previous comment, knowls don't consider
"td" to be block level, but "tr" is.  Tables and lists will
always have to be handled specially.

**Comment by rbeezer** [comment]
Side-by-side has been totally redone, so you may want to check if this needs updating.

**Comment by rbeezer** [comment]
And redone, yet again.  Can this be closed?

**Comment by davidfarmer** [comment]
In the sample article I clicked on a knowl in a paragraph in a SBS and  knowl
in a list item in a SBS, and both seemed fine.

I suggest closing.  It will be a separate issue (because the markup is different)
if a similar problem still exists.

**Comment by rbeezer** [comment]
Thanks for checking!
