### ISSUE TITLE
embedding <dl> within an <ol>

### ISSUE THREAD

**Issue by byoshiwara** [rbeezer/mathbook#336]
When embedding a dl description list with titles "Step 1", "Step 2", etc., within a ol, the items in the dl are numbered as items in the ol:

<ol label="*a*"> 
     <li> 
         <p>Follow the steps to solve by completing the square: <m>x^2 − 1 = 
3x</m>.<dl> 
             <li><title>Step 1: </title> 
                 <p>Write the equation with the constant on the right.</p> 
             </li> 
             <li> 
                 <title>Step 2: </title> 
                 <p>etc...</p> 
             </li> 
         </dl></p> 
     </li> 
     <li><p>Next task, etc...</p></li> 
</ol> 

gives, for example, "b. Step 1:" and "c. Step 2:"

**Comment by rbeezer** [comment]
Sorry, Bruce, I didn't understand this when I labeled it an enhancement.  You can't put a `dl` into a list item of some other list.  In other words, a `dl` needs to be a "top-level" list.  And an `ol` would never have a `title`.


See if the following is the right markup for your example,

```
<p>Follow the steps to solve by completing the square: <m>x^2 − 1 = 3x</m>.
<dl>
  <li>
     <title>Step 1</title>
     <p>Write the equation with the constant on the right.</p>
  </li>
  <li>
     <title>Step 2</title>
     <p>Blah.</p>
  </li>
  <li>
     <title>Step 3</title>
     <p>Blah, blah.</p>
  </li>
</dl></p>
```

**Comment by rbeezer** [comment]
"dl" is a "description list" (not a "definition list" or "defined terms list"). 
So its use can be broader than definitions (witness FAQs in the Authors and 
Publisher's Guides, which are questions and answers).

Certainly terms and definitions is a major/primary use case, so maybe we need an 
indicator for that case, should we wish to mine it for a glossary or index.

That all said, I find the "Step" of this example unnecessary.  A plain old 
ordered list seems the right thing to do.

Perform the following steps: ...
