### ISSUE TITLE
get css for booktitle working

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#338]
(or worktitle or whatever replaces it, see #332)

**Comment by davidfarmer** [comment]
Please check if what I did is adequate.

**Comment by kcrisman** [comment]
Seem fine, thanks for the quick response!  But ... *where* is this css?  I don't see any new commits, so it must be located on some server that is dynamically updated by @davidfarmer 😄 but I wonder when those things will make it back into this repo?  If @rbeezer is doing it that way though then I guess you can close this.

**Comment by rbeezer** [comment]
MBX is the XML specification.

The conversion to AIM's HTML/CSS is a demonstration of MBX.

The HTML/CSS spec is an AIM project under David Farmer.  (Just like LaTeX is not 
in MBX repo.)

**Comment by rbeezer** [comment]
Can we do "oblique"?  Or should LaTeX switch to italic?

Which is *right*?  I'd just like them to be consistent.

**Comment by davidfarmer** [comment]
Rob,

The CSS has "oblique" currently, because that is what you had in some
old CSS that was quoted on this thread.  (I had italic at first,
but then switched.)

Probably it is bad to have too many things italic, and the
title of a book does not need as much emphasis as something you
*really* want to emphasize.

David

**Comment by kcrisman** [comment]
> The HTML/CSS spec is an AIM project under David Farmer.  (Just like LaTeX is not in MBX repo.)

I thought you might say something like that ... but then again, my web pages work just fine without me installing anything from David, whereas if I didn't have LaTeX installed I couldn't compile the results of the tex stylesheet.  It's certainly not evident to a "typical" (think post-initial period) user that the css is liable to change at any moment due to the whims of @davidfarmer 😃 though luckily I trust him more than myself on most design decisions. 

More to the point, it would be nice to have at least one "basic" boxed css styles - perhaps very minimal but with a template for what to change - for users to view.    Perhaps there is such a template, but I don't think the current css files in the repo are that.

**Comment by davidfarmer** [comment]
There is nothing secret about the CSS: it is generated from the SCSS
in this repository:

https://github.com/BooksHTML/mathbook-assets

In addition, there is a mathbook-add-on.css hosted on the AIM website,
where I add new css as needed.  For example, .booktitle is styled
from there.  Eventually the add-on will be incorporated into the
main file.

Regards,

David

**Comment by kcrisman** [comment]
Thanks, David.   Again, as long as things "just work" obviously it doesn't really matter, but in the long run it surprises me a bit that one has this dependency that isn't really stated - or perhaps it now is but I haven't read all the documentation recently :) anyway, I should reiterate that the actual issue here is solved from my point of view, modulo this dependency question.  I'll close this but obviously Rob can reopen if need be.

**Comment by rbeezer** [comment]
Pun observed.  ;-)

Sorry for the noice - I was in a rush and did not take the time to double-check 
what was actually happening at this point.  Thanks for the change.

Rob

**Comment by rbeezer** [comment]
(In reference to CSS hosted at AIM.)

On 07/15/2016 11:22 AM, kcrisman wrote:
> Thanks, David. Again, as long as things "just work" obviously it doesn't really
> matter, but in the long run it surprises me a bit that one has this dependency
> that isn't really stated.

We get MathJax from their CDN.  We get fonts from Google.  We get code syntax 
highlighting from Google.  We get CSS from AIM.  The dependency is an internet 
connection.

Student Project: engineer a good totally offline version and automated process 
for updating key components (eg MathJax).

**Comment by kcrisman** [comment]
> We get MathJax from their CDN. We get fonts from Google.


I didn't realize all that wasn't semi-locally hosted.


> We get code syntax
> highlighting from Google. We get CSS from AIM. The dependency is an
> internet
> connection.


Fair enough.

Let me then keep hijacking by saying that, in this case, because the CSS is
fairly tightly connected to the project (for instance, AIM is a MBX
sponsor), perhaps there should be some sort of big series of signs
somewhere saying

> Need C-S-S?/Batteries included/But pull requests/don't go here,
stupid/Burma-Shave

but I couldn't find it on the main pages.  And instead there is still
https://github.com/rbeezer/mathbook/tree/dev/css which might make one think
that MBX 'natively' supports something that is actually updated along with
all the many changes made on a daily basis :)  E.g. at
https://github.com/rbeezer/mathbook/blob/dev/CONTRIBUTING.md would be a
good place.

**Comment by davidfarmer** [comment]
How about another key example: where do knowls come from?
And what critical software do knowls rely on?

The real point that I think Rob is making: why focus on
one or two out of the ten (or more) critical items that *all* have to
be available and working correctly in order for the HTML version
of your book to function properly?

**Comment by kcrisman** [comment]
> How about another key example: where do knowls come from?
> And what critical software do knowls rely on?
>
>
I don't know.  The knowls are, however, at least inside my directory.



> The real point that I think Rob is making: why focus on
>

I guess that this one seems different to me, at least in the sense of
pretending it's really separate.  What value does the AIM set of CSS have
without this?   Or perhaps in another way, it seems to me that everything
other dependency is in some sense upstream, while the CSS is somehow
downstream.  Anyway, it's not worth arguing over if I'm the only one who
cares, I'm fine dropping it.  But it does seem like it's more like when
they tried to imagine sagenb was "upstream" of Sage, which has since caused
much grief even if it was a good way to speed up development at one point.

**Comment by rbeezer** [comment]
On 07/17/2016 06:15 PM, kcrisman wrote:
> I don't know. The knowls are, however, at least inside my directory.

The Javascript for knowls comes from AIM.  Knew I was forgetting something.

**Comment by rbeezer** [comment]
On 07/16/2016 06:26 PM, kcrisman wrote:
> perhaps there should be some sort of big series of signs
> somewhere saying

See 098a6104
