### ISSUE TITLE
Make DTD clearer for frontmatter items

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#340]
See https://groups.google.com/forum/#!topic/mathbook-xml-support/6UKwlthV_Dk  Same for dedication, etc. in front matter.

**Comment by rbeezer** [comment]
RELAX-NG Schema now says a `preface` can contain

```
Content: title?, idx*, (((p | blockquote | pre | todo | sidebyside)+, attribution*) | contributors)
```

which is basically paragraphs, an attribution, with "illustrations" in a `sidebyside`.  No numbered items here.  But maybe a restricted version of `paragraphs` would be useful as a lightweight division?

See https://github.com/rbeezer/mathbook/issues/639
