### ISSUE TITLE
latex-image-code inside sidebyside

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#347]
latex-image-code inside sidebyside doesn't work correctly. Wrapping in image or both figure and image gets LaTeX with an includegraphics command with empty argument. Wrapping in figure only produces total nonsense. For HTML, just get <img src>.

**Comment by oscarlevin** [comment]
I get these errors too, starting at commit 22df551220db0c6045f42c81732458521e70496e (which makes sense, since that was the latex specific side-by-side refactor commit).

**Comment by rbeezer** [comment]
This should be resolved at  4f60d884

Sorry for the outage, and the time to a fix.
