### ISSUE TITLE
Make Loading of MathJax Extensions Configurable at the Document Level

### ISSUE THREAD

**Issue by jasonu** [rbeezer/mathbook#350]
Per this discussion in the support forum:
[https://groups.google.com/d/msg/mathbook-xml-support/IvU4donIqrg/KWxtyyUwDwAJ](https://groups.google.com/d/msg/mathbook-xml-support/IvU4donIqrg/KWxtyyUwDwAJ)
improve loading of MathJax extensions so that it can be configured on a per-document basis.

**Comment by davidfarmer** [comment]
I think "configured" should be narrowly interpreted to mean
"can add new ones".  If you need a package that is missing,
then it can be added.

If you don't need a particular package, I speculate that the
performance improvement by omitting it is negligible, and so that
feature should have a very low priority.

**Comment by rbeezer** [comment]
My current thought is to have

docinfo/mathjax/extension

You can have several of these - the indicated package is a MathJax extension to 
model some existing LaTeX package of the same name.  You get a \require{} 
MathJax-load on the HTML side and a \usepackage{} (late) in the LaTeX preamble.

If that works for your project, great.  If it doesn't (conflicts, etc) then 
tough.  You can, of course, change the order of the "extension" elements, but 
that is the only recourse you'd have.

All the necessary information is clearly present in the author's source and no 
other project needs to be concerned with a package used this way.  If the 
package is popular, we could make it "permanent" and commit to supporting it, if 
we wanted to.

I do not like the way the  extpfiel  package is currently incorporated (an 
addition for an early adopter), so would be happy to see that change.

**Comment by rbeezer** [comment]
Implemented at  2bfaf064

See post at discussion referenced above, or in sample article.
