### ISSUE TITLE
footnote in a table

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#353]
In LaTeX, using a footnote in a tabular is a classic issue. Should be an easy fix though. The classic, uncomplicated solution is at:

http://tex.stackexchange.com/questions/109467/footnote-in-tabular-environment#answer-109470

**Comment by rbeezer** [comment]
FEWER footnotes, not MORE. ;-)

* Does the indicated solution work for several footnotes in teh same table, and with "regular" LaTeX footnotes in the vicinity?
* Do intra-tabular footnotes behave in HTML (as knowls)?

**Comment by Alex-Jordan** [comment]
I confess that an impish smile ran across my face as I posted this.

Several footnotes in the same table: The footnotemarks iterate appropriately, but the footnote counter needs some attention after the table ends, like:
```
...
\end{tabular}
\addtocounter{footnote}{-1}
\footnotetext{one}
\addtocounter{footnote}{1}
\footnotetext{two}
```

Regular footnotes in the vicinity: check.

Intra-tabular footnotes in HTML: The current example I am looking at makes a knowl appear under the first cell (only) of the row where the footnote is. The knowl would be better if it were as wide as the table row. Not sure why footnote would be the problem here though. I thought knowls appear following the next block level element, which would be the row.

I have no idea about in sidebyside (in LaTeX or HTML)

**Comment by rbeezer** [comment]
I don't need impishness right now.  ;-)

Looks like dropping a `\footnotemark` at location is trivial, then as part of processing `tabular` a `xsl:for-each` could cruise the whole table to drop `\footnotetext` and any counter adjustments together afterward.

**Comment by rbeezer** [comment]
Due to the introduction of `tcolorbox` for styling of LaTeX, and due to hidden knowl content being a `div` in HTML output, we know how to "pop" footnotes at the end of blocks.  So this approach has been taken for `tabular` and `table`.

At 6c36d0649a95bdb8cb2a0a9eb959666620527e50 and 40df7a3d24f6626cad6f4d9d9d54a384e6717b5a.  Needs to go into the schema.

**Comment by rbeezer** [comment]
Should have said: following makes me a little nervous.  At [www.texfaq.org/FAQ-footintab](http://www.texfaq.org/FAQ-footintab) our solution is described and then,

> This is described in Lamport’s book, but it gets messy if there’s more than one footnote.

Which, of course,really does not explain what the problem is.
