### ISSUE TITLE
Back colophon in LaTeX assumes single line

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#357]
As noted in the comments in `mathbook-latex.xsl`, the back colophon is assumed to be a single line. I was thinking it would be nice to put information about the fonts selected and artwork credit for the cover back there, since that's typically where book design would be discussed. Easy for me to hack the LaTeX output right now, but making an official issue (feature request) to move to a parbox or something similar as the existing comment suggests might be good.

**Comment by rbeezer** [comment]
The back colophon has been significantly liberalized.  The schema basically says you can use paragraphs and `sidebyside` with no captions.  In practice, almost anything you put in there (that would normally go in a division) should render.  It should expand to include things like `image` once freed from `sidebyside`.

So if you have schema violations, please post on one of the groups (-dev?).  Anything that is numbered will not be allowed.

I'm accustomed to see **credits** in the front colophon and production choices in the back colophon.  But you could use a `dl` in the back colophon as a way to list credits.
