### ISSUE TITLE
Remarks not incrementing HTML counter

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#358]
`remark` in HTML winds up with the same number as its predecessor. At the moment, I'm staring at a page with three numbered items: Figure 6.15, Remark 6.15, and Remark 6.15.

**Comment by rbeezer** [comment]
Quick fix at  bdc75665

Some explanation at: 
https://groups.google.com/d/topic/mathbook-xml-support/YKVfbnerLyw/discussion
