### ISSUE TITLE
Possible "computation" and "technology" blocks

### ISSUE THREAD

**Issue by ladanielson** [rbeezer/mathbook#359]
As per Rob Beezer:
Can you do me a favor, and pay it forward?  Get on GitHub (rbeezer/mathbook) and 
create an "issue" suggesting "computation" and "technology" blocks as 
"remark-like"?  If it sits in my paper notebook it will get lost and forgotten. ;-)

FYI: College of Idaho is using assemblage for now.  It looked like remarks were numbered, which we didn't need for our "WeBWorK Tips."

**Comment by rbeezer** [comment]
I've added these at 8054108b

Thanks @ladanielson for the suggestion!
