### ISSUE TITLE
alignment in non-display math

### ISSUE THREAD

**Issue by byoshiwara** [rbeezer/mathbook#361]
Is it possible to have aligned equations but not centered as in the display style? An example of how this might look: https://groups.google.com/group/mathbook-xml-support/attach/4b052d5b167a/non-display-aligned-math.jpg?part=0.1&authuser=0&view=1

discussion in Mathbook XML support google group

 https://groups.google.com/d/msg/mathbook-xml-support/9CCAFez29UI/ehZbLQVLAAAJ

**Comment by Alex-Jordan** [comment]
Hi Bruce (4.5 years later),

Is this issue settled? I would use like:
```
<m>\begin{aligned}\frac{1+2}{3\cdot4} \amp= \frac{3}{12} \\ \amp= \frac{1}{4}\end{aligned}</m>
```

In other words, use the `aligned` environment, which is for use when already a math environment. This is sidestepping a PTX approach of breaking the XML up by line by line, but I doubt that inline math would be endowed with that structure anytime soon.

If you have a moment, would you think over this and indicate if this issue can be closed? If so, you could close it (as the person who opened it).

**Comment by byoshiwara** [comment]
Alex--OK, I'll close the issue.
I have been using code as you suggest. I had opened the issue when I learned that \begin{align*} was illegal, and I think I was worried that the <m>\begin{aligned} ... might also become illegal.
