### ISSUE TITLE
Paragraphs in Side-by-Side

### ISSUE THREAD

**Issue by Jahrme** [rbeezer/mathbook#362]
Issues with `<paragraphs>` in `<sidebyside>`,  reported [here](https://groups.google.com/forum/#!topic/mathbook-xml-support/JlhCQ0ljemg).

**Comment by rbeezer** [comment]
Bad floating figure behavior in LaTeX fixed at:  8357188f

`<blockquote>` enabled at: 1dc270d8

Report at link above.
