### ISSUE TITLE
Make sure navigation bar in mobile mode is always at bottom

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#37]
I just noticed this in class right now - could be pretty helpful!

**Comment by kcrisman** [comment]
To be clear, the class immediately said "yes we should have that"; scrolling to the bottom and then needing to scroll up even a medium-length page would have been quite annoying, according to unanimous decree (including the design major in my Number Theory class).

**Comment by kcrisman** [comment]
Oh, and to be REALLY clear, I see now that this only shows up when one zooms in so far that the "Contents" bar on the left disappears; otherwise the navbar is perfectly visible and usable no matter how far one scrolls.  So there may be other ways to solve this other than adding a navbar at the bottom, but at any rate that is the problem.

**Comment by rbeezer** [comment]
Once you zoom, or equivalently, reduce browser width, the HTML interface 
switches over to mobile mode, to accomodate all your students reading your book 
on their phones when they have nothing better to do.

Is this the behavior you are seeing?

Don't zoom so far, or get a wider screen?  ;-)

**Comment by kcrisman** [comment]
Yes, this is exactly the behavior.

> Don't zoom so far, or get a wider screen? ;-)

Nice try.  In mobile mode, then, there should be some kind of small navbar at the bottom of a page.  I'll edit the title.

**Comment by davidfarmer** [comment]
Apparently you aren't seeing the nav buttons at the bottom
when the screen is narrow?  The issue is why the feature is
not working, not that we need to add the feature.  Can you describe
the setup, and what you do see?

**Comment by kcrisman** [comment]
Okay, I think I have it.  The issue is that in some browsers the feature is not working - in modern Chrome and FF it works fine, in an older Safari not.  Given that we cannot expect everyone to have the most up-to-date browser (and I haven't tried this in IE, which of course many horribly old variants of still exist all over the world), probably there should be something retrofitting for that situation.  Maybe it's a too-new js library?

**Comment by kcrisman** [comment]
I'll send some screenshots off-list.

**Comment by davidfarmer** [comment]
It can be a truly enormous amount of work to support old browsers.

I really don't see the possibility of someone volunteering to write
that code, or us finding the money to pay someone to do it.  In fact,
if someone wanted to put that much effort into the project, I could
think of 10 other things that are higher priority.

Considering that there are (at least) 3 free modern browsers in which
things work fine, I am having a hard time imagining that supporting
old browsers could every become high on our list of priorities.

**Comment by kcrisman** [comment]
That may be so, but it's still worth having the ticket open.  In this case, I suspect it's something fairly innocuous.

**Comment by davidfarmer** [comment]
Please close, as this is obsolete
