### ISSUE TITLE
Fonts in captions

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#373]
In a sidebyside, captions are entirely sans serif (see numerous examples [here](http://mathbook.pugetsound.edu/examples/sample-article/html/section-side-by-side.html)).

But regular figures and tables have captions where the prefix (e.g. "Figure 5.2") is roman, like [here](http://mathbook.pugetsound.edu/examples/sample-article/html/section-5.html).

Should be an easy CSS fix.

**Comment by davidfarmer** [comment]
The problem was that those figcaptions no longer appear inside a figure,
as was assumed by the CSS.  Fixed.
