### ISSUE TITLE
introductions to (sub) sections

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#392]
Currently the HTML introduction to a section starts like this:

< article class="introduction" id="introduction-6" >
< h5 class="heading" >< span >< /span >< /h5 >

Currently there is *no* styling coming from the .introduction class.
The empty .heading provides some unintentional styling.

I suggest:

1.  Omitting the empty h5.

2. Adding a "section-like" class, so it would have
< article class="introduction section-like" id="introduction-6" >

That would allow us to style it properly, while not messing up the
introductions to other types of objects.

An alternative is to instead make it a section, not an article,
in which case you would not need section-like:
< section class="introduction" id="introduction-6" >
(but the introductions to other things, like theorems,
would still be articles)

Note that SL2X is even worse: it makes section introductions as a div
with no styling.  I'll change it to do the same as we decide here.

**Comment by davidfarmer** [comment]
The same issues arise for conclusions to a section.  For example, the conclusion
to Section 4.6 in 
http://mathbook.pugetsound.edu/beta/example/interesting-corollary.html

It is hard to tell that it is a conclusion to that section, and I'd like to have a
better way to mark it visually.  I can fiddle with the CSS, but not until after
we decide on the HTML markup.

**Comment by Alex-Jordan** [comment]
Hi David, it looks like some HTML tags in your post were eaten by GitHub. I might be able to deduce what you meant, but you mind reposting?

**Comment by davidfarmer** [comment]
Sorry. If you view it in GitHub, you can see the tags now.

**Comment by davidfarmer** [comment]
I looked at this further, and am now sure that the "introduction" to a chapter, section or
subsection must be an html "section", not an "article".

If there is a hidden knowl in the introduction to a section (which definitely
happens, for example when a section contains nothing but the introduction
and exercises), then the article-ness of the introduction makes it display poorly.

However, introductions to other things (definitions, exercisegroups, etc) are okay as-is.

**Comment by rbeezer** [comment]
This should be an easy one, and not controversial.

**Comment by rbeezer** [comment]
At 7790ca23

`introduction` and `conclusion` that are direct descendants of subdivisions (more precisely "structural" elements) should now be encased in HTML `section` (not `article`).  Everything else should be the same.

Changes live on website examples.  Sample article:  Chapter 4 leads with a short introduction, now with too much trailing vertical space.  Exercise group in Subsection 11.2 has an introduction that should remain unchanged.

Incidentally, removed some empty `h5` since I was in the neighborhood.

G'Night.

**Comment by davidfarmer** [comment]
I adjusted the trailing vertical space, but will need to look at
APEX and other examples once they re-build.

> Changes live on website examples. Sample article: Chapter 4 leads with a short introduction, now with too
> much trailing vertical space. Exercise group in Subsection 11.2 has an introduction that should remain
