### ISSUE TITLE
WeBWorK table border warning message

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#397]
This warning is produced during xsltproc processing every time it is relevant:

```
MBX:WARNING: medium and major will come out as minor in the hardcopy output of a WeBWorK PG table
```

I think we could change things so it just gets printed one time, instead of hundreds. It's going to be a very common warning in a book with lots of WeBWorK.

**Comment by rbeezer** [comment]
I've thought exactly the same.

Do you see the place at the bottom of  xsl/mathbook-common.xsl  where one-time 
warnings are issued?  Can you mimic such a setup in mathbook-latex.xsl?

**Comment by Alex-Jordan** [comment]
So I would add a one-time error to `mathbook-common`, and remove the warning from `mathbook-webwork-pg`, right? Not sure how `mathbook-latex` is involved.

**Comment by rbeezer** [comment]
I was taking "hardcopy" to suggest LaTeX output.  But I guess a WW problem may be printed by a student from a server where it may have migrated from an archive, so we could warn on **every** conversion (this in `-common`).

**Comment by Alex-Jordan** [comment]
To me, "hardcopy" is WeBWorK vocab for when a student prints a homework set from within WeBWorK. MBX latex output is different.

If a problem is authored in an MBX book, it will see use in a WeBWorK hardcopy eventually. Even if you are teaching the course and using the MBX book, some students will print a hardcopy of an assignment if you assign through WeBWorK.

**Comment by Alex-Jordan** [comment]
Addressing this in my current spate of WeBWorK related issues. I've got it to give a single warning message that includes a count of how many instances there are, but doesn't give location information.

I'm inclined to only print these warnings when `mathbook-webwork-archive.xsl` is used, because that produces the `.pg` files that might end up on a WeBWorK server, that might get pushed through WeBWorK's hardcopy production machine, and lead to the discrepancies these warnings are referring to.

Alternatively, I could print the warnings from `mathbook-common.xsl` and you'd see them all the time. Preference?

This is all predicated on my other work that isolates server-based png image scraping from server-based tex scraping. In other words, if you have authored a table in MBX source, then with MBX HTML and print output, that table *will* be rendered using MBX constructs, not say WeBWorK-generated tex. This is true even if elsewhere in the problem you are using a WeBWorK-generated png image.

**Comment by rbeezer** [comment]
Thanks for this.  I'd like to warn in  mathbook-common.xsl  as much as possible 
- folks should know *early* when something is going to behave differently across 
output formats.  Before they have hundreds of them.

With a one-time warning and a count, there is no point to have location 
information.  Discovered early, an author should know where the bodies lie.

Rob

**Comment by Alex-Jordan** [comment]
`mathbook-webwork-archive` does not call the common generic-warnings template. Should I make it so? Or only make it call the new generic webwork warnings template?

**Comment by rbeezer** [comment]
Yes, lets have  mathbook-webwork-archive  call the generic-warnings template.

Is there a need for a "generic webwork warnings" template?  Can they not go in 
the generic one?  I'd rather not have these proliferate too much.

Mostly, quality of source is independent of choice of output format.

**Comment by Alex-Jordan** [comment]
OK, sounds good.

What I meant was, what is currently

```
<xsl:template match="mathbook" mode="generic-warnings">
    <xsl:apply-templates select="." mode="xinclude-warnings" />
    <xsl:apply-templates select="." mode="xmlid-warning" />
</xsl:template>
```

is now going to be 
```
<xsl:template match="mathbook" mode="generic-warnings">
    <xsl:apply-templates select="." mode="xinclude-warnings" />
    <xsl:apply-templates select="." mode="xmlid-warning" />
    <xsl:apply-templates select="." mode="webwork-warnings" />
</xsl:template>
```
with `webwork-warnings` defined below. Right now there are three warnings all related to tables. If you'd prefer, I could name it `webwork-table-warnings` or something like that.

**Comment by rbeezer** [comment]
I did take a look at this.  ;-)  But not carefully enough.

Yes, that list of two can become a list of three.  That'll be good.

I didn't want the more specific templates  (-html, -latex, etc) to have a long 
list of these.

**Comment by rbeezer** [comment]
#438 takes care of this one.
