### ISSUE TITLE
section id=""

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#398]
In the sample article, two HTML "sections" end up in the backmatter.html, both with id="". This leads to xsltproc reporting an error form a duplicate id. Note: not all versions of xsltproc report this.

The offending sections are solutions to "Exercises 11.3 More Exercises" and solutions to "Exercises 16 Exercises".  They seem to be the only Exercises sections from the sample article. Apparently AATA gets 23 of these errors. AATA has 23 Exercises sections. These clues should help.

Probably a harmless error, but if your version of xsltproc reports this error, it might color your impression of MBX.

**Comment by rbeezer** [comment]
Aah!  That must be it!  Very good.

Back matter needs work, but I'd guess I can get something in place to stop this.  @twjudson will be very happy.

**Comment by rbeezer** [comment]
Easy - there was **always** an empty id being written.  Gone as part of  fb47adff

Alex - confirmation would be nice, since my `xsltproc` is not showing the error message.  But I'm confident enough to just close this anyway right now.

**Comment by rbeezer** [comment]
Forgot to thank you for digging this one up, I had not realized the **output** was checked for this sort of thing, I thought it was just the XML source, so all my hunting was in the wrong place.

**Comment by Alex-Jordan** [comment]
I can confirm that I don't get the error with the sample article. Thanks!
