### ISSUE TITLE
LaTeX for WebWork problems from a WW server have changed

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#399]
So we don't parse it properly and there are error messages about poorly formed XML and nothing gets rendered.

See https://groups.google.com/d/topic/mathbook-xml-support/QQBsGWQFNPs/discussion

**Comment by rbeezer** [comment]
@Alex-Jordan When this is resolved are you able to make a PR to the WW code with comments in the vicinity of these markers, so they don't change without warning?

**Comment by Alex-Jordan** [comment]
I'll do that.

**Comment by rbeezer** [comment]
Fix is now at #475

**Comment by rbeezer** [comment]
Looks like this is done, except for some mop-up.  See #475 for details.
