### ISSUE TITLE
 'activity.text.solution "no"'

### ISSUE THREAD

**Issue by mattboelkins** [rbeezer/mathbook#400]
I'd like the ability to suppress solutions to activities within the text and have them appear in the backmatter.  I imagine that will also require there to be something like  'activity.backmatter.solution "yes"' as well.  Thanks Rob.

Matt

**Comment by rbeezer** [comment]
The generic name for this class of elements is `project`, so the following new switches in `xsl/mathbook-common.xsl` will do what you want.  See post in a minute on Google Group with more details.
```xsl
<xsl:param name="project.text.hint" select="'yes'" />
<xsl:param name="project.text.answer" select="'yes'" />
<xsl:param name="project.text.solution" select="'yes'" />
```
I put in `backmatter` switches, and left them un-implemented.   They will get picked up in a much bigger refactor of exercises and the backmatter.  So I'm going to close this now.
