### ISSUE TITLE
inline exercises with knowl for answer

### ISSUE THREAD

**Issue by byoshiwara** [rbeezer/mathbook#410]
Is it possible for the inline exercises to have their answers show up only in knowls  and the sectional set of exercises have their answers only show up in the backmatter?

**Comment by Alex-Jordan** [comment]
Hi Bruce,

Yes. It's 4+ years later, so maybe you've got this covered now. Would you bring this up in `-support` if you still have questions? And if you agree, please close this issue.

**Comment by byoshiwara** [comment]
I can use  <solutions divisional="answer"> in the backmatter
