### ISSUE TITLE
Adjust image height deprecation warning

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#413]
If an image has a height attribute, you get this warning:

MBX:DEPRECATE: (2016-07-31) @height attribute on <image> is no longer effective and will be ignored (6 times)

But that is inaccurate for an image in a WeBWorK, where the height attribute (if specified) is a number of pixels. And is often necessary to specify.

**Comment by rbeezer** [comment]
We can have the warning not warn about WW problems.  But I'm reluctant to relax the DTD for the WW case, since it will lead to too much confusion on the "regular" images.

I'm presuming there really is no way to work off only a `@width`.

**Comment by rbeezer** [comment]
More selective warnings with better text about WW exception at 3f28eec0.

I've tested that existing functionality is OK, but have not tested fix for root cause.

@Alex-Jordan Can you test for your situation, confirm, and if so, close?  Thanks for clarifying this one.

**Comment by Alex-Jordan** [comment]
ORCCA previously gave:
```
MBX:DEPRECATE: (2016-07-31) @height attribute on <image> is no longer effective and will be ignored (7 times)
```
when compiling html, but now there is no message there. So I think it's good. Thanks for tackling it.

> I'm presuming there really is no way to work off only a @width.

No, due to the unfortunate limitations of how PGgraphmacros works.
