### ISSUE TITLE
Separate handling of WeBWorK solutions for inline vs sectional

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#415]
Implement a processing switch (or two) to control whether WeBWorK solutions are processed at all into the base64. Perhaps similar with hints.

So, an author would write a `<solution>`. The PG archive would _always_ include the solution. But the processing into a base64 string for the interactive HTML could omit the solution altogether. 

In this way, you could happily show solutions to inline exercises, but hide them in sectional exercises. And yet you still wrote them for the sectional exercises to be used in the archived form for use in actual WeBWorK problem sets.

Note: no way to achieve this kind of control if you are using an OPL problem. The solution will either show or not show depending on whether it exists in the first place and what the settings are in the anonymous host course.

**Comment by rbeezer** [comment]
Yes, that sounds like a good idea.

**Comment by Alex-Jordan** [comment]
This is implemented as part of the recent WW refactor, I think culminating at 3a548d2.
