### ISSUE TITLE
exercisegroup related CSS

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#416]
At http://spot.pcc.edu/math/orcca/section-cartesian-coordinates.html, exercises 6 and 7 are in an exercisegroup. The knowl for their solutions is not indented along with the exercise. (And I imagine the same would be true if there were an answer and a hint there.)

Relatively recent indentation of the exercisegroup exercises appears to have left behind these associated knowls.

**Comment by rbeezer** [comment]
Strictly CSS items for HTML are best over here - thanks!

https://github.com/BooksHTML/mathbook-assets/issues/77

**Comment by davidfarmer** [comment]
I made that example a bit better, but it is likely that there are other
cases (perhaps multi-column) that will need attention later.
