### ISSUE TITLE
WeBWorK switch for knowls

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#418]
Two switches that control whether a webwork is born as a closed knowl. Born open increases load time, but also could make for a better reading flow. Ultimately the author's/host's choice.

See: https://groups.google.com/d/msg/mathbook-xml-support/Vg2oG5lVdD0/euZq9hdSBAAJ

**Comment by davidfarmer** [comment]
Born-visible WW exercises are going to slow down the page load even more
than the (currently unacceptable) MathJax loading time for large sections.

One suggestion was a static exercise that can be toggled to WW.  If someone could
produce a couple of static examples, then I can experiment with the toggling.

A related suggestion was to move the end-of-section exercises to a special type
of separate section.  This prevents the load on the WW server every time the
section is opened.

What is the timeline for the born-open WW exercises?  Is there time to explore other options?

**Comment by Alex-Jordan** [comment]
Timeline is by Fall 2017, but preferably earlier enough to vet things before the Fall 2017 courses.

I like the idea to "activate" static versions. I think that will need significant XSL work though. This may have to wait and be part of a big WeBWorK feature run over the summer. 

Ideas on how this would work. For simplicity, suppose you have:

```
<exercise>
    <webwork seed="1">
        <setup>
            <var name="$a">
                <static>2</static>
            </var>
            <pg-code>
                $a=2;
            </pg-code>
        </setup>
        <statement>
            <p><m>1+1=</m><var name="$a" width="3" /></p>
        </statement>
    </webwork>
</exercise>
```

You would want this to produce the same output as

```
<exercise>
    <statement>
        <p><m>1+1=</m><fillin width="3" /></p>
    </statement>
    <answer>
        <p><m>2</m></p>
    </answer>
</exercise>
```

But also come with a button to toggle it to the iframe that calls the WW problem from the server using its base64 string.

One side note: I like that this would really force authors to rigorously provide static versions of vars. Right now, unless you are constantly reviewing your tex output, it's easy to let this slip by.

**Comment by rbeezer** [comment]
On 10/22/2016 02:43 PM, davidfarmer wrote:
> Born-visible WW exercises are going to slow down the page load even more
> than the (currently unacceptable) MathJax loading time for large sections.

Agreed.

> One suggestion was a static exercise that can be toggled to WW. If someone could
> produce a couple of static examples, then I can experiment with the toggling.

@Alex: do you think you could take an existing page with one WW problem and hack 
up an HTML static version right next to it, in some div encompassing both?  Or 
whatever David thinks is best?

Yes, it will take a bit of XSL to get the static, but we know how to do this for 
LaTeX for the variant parts.  My point is, we've thought through the MBX source 
pretty carefully.

> A related suggestion was to move the end-of-section exercises to a special type
> of separate section. This prevents the load on the WW server every time the
> section is opened.

Yes, yes, yes. ;-)

> What is the timeline for the born-open WW exercises? Is there time to explore
> other options?

A switch is perhaps trivial and might even make the code *simpler*.  But I'm in 
no particular rush myself so am happy to hold off.

Rob

**Comment by rbeezer** [comment]
Switches implemented at 7ed03ed0.  Default is to be born closed in external file knowl (status quo).

Load time for Chapter 1 of the sample WW chapter (six smaller problems) is not noticeably longer when all are born open.

Code is not twisted, but perhaps could be improved, particularly making these embedded knowls?

No announcement on the list until Alex can test.

**Comment by davidfarmer** [comment]
If this gets closed soon, then please open a new issue for toggling between static exercises
and a WW equivalent.

**Comment by rbeezer** [comment]
Yep, that was my plan - to split that off.  Thanks.

**Comment by rbeezer** [comment]
Closing this, and moved static versions to new issue.

@Alex-Jordan Can you announce this to the group when you think it is ready?
