### ISSUE TITLE
Allow copyright elsewhere than colophon (and document)

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#42]
It doesn't seem to just magically turn up in frontmatter.  In scla it is in the "colophon" but frankly you should be able to put it wherever you want to, and not everyone wants a "colophon".  It's also not mentioned in the article, even though transferring copyright of articles is this annoying thing we have to deal with for many publishers.

**Comment by rbeezer** [comment]
For openers, see:

https://groups.google.com/forum/#!topic/mathbook-xml-support/dHhbarrOCU4

Most any book or article has just one copyright at any one time, and now yu know where to place that information in your source.  If you want to talk about other copyrights, the "copyright" element will get you a nice symbol and you can use it anywhere.

There will be more (better) examples of this coming soon, eg Judson's AATA very soon and Beezer's FCLA some day.
