### ISSUE TITLE
index and larger TOC in sample article

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#425]
It is hard to find things you know are in the sample article.  It would help
if the index were activated, and until the index is comprehensive, have the
TOC include subsections.

**Comment by rbeezer** [comment]
Index is activated.  Not comprehensive. Now easier to find.  Have a peek.

http://mathbook.pugetsound.edu/examples/sample-article/html/backmatter.html#index-part-1

Note: sidebar ToC is 2-deep, content is chunked 1-deep.  Click on a secondary ToC bar, you get a page that is a section, and all 2-deep links get highlighted.

Thanks,
Rob

**Comment by davidfarmer** [comment]
I guess the javascript that is supposed to highlight just
the section you are on, has become broken.  (Or the markup
is not what the javascript expects).

**Comment by rbeezer** [comment]
I'm guessing the Javascript is "seeing" all those targets on the currently open 
page and so highlighting them.

So not newly broken, just an unanticipated use case?

**Comment by davidfarmer** [comment]
Now I am guessing it is the markup.  Scroll up and down this page and
you will see one seciton highlighted, which changes as you move:

http://sl2x.aimath.org/development/collectedworks/htmlpaper/0711.0718/section3.html

I need a break from CSS/layout, and I am guessing you
have higher priorities, so I'll make an MBX issue to be dealt with later.
