### ISSUE TITLE
Be able to xref to book node in latex

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#443]
I have currently something like  `<book xml:id=“abc”>`  Later in front matter I have

`<xref autoname="yes" ref=“abc”>Table of Contents</xref>`

because I want to be able to refer to that in the html (which works).  That causes a LaTeX error, however.   

Rob says,

> I think it makes sense for a reference to the whole book in LaTeX output to also 
go to the ToC.  If there is not a ToC (default for an article) then maybe it 
should go to the title (ie title page)? 

> I think it is just a matter of dropping the labels in the right places, with the 
ToC entry maybe being just a small fiddle to achieve. 

See also #424 and #198, though they are not the same.

**Comment by rbeezer** [comment]
Implemented at  6aeb2f20

See announcement on Google Group
