### ISSUE TITLE
Other tikz-based packages

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#47]
It would be nice to be able to specify some extra packages when using the `<tikz>` tag. The packages would be loaded in the template before the `\begin{document}`.

For instance, right now I'd like to use the `forest` package to make a tikz-based tree diagram. I think there are a lot of packages out there that would work similarly.

I'm happy to make modifications to `extract-tikz.xsl` and submit a pull request, but I'm interested if you have a suggestion for the right way to do this.

**Comment by rbeezer** [comment]
This was addressed (successfully) in #55.
