### ISSUE TITLE
Quotes are not rendered properly in html

### ISSUE THREAD

**Issue by geo909** [rbeezer/mathbook#482]
Hi,

Thanks a lot for mathbook xml, I'm most probably going to use it for my notes this term.

There is an issue with quotes. Consider the following code:
`        <p> ``quoted''</p>
`
With latex, this will produce [this](https://postimg.org/image/oghpzljjz/).

while with html, it will produce [this](https://postimg.org/image/4ynkqkg1r/).

Obviously the second is problematic. Is there any way around that?
Using `"quoted"` will not produce a nice latex output, so I would like to avoid it.

Thanks again

**Comment by Jahrme** [comment]
Quoted material should be enclosed in "q" tags, i.e.,
```xml
<p>Here we have some <q>quoted</q> text.</p>
```
This will produce proper quotes in both LaTeX and HTML output.

**Comment by geo909** [comment]
Oh, I see, that was simple, thanks so much.

**Comment by rbeezer** [comment]
And there is an "sq" tag which will produce single quotes.  There is rather 
sophisticated code to make various combinations of single and double quotes 
behave properly in LaTeX.  Imagine a single quote followed by a double followed 
by a single.  Will four left single quotes in a row in LaTeX do the right thing? 
  We make sure it does.

Spend some time with the sample article.  It is not very well organized, but it 
addresses many of these difficulties.  Part of the philosophy of MathBook XML is 
that an author should not have to be concerned about the target output(s) as 
they write.  Available off:

http://mathbook.pugetsound.edu/examples.html

Thanks for your interest - feel free to ask questions on teh Google Group, there 
is a good collection of authors there who would be happy to help with getting 
started (though many of us will be at the US math meetings, Jan 3-8).

Rob

**Comment by geo909** [comment]
Thank you very much for your reply. You're doing a great job with mathbook. It wasn't trivial to learn, but I think I got the grasp of it after a day of tinkering, it's defnitely worth the time investment.

I saw the google group, I'll make sure to bug you guys over there next time when I hit a dead end.

**Comment by rbeezer** [comment]
Thanks very much for the encouragement - its been a fun project.  I expect the 
day of tinkering will be repaid with greater efficiency going forward.  See you 
over in the group!

Rob
