### ISSUE TITLE
clarify where xinclude stuff goes

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#488]
Shouldn't the top file in a modular document also have 
```
<mathbook xmlns:xi="http://www.w3.org/2001/XInclude">
```
in addition to the subfiles?  The author guide doesn't make this clear.

**Comment by rbeezer** [comment]
Clarified in the context of an example.  Nothing was inaccurate, but perhaps this will avoid confusion.  At 378fac3003b3db3684229ea72b18cd3668dbcad8
