### ISSUE TITLE
More xinclude doc

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#493]
It turns out one can use xinclude to include just plain old identical text several times.  So here is an issue to document this in the relevant part of the author guide on inclusion.  From the list:

> A post on using xi:include to use the same content multiple times: http://www.sagehill.net/docbookxsl/DuplicateIDs.html
> Summary: it's fine if there are no id's in the repeated content. Also, some advanced techniques for if there are id's, or if you want to include the content but not the included file's root element.

**Comment by rbeezer** [comment]
I included this information at  378fac3003b3db3684229ea72b18cd3668dbcad8.  The information about duplicate IDs I now know it looks quite dangerous.  Interesting, and informative, but dangerous.  So I included the link, with disclaimers.

Thanks.
