### ISSUE TITLE
Clarify DTD for website (and other docinfo stuff?)

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#497]
> If you want to record this in an issue as an example to be considered as part of overhauling the DTD (a sabbatical project) that'd be great.  Might motivate me to make a DTD/schema label. 

> > Sample book gives bad DTD violation
> 
>         <website> 
>             <name><c>abstract.pugetsound.edu</c></name> 
>             <address>http://abstract.pugetsound.edu</address> 
>         </website> 
> 
> element name: validity error : Element name was declared #PCDATA but contains non text nodes

**Comment by rbeezer** [comment]
The `docinfo` should now be fully described in the RELAX-NG schema.  Though it is slated for an overhaul.

In particular, the `website/name/c` construction is now recognized.

If you find things in your project not covered by the schema, please open a new issue and it'll be handled fairly quickly.  Thanks for the reports.
