### ISSUE TITLE
Open source to the limit

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#507]
In HTML output, embed the MBX source of the relevant chunk (leaf or summary style).  Provide some UI device to reveal it in a way that parts can be cut/paste for recycling in associated projects (instructor worksheets, say).

A hidden knowl with pre-formatted text (suitably escaped) would be one way to basically accomplish this.

Easy to identify the root element of a chunk, and if it is a leaf node or a summary node.  Perhaps a separate XML-to-XML transform could chunk up the source, then the HTML transform could point to the pieces (e.g. as an external knowl).  Then the contents would not go out on the wire until requested.

**Comment by Alex-Jordan** [comment]
Did this get built with c6faf1bf89?

**Comment by rbeezer** [comment]
Yep, that's the commit.
