### ISSUE TITLE
allow "short titles" for page heads

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#510]
Many times there will be short versions of a long chapter title in the header for that chapter.  One gets lots of overfull reminders in LaTeX when this happens in MBX.  I can fix my own by just renaming chapters, but this could be a nice enhancement for book conversions, for instance.

**Comment by rbeezer** [comment]
Definitely planning some sort of alternate (short) title, which can be used in 
more ways than just headings.

Headings will get some attention sometime, too.

**Comment by rbeezer** [comment]
This was added about a month ago at 9cf8573ad064b29c980d4a906d89f9014dd96cc7 and 5 subsequent commits.  Well under a two-year wait!  ;-)  Thanks for your patience.

And work on LaTeX styling makes headers/footer/page styles easier to configure.
