### ISSUE TITLE
HTML: allow images to be downloaded in multiple formats

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#521]
For example, if you have provided (somehow) SVG, PNG, and JPEG versions of an image, then allow these to be downloaded in some user-friendly way.

See https://groups.google.com/d/msg/mathbook-xml-support/XscXe0mCD9s/m7mu1zI_BQAJ

**Comment by rbeezer** [comment]
Implemented at  138ffa08, with flexible configuration set-up on  9b274bba

See thread referenced above, sample article, and maybe upcoming Author's Guide documentation, for more.

Thanks, Alex, for laying the foundation on this one, and @davidfarmer for the necessary CSS.
