### ISSUE TITLE
Static versions of WeBWorK exercises

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#526]
This came up on #418, specifically at https://github.com/rbeezer/mathbook/issues/418#issuecomment-255555783

That issue was about something else and is closing now.

**Comment by rbeezer** [comment]
#411 looks related and might be entirely similar.

**Comment by Alex-Jordan** [comment]
The comment referenced above is more about a static version that can be "activated" by a click. The activation part remains to be done, but we do now have static versions.

**Comment by Alex-Jordan** [comment]
This has been accomplished as of ce976030d0b0, but it does need a WW server with version 2.16 or later. (And 2.16 has not yet been released.) I think this could be closed.
