### ISSUE TITLE
Online authors guide TOC

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#530]
The TOC in the online authors guide should be expanded to also show links to sections.

This really should be the default for MBX, because it is very difficult to navigate
when you have to go to the top page for a chapter to find out what subsections exist.

(I am not clear on the subtleties of chunk level, but a two level TOC should be the
default independent of whether chapters or sections are separate files.)

**Comment by davidfarmer** [comment]
Also need this for the sample article, especially since the index is incomplete.

**Comment by rbeezer** [comment]
I did this for the sample article at your request a while back.  (It is a processing option, but not the default.)  Or do I mis-understand something?

http://mathbook.pugetsound.edu/examples/sample-article/html/

**Comment by davidfarmer** [comment]
Looks good (and did not look that way the last time I checked!)

**Comment by rbeezer** [comment]
Author's Guide now has a 2-deep sidebar ToC.  As part of saying "PreTeXt" everywhere.  At 3ff7bc1d766a0eea81ab1c1b414ff3fe0c4c4027
