### ISSUE TITLE
Implement named lists in sidebyside

### ISSUE THREAD

**Issue by CVollet** [rbeezer/mathbook#535]
Also, it may help to know that all of this happened within an `<insight></insight>`

**Comment by CVollet** [comment]
But that doesn't seem to be the issue because commenting out the `<sidebyside>` fixed it so the lists show up.

**Comment by rbeezer** [comment]
Implemented at  63aa0450.

But see https://github.com/rbeezer/mathbook/issues/562

Discussion at:
https://groups.google.com/forum/?fromgroups=#!topic/apexactive-calculus-mbx-conversion/p52LbPNjLEM
