### ISSUE TITLE
sbsgroup and subcaptions

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#541]
An `sbsgroup` with a `caption`, where there is a `sidebyside` with a `figure` that also has a `caption`, causes the LaTeX to not compile. The issue is that the inner `figure` uses `\subcaption`, but the `subcaption` package has not been loaded because the usual trigger is when the parent `sidebyside` has a `caption`. There is no provision for when the grandparent `sbsgroup` has a `caption`.

**Comment by rbeezer** [comment]
I need to work on "sidebyside", "sbsgroup" and captions plus subcaptions.  Is this holding you up?  Do you want to make PR for the trigger?  Otherwise, I'm likely to save this to be part of an overhaul.

**Comment by Alex-Jordan** [comment]
We can address this particular thing just by adding the subcaption package to latex.preamble. I don't know that the output looks good, but that should make it compile. I think that means that there is no immediate need to make a PR.

**Comment by rbeezer** [comment]
`sbsgroup` is in good shape now.  Work begins at 4c8a65b6 and is woven in among next 10 or 15 commits.  Please report anything related that is not behaving.
