### ISSUE TITLE
index entries inside blockquotes throws an error

### ISSUE THREAD

**Issue by cfroccajr** [rbeezer/mathbook#542]
When I input something like this:

```
<blockquote>
<p>
1. Divide the number given by some 
    <term>prime number</term>
    <index><main>prime number</main></index> 
(i.e.) such a number that cannot be divided, but by it self, or unity; 
and the <em>quotient by some or other prime number</em>, and the <em>last 
quotient again by a prime number</em>; and so go on until the 
<em>last quotient of all be one</em>; and thus you shall find a certain number of 					
    <term>prime divisors</term>
    <index><main>prime divisors</main></index>.
</p>
</blockquote>
```

I get the error:

`MBX:WARNING: could not translate string with id "blockquote" into language for code "en-US"`

Since the quote I am using defines terms within its self I would like to put in index entries write where the terms are used.

(see [https://groups.google.com/d/msg/mathbook-xml-support/MFZm_aYA5bc/P76ESWR7CAAJ] )

**Comment by rbeezer** [comment]
Fixed at 64437ea3
