### ISSUE TITLE
Use a link checker on the MBX main site

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#543]
The following links on   http://mathbook.pugetsound.edu/    are broken:

    A First Course in Linear Algebra (Beta)

    Introduction to Computer Organization: ARM Assembly Language Using the Raspberry Pi 

It is advisable to use a link checker.

**Comment by rbeezer** [comment]
Now in use.  I don't particularly like the command-line tool I found (`linkchecker`) but I seem to have it configured to get the job done.
