### ISSUE TITLE
Fully implement `part`

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#550]
This will require preliminary work on level determination.

A `part` should be author-configurable in `docinfo` as "structural" or "decorative".  The former will rest numbering, the latter will insert divisions with no effect on numbering.  Both will affect the table of contents (maybe HTML sidebar ToC will see changes to allow this?).

**Comment by rbeezer** [comment]
From a discussion:

"Do you want your parts to be "decorative" or "structural"?  Former gives full-page intro in LaTeX, entry in HTML sidebar ToC, summary page in HTML, no affect on chapter numbering.  Latter is the same, but now all numbering has part numbers first and chapter numbering resets on each part.  I plan to implement both.  But perhaps a "design discussion" is in order before I leap."

**Comment by kcrisman** [comment]
Personally, decorative.   But yes, both should be available.

**Comment by davidfarmer** [comment]
If you really intend the "parts" to be separate stand-alone
documents, then it may make sense to restart the chapter numbering
in each part.  (Use case: different physical volumes in the
classical sense.)

But I have several multi-volume works in my shelves where they
number chapters consecutively across physical volumes.

I suspect most use cases will be consecutive numbering of chapters,
with the "part"s indicating some theme (or being "decorative"
as KDC put it).

I'd ask for a persuasive example for re-starting numbering before
going to the effort of implementing that.

**Comment by rbeezer** [comment]
Agreed.

On 09/04/2017 05:53 AM, David W. Farmer wrote:
> I'd ask for a persuasive example for re-starting numbering before
> going to the effort of implementing that.

CRC Handbook of Combinatorial Designs has seven parts, each with chapter number 
reset, in one physical volume.  IIRC, the rest of the series is like this (only 
have one here at home right now).

**Comment by rbeezer** [comment]
This has been implemented.
