### ISSUE TITLE
Warn about common misunderstood sectioning requirement

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#552]
If a subdivision has an expected next-refinement subdivision, then it needs to have just that refinement and optionally an `introduction` and/or a `conclusion`.  New authors do not always recognize this requirment.

if refinement is present, and filering out all refinements and intro/conclusion is not empty, then warn with an accurate report.  Perhaps a `for-each` at each subdivision level would be the way to organize this.

**Comment by Alex-Jordan** [comment]
If the only children of a subdivision are introduction and exercises, that causes a DTD violation. So perhaps should be warned against as well.

**Comment by rbeezer** [comment]
Thanks.  Once "exercises" gets a rethink, then maybe a run of "p" and friends, 
followed by "exercises" and/or "references" should be possible.

**Comment by Alex-Jordan** [comment]
I believe that works now. It's just if the p and friends get wrapped in an introduction that the DTD takes issue with.

**Comment by rbeezer** [comment]
Violations of the expected arrangement of elements *should* be caught by the DTD, or soon, the RELAX-NG schema.

I only want to write warning code for FAQ-level mistakes, and even then they will not always be comprehensive.  For example, in this case, the warning will only be effective, if the "non-introduction" material contains a `p`.

**Comment by rbeezer** [comment]
Implemented at c183292f.

Filtering, as suggested initially, would be better, but runs the risk of false-positives with metadata-ish elements like titles.  So took the easy way and just hunt for misplaced `p`, which is likely to almost always be the case.
