### ISSUE TITLE
disable mathjax scrolling

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#555]
The MathJax feature for scrolling to a hash should be disabled in the configuration,
not in the Mathbook.js javascript.  (DF removed the explicit MathJax dependence from
that script on 4/12/17.  That long script maybe should be broken into separate pieces?)

**Comment by rbeezer** [comment]
Answering my own question:

positionToHash: true

should become "false" in the configuration written into each page?

http://docs.mathjax.org/en/latest/options/hub.html

Do I understand right?  I can roll that into other changes upcoming (today, 
hopefully).

Rob

**Comment by davidfarmer** [comment]
Yes,
positionToHash: false
in MathJax.Hub.Config

The code in Mathbook.js does not make sense to me, so I am
not planning to delete it until I can sit with someone who
knows javascript and they can explain it to me.

**Comment by rbeezer** [comment]
Changed at bb1cba11.
