### ISSUE TITLE
CSS for byline in a section

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#56]
Just a note that the CSS for a byline at the level of a section might get some attention. A byline at the level of a chapter stands out as separate from the text, but not so much with a section.

**Comment by rbeezer** [comment]
Definitely.  It's another expediency.

**Comment by Alex-Jordan** [comment]
Also, related, in the pdf, all the author information I tagged for the
recurrence relations section is showing up jumbled:

  Alex JordanDepartment of MathematicsPortland Com- munity CollegePortland,
Oregon, USAalex.jordan@pcc.edu

instead of

  Alex Jordan
Department of Mathematics
Portland Community College
Portland, Oregon, USA
alex.jordan@pcc.edu



On Sun, Feb 22, 2015 at 9:35 PM, Rob Beezer <notifications@github.com>
wrote:

> Definitely. It's another expediency.
>
> On 02/22/2015 06:01 PM, Alex Jordan wrote:
> > Just a note that the CSS for a byline at the level of a section might
> get some
> > attention. A byline at the level of a chapter stands out as separate
> from the
> > text, but not so much with a section.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rbeezer/mathbook/issues/56>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rbeezer/mathbook/issues/56#issuecomment-75491736>.
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by rbeezer** [comment]
It was only designed for a name.  ;-)

But it should be able to contain more.  I think I have templates for this 
someplace.  That should be part of addressing this ticket.

How *much* iformation goes into SCLA is separate matter.  Not sure what I think 
there.

Rob

**Comment by Alex-Jordan** [comment]
Oh sure, I don't care what makes it into the final version. I was just
emulating something I found somewhere.

On Mon, Feb 23, 2015 at 8:07 PM, Rob Beezer <notifications@github.com>
wrote:

> It was only designed for a name. ;-)
>
> But it should be able to contain more. I think I have templates for this
> someplace. That should be part of addressing this ticket.
>
> How *much* iformation goes into SCLA is separate matter. Not sure what I
> think
> there.
>
> Rob
>
>
> On 02/23/2015 06:43 PM, Alex Jordan wrote:
> > Also, related, in the pdf, all the author information I tagged for the
> > recurrence relations section is showing up jumbled:
> >
> > Alex JordanDepartment of MathematicsPortland Com- munity CollegePortland,
> > Oregon, USAalex.jordan@pcc.edu
> >
> > instead of
> >
> > Alex Jordan
> > Department of Mathematics
> > Portland Community College
> > Portland, Oregon, USA
> > alex.jordan@pcc.edu
> >
> >
> >
> > On Sun, Feb 22, 2015 at 9:35 PM, Rob Beezer <notifications@github.com>
> > wrote:
> >
> > > Definitely. It's another expediency.
> > >
> > > On 02/22/2015 06:01 PM, Alex Jordan wrote:
> > > > Just a note that the CSS for a byline at the level of a section might
> > > get some
> > > > attention. A byline at the level of a chapter stands out as separate
> > > from the
> > > > text, but not so much with a section.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/rbeezer/mathbook/issues/56>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rbeezer/mathbook/issues/56#issuecomment-75491736>.
> > >
> >
> >
> >
> > --
> > Alex Jordan
> > Mathematics Instructor
> > Portland Community College
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rbeezer/mathbook/issues/56#issuecomment-75688562>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rbeezer/mathbook/issues/56#issuecomment-75696294>.
>



-- 
Alex Jordan
Mathematics Instructor
Portland Community College

**Comment by Alex-Jordan** [comment]
Also I noticed that if I include my name for the section, in the pdf, the text size persists into the body. So the section was in \Large

**Comment by davidfarmer** [comment]
It causes me a huge headache when in the LaTeX people put their
affiliation, email, and footnotes in the \author{...}.

LaTeX processes it into something readable, which satisfies the author.
But to turn it into HTML or actually split the information into fields
is almost impossible.

There are \authoraddress{...} and \authoremail{...}, but most people
don't use them.

It seems like that is what you need.  And maybe you need a way to re-use
that content if the same person's information is going in multiple 
sections.

**Comment by rbeezer** [comment]
Just fixed the font size bleeding through in the LaTeX output.  This was 
originally done in haste, and definitely needs to be revisted.  For example, the 
modal template ("name-list") should move out of the HTML file and into the 
common (text) utilities.

For now, an "author" element carrying your name should be minimally functional 
and will improve.

**Comment by rbeezer** [comment]
Agreed.  MBX has "author" and "editor" elements meant to carry these bits of 
information.  I have some recollection of discussing \authoremail{} before and 
thought you needed some extra package (amsart?).  (But cannot locate the 
discussion.)  Could be wrong, but I don't think it is vanilla LaTeX (which may 
be why it is not used so much).

In FCLA I had a scheme where "Contributors" were listed in the front matter and 
then just referenced at the location of their contribution.  For HTML their name 
was a knowl, containing all their information.  PDF was a hyperlink back to 
their entry in the frontmatter.

Once the basics of FCLA are converted to MBX, maybe I'll implement this feature 
in a general fashion for MBX - it seems generally useful, especially for open 
source projects, or "collections" where each chapter comes from a different person.

Rob

**Comment by rbeezer** [comment]
This is now in much better shape for PreTeXt generally.  FCLA and SCLA source may need attention.  See recent  `pretext-dev` posts and/or recently closed issues.
