### ISSUE TITLE
hungarian

### ISSUE THREAD

**Issue by czsanyi** [rbeezer/mathbook#561]
How can I exchange words? In the laguage-file it is an  <localization string-id='evaluate'><xsl:text>.........</xsl:text></localization> line. In hungarian language it is "kiértékelés". But in english is perfect the sentence "evaluate sage code", but in hungarian it is "Sage kód kiértékelése"

https://groups.google.com/forum/?fromgroups=#!topic/mathbook-xml-support/ZzBkV_oBK1M

Sándor Czirbusz

**Comment by kcrisman** [comment]
My guess is that one might have to localize the whole sentence and not just the individual words.  @rbeezer ?

**Comment by rbeezer** [comment]
@kcrisman:

https://groups.google.com/d/msg/mathbook-xml-support/ZzBkV_oBK1M/ntVlFqKwBAAJ

**Comment by kcrisman** [comment]
Sorry

**Comment by rbeezer** [comment]
Noooo problem.

**Comment by czsanyi** [comment]
Such is the hungarian grammar

2017-05-10 4:20 GMT+02:00 Rob Beezer <notifications@github.com>:

**Comment by rbeezer** [comment]
Changes at  63d43618, explanation on the Google Group.  Thanks, Sandor, for making an issue for this one.
