### ISSUE TITLE
xref in titles

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#565]
Having an xref in a title (of say, an exercise) keeps causing my LaTeX to fail to compile. The compilation fails where the exercise is born, so at a rather mundane place where the title is used. 

Rob has noted that titles migrate (to toc, other xrefs), and so a title like this with an xref would be even more awkward once it was used somewhere else.

I propose enforcing a ban on xref in titles.

**Comment by rbeezer** [comment]
On 05/17/2017 10:18 PM, Alex Jordan wrote:
> I propose enforcing a ban on xref in titles.

Yes, just like footnotes are banned in titles.  I will make a "relaxng" label 
and then get these into the DTD replacment.

**Comment by rbeezer** [comment]
Banned in new RELAX-NG schema.  Thanks for the report.

**Comment by rbeezer** [comment]
See #709 for the about-face.
