### ISSUE TITLE
author personname doubles

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#570]
See e.g. https://mathbook.pugetsound.edu/doc/author-guide/html/windows-install-notes.html where

```
  <author>
    <personname>Dave Rosoff</personname>
  </author>
```

has doubled the name in html output

**Comment by rbeezer** [comment]
This now behaves correctly due to commits at, and surrounding 730866290195881fb8aab8588da67bb3e0bc96e9

It is "accidental" in that the markup is not valid (the `personname` is superfluous here).  I'll adjust that next time I cruise sources for deprecation fixes.  Thanks for the notice.
