### ISSUE TITLE
Change use of task tag

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#573]
https://groups.google.com/d/msg/mathbook-xml-support/OxfG-ns97VM/x1JlQ8ADCgAJ

There’s a consensus forming around deprecating the current use of task, which is presently equivalent to project, activity, exploration, investigation, in favor of making it a child of those things. (We *think* that the only current user of task is TJ Hitchman, who is currently copied on this. Rob will help seamlessly update code to replace the task tag currently in use with something like project, and then the rename tag can be used to make “task” be the way “project”s are referred to within the *output* from MBX.) 

The rationale for this is that with the change, a project, activity, exploration, or investigation (“project-like”), which are frequently used in IBL-ish contexts, could then contain a sequence of task elements. Each of these tasks could have a hint, answer, and solution, as I described below. Precise formatting in HTML and PDF is to be determined, but it seems that these would likely appear with alphabetical labels such as (a) or a. (Basically as if putting a list inside an activity right now, but with the benefit that hint/answer/solution can be attached to each part, rather than putting a hint with a list inside it and then an answer with a list inside it and a solution with a list in it.) 

Current proposal is that a task may have a title, zero or more index entries, and then can be structured as a sequence of %para; (p, blockquote, pre, sidebyside, sage, figure, table, listing, poem, program, console, image, tabular) or a statement (which is a sequence of %para;) followed by zero or more hints, zero or more answers, and zero or more solutions. A project-like would keep its current structure but also be allowed to be set up as a sequence of %para; and task. Any other things we should consider here? 

How these things get rendered in HTML or PDF output is a matter for later. We’re just working on what the MBX syntax should be for the moment. 

Other question (specifically to Matt Boelkins and the Westfield crowd who have activity-heavy or IBL things): Anything else that we want to be able to put into a project-like beyond what can go in there now and the new task tag that will allow hint/answer/solution on each of what we might otherwise refer to as a “part” of an activity?

**Comment by Alex-Jordan** [comment]
I think this has been done. @mitchkeller, do you agree? If so, would you close?

**Comment by mitchkeller** [comment]
Yes, this was resolved a couple of years ago. Closing.
