### ISSUE TITLE
Add a glossary of initialisms to Author's Guide

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#574]
XML, GeGebra, sage, etc.

From Paul Blanchard.

**Comment by Alex-Jordan** [comment]
Things that might not naturally arise in other MBX documentation but could be helpful:
TLA
LMS
LTI
API
CAS

**Comment by rbeezer** [comment]
Initiated at d5cc7f9eae757072fbda7f08143420c73c09cae9.  Includes three in first comment.  @Alex-Jordan :  PR welcome for more!
