### ISSUE TITLE
items inside other numbered items shouldn't be numbered consecutively

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#577]
@davidfarmer suggests that having tables or other things _inside_ of other items not be numbered consecutively in the following way:

* Example 2.1
  * Table 2.2 (inside the knowled Example and hence not visible)
* Example 2.3
  * Table 2.4 (same)

**Comment by rbeezer** [comment]
And if the example is not knowled?

And, in the example provided here, how should they be numbered.

**Comment by kcrisman** [comment]
I don't know the answer to this, and you are right about knowls possibly changing this.   But somehow this should (in principle) be resolved, though it's obviously much lower priority than other stuff.  I guess this is just weird because inside...

**Comment by rplantz** [comment]
I wonder if tables even need to be numbered in many situations like this.

Bob

**Comment by Alex-Jordan** [comment]
I don't understand if the example is a suggestion how *not* to number things, or how to number things.

Whether certain things are born as knowls is a processing switch for HTML. If that were to affect numbering, then you cannot guarantee numbering on someone's rendering of the HTML will match someone else's rendering of the HTML. But much worse, you cannot guarantee that numbering in the HTML would match numbering in print.

**Comment by kcrisman** [comment]
The example is that these tables are **inside of** examples.  So, at least potentially, this is very confusing.  I understand the comment about whether things are knowled.  To me, the table and example might even have the same number, but in any case this sort of behavior is confusing.

**Comment by rbeezer** [comment]
Soon there should be a purely-layout element that does not get a number, while 
figure/table will be reserved for numbered things.

Problem now is figure/table has a structure/number purpose and a 
layout/placement purpose.

Rob

**Comment by rbeezer** [comment]
#148, if implemented, would give authors a partial cure for this situation.

**Comment by rbeezer** [comment]
Authors want this.  They want figures (and all they contain) in lots of places.  And this is the only way to put a numbered block inside another one (it is limited to inserting "captioned" items).

Two alternatives:
* Put the image (or whatever) in a `sidebyside` with just one panel.  It will look good and not be numbered.
* Put captioned items on a whole new independent numbering scheme (see finally implemented #148).  Which I think will be **more** confusing, but it will definitely be **different** and allow outermost items run consecutively even when hidden in knowls.

I can't think of anything else concrete to do.
