### ISSUE TITLE
Reusing an image

### ISSUE THREAD

**Issue by ladanielson** [rbeezer/mathbook#592]
I would like to reuse an image (to keep them in sync) without having to redeclare it's source.  Currently I code the original copy of the image and have an id:
```
<image xml:id="intervals-overlapping">
```
On the identical images I would like a `@source-id` attribute to resuse the earlier image.

**Comment by rbeezer** [comment]
This is now possible.  The attribute is `@copy`, to be consistent with other places with similar devices (like copies of Sage cells).  Code at aed901d1

See Chapter 9 of the sample article at the penultimate subsection for two examples and more commentary.

This is tested, but I would not be surprised if there is some subtlety that is overlooked.  So re-open and comment if needed.
