### ISSUE TITLE
Good auto IDs, versions

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#594]
This page reminded me about lingering issues with auto-generated ids, and the eventual
need to declare versions/editions of documents:

https://cdn.rawgit.com/byoshiwara/mfg/master/LinMod.html

On that page, Problem 31 has id exercide38.

There is nothing technically wrong with that, because IDs function properly as long at they
are unique.  But perhaps it would be better if the id matched the problem number?

I suspect that the answer to that question is "not really, because it is unworkable".
A scenario which may cause problems is: hard-coded ids interleaved with auto-generated,
or hard-coded ids which conflict with auto-generated.

My real concern is when we get to the point of declaring Editions of documents.
I suggest that part of declaring an edition is having an ID for everything.  That way,
we can track content across editions, and avoid some of the usual headaches when
publishers come out with a new edition.  Authors will not want to add all those IDs
by hand, so we will want a mechanism for doing it automatically.

**Comment by rbeezer** [comment]
Recent discussion about, and work on, `@permid` make this moot, I believe.

Work initiated at 0103bbbb53fa509a7bb66c9b74f405170fdf37b9
