### ISSUE TITLE
Local references having less verbosity.

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#61]
For example, right now if I'd use `xref` in Exercise 2 to refer to Exercise 1, the output string is something like "Exercise 1.1.1.1". It would be nice if it would just be "Exercise 1". See https://groups.google.com/forum/#!topic/mathbook-xml-support/kXCrMcmVCCk.

**Comment by rbeezer** [comment]
Exact same situation applies to citations, since we allow for multiple bibliographies, and hence need hierarchical numbering for long-distance references.

**Comment by rbeezer** [comment]
After a fresh pull, try the following in your customization layers (both LaTeX and HTML):

```xsl
<xsl:template match="exercises//exercise" mode="xref-number">
    <xsl:apply-templates select="." mode="serial-number" />
</xsl:template>
```

This should make the number of every sectional exercise in a cross-reference simply it's "serial number" and not its "fully-qualified" number.  Similar variants will have similar effect, for example  match="exercise"  will apply to inline exercises also.  Can you report on success/failure?

**Comment by rbeezer** [comment]
The above is a quick fix for Alex's particular immedite needs.  Note that this may rely on `exercies//exercise` already having hard-coded numbers in LaTeX and thus already using a `hyperlink` rather than a `hyperref`.  So the fix may not work for inline exercises (as suggested).

**Comment by rbeezer** [comment]
I still think it would be good to *automatically* recognize certain cross-references as being <q>local</q> and react with a serial number.  This would require passing the `xref` and its `target` down into the cross-reference code for enclosing subtree comparisons.  Sectional exercises would be a good place to experiment.

**Comment by rbeezer** [comment]
One option (not sure I like it) is to allow  `local='yes'`  on an `xref`.

**Comment by Alex-Jordan** [comment]
This is working (making exercise references just use the serial number).

**Comment by Alex-Jordan** [comment]
I don't like the idea of `local='yes'` because it's the kind of thing you would use a lot and also not use a lot, so there would be a lot of manual setting of attributes in the source. Maybe an xsl expert can help with the more automated method.

**Comment by rbeezer** [comment]
Thanks for letting me know the short-term fix is in.

I was thinking of a two-prong approach.  Automatic detection of "localness" in limited cases (like "exercises" sections).  And the chance to selectively override with `local='yes'`.

**Comment by Alex-Jordan** [comment]
Going through issue where I was the author since I might be able to close them. This sounds like something that has been thoroughly addressed in the intervening three years with the `text` attribute on an `xref` and `docinfo/cross-references` . Do you concur?

**Comment by rbeezer** [comment]
Yes, I think there are good options now for this.  More to do along these lines, but distinct.  See, eg, https://github.com/rbeezer/mathbook/issues/312
