### ISSUE TITLE
Fig with caption in sbs sample article section

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#613]
Maybe this only helps me, but if the SBS section in the sample article (Section 22 currently)
also contained just a plain non-SBS image with caption, that would make it easier to tweak
the caption CSS.

**Comment by davidfarmer** [comment]
Also, it would be be good if the graphics section (section 9) contained a long caption that
wrapped across 2 or 3 lines.

**Comment by rbeezer** [comment]
Good idea.  Done.  At 2983a120.  I might have placed them elsewhere, but I put them at the end of each section so that they didn't disrupt numbering while the `sidebyside` refactor is so fresh.  Included cross-references nearby to test knowls.  One is really nearby.

(Looking good.)
