### ISSUE TITLE
Be more careful about punctuation at the end of titles

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#625]
For HTML, CSS provides a period.  Not so nice when an author has a question mark.  So we should use XSLT to notice and provide guidance to the styling.

Original discussion at:

https://groups.google.com/d/topic/mathbook-xml-support/N-bD8Kc_Qqc/discussion

**Comment by rbeezer** [comment]
And the styling in LaTeX should more closely match the HTML.

**Comment by rbeezer** [comment]
Would it help current CSS work, or be convenient to assume, that I build a function to see if a title has punctuation at the end in author's source?  And based on that, write a CSS class?

**Comment by davidfarmer** [comment]
It would be reasonable to check for "!" or  "?",
and write a class for that.  But don't check for "."
because it should not be there, and the double-period
will flag that.

Maybe there are other cases, but let's see actual examples before
implementing, since adding more cases will be easy.

**Comment by rbeezer** [comment]
I wrote the boolean ending-punctuation template for -common, since we'll need that eventually.  Not bomb-proof, but pretty reliable.  I could design a title that fooled it, so we'll just have to see, as a practical matter.

Very easy to then mark most all of the titles on "blocks" (examples, theorems, etc).  Sample for HTML:

http://mathbook.pugetsound.edu/beta/201712-16-title-punctuation

Example 4.2 now has a title ending in an exclamation mark.  The `span` surrounding the title has `class="title punctuated"` and is the only such example throughout.

I may make the discovery template public (after a percolation period), and can wait on HTML for whenever you are satisfied.  Of course, the class/indicator can take most any form you think is best.

**Comment by davidfarmer** [comment]
This should be working now.

It took me a while and other things have changed (that example
should no longer be in a .hidden-knowl-wrapper), but I don't
think that will make a difference.

**Comment by rbeezer** [comment]
Looks like too much has changed.  Example 4.2 has an exclamation and a period.

http://mathbook.pugetsound.edu/beta/20180106-title-punctuation//interesting-corollary.html

Otherwise I have a branch all ready-to-go.  I might be able to merge and announce while on the road.

**Comment by davidfarmer** [comment]
Ah, there are two cases, depending on being in a knowl or not.

Fixed now.

**Comment by rbeezer** [comment]
Going up now, before departing!

**Comment by rbeezer** [comment]
This should be in good shape on the HTML side now.  I've got periods going in many of the necessary places in LaTeX output now, as of 2134b197396bc323025dd980a0e73112a7e179bc

Call my attention to any necessary instances in LaTeX (I'm sure there are some) and it should be nearly trivial to add.
