### ISSUE TITLE
Clarify the use of modular source files, especially with the mbx script

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#626]
See discussion at https://groups.google.com/d/topic/mathbook-xml-support/oGA1gkAdF3M/discussion

**Comment by Pelonza** [comment]
So, it seems now, after a bit more discussion on that thread, that specifically the details I was missing to get it to work right were:

1) Just run the python-mbx script on the "base" file in the modular structure (e.g. index.ptx, etc)
2) Make sure to use full, absolute paths when calling it (maybe this isn't necessary??)

Just that bit of extra in the image-processing page of the author guide would have saved me a boatload of frustration... (I still would have had to install cairo/pdf2svg, but that's less troublesome)

**Comment by rbeezer** [comment]
Again, thanks very much, Karl.  Sorry this was a struggle.  But I appreciate you taking the time to suggest improvements.  I put the changes in Chapter 8, since they are a bit more general than just making images.  The material in Section 4.6 I mean to just be a pointer to the need for the script.

New "notes" in:  http://mathbook.pugetsound.edu/doc/author-guide/html/section-65.html

New section on mbx.cfg:  http://mathbook.pugetsound.edu/doc/author-guide/html/section-67.html

**Comment by rbeezer** [comment]
Forgot the commit: 7fd2c458
