### ISSUE TITLE
Make more visibile in side toc for Author Guide

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#631]
When I go to:
http://mathbook.pugetsound.edu/doc/author-guide/html/mathbook-author-guide.html

I can see "Appendices". But I think it would be better if each appendix's title were visible. Mainly, I might not realize that there is Windows-specific in there. I think I understand why such a topic is in an appendix instead of a main chapter. And yet if I were looking for Windows-specific help, I don't know that it would occur to me to peek inside appendices to see.

**Comment by rbeezer** [comment]
Duplicates #530

**Comment by davidfarmer** [comment]
This is a special case of the known issue that (I really want to
type this in all caps, but I won't):

    By default the TOC should show both chapters and sections

Showing only the chapter headings makes it difficult for almost everyone
to find what they want.

Maybe our wish list contains a way to hide the sections and only show the
chapters.  Until then, it is more annoying to not find what you want,
than to see a long TOC.
