### ISSUE TITLE
Move WW image attribute to tex-size

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#632]
And away from the form with underscores.  Since we have no identiers with underscores anywhere else.

I'm content to do this, with the full deprecation drill, but would like @Alex-Jordan to comment first.

**Comment by Alex-Jordan** [comment]
Sounds fine. It just has an underscore because that is how the corresponding Perl hash key is.

Perhaps with commentary I will leave in the forum, this attribute can be cut entirely.

**Comment by rbeezer** [comment]
Done at 49847cf5 with full deprecation drill.  Also found an improvement to the deprecation routines as a side benefit, at 5f40c02e

Not done in a backwards-compatible manner, simply as a matter of being low impact.
