### ISSUE TITLE
PreTeXt, not Pre\TeX{}t

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#633]
The "TeX" part of PreTeXt should be written as in those quotes.

It should not be written like the \TeX macro, with the E capital and dropped.

Among the reasons are:
  -the TeX is a nod to \TeX, not a claim to be part of \TeX
  -PreTeXt is pronounced like the word pretext, not prete(ch)t

**Comment by kcrisman** [comment]
> -PreTeXt is pronounced like the word pretext, not prete(ch)t
>
>

I have to admit this is slightly disappointing :smiley:

**Comment by rplantz** [comment]
Shucks. I wanted to pronounce it "prey-te(ch)t".   😉

--Bob

**Comment by rbeezer** [comment]
Done at b5039c2b.  Thanks, David.
