### ISSUE TITLE
imroved-width in mathbook-common

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#636]
The current dev tip of `mathbook-common` has an `$improved-width` variable in `<xsl:template match="image|video|jsxgraph" mode="image-width">`, but it appears to be unused. I am unsure if it is remains as an accidental remnant, or if it is intended to be used in the code that follows but accidentally goes unused.

I am attempting to get images in webwork to meet the percentage width standard, along with no height attributes.

**Comment by rbeezer** [comment]
I'm looking into fixing some of this width business, and have some current work on a branch.  But this has been there for a year.  Looks like an accidental remnant.  It'll go away when I get this reworked.

Thanks!

**Comment by rbeezer** [comment]
Now a non-issue with nothing to do.  Due to 1c63f4ca which likely removed this.
