### ISSUE TITLE
Allow a paragraphs element in places like the preface

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#639]
A `paragraphs` which did not allow numbered itmes might be useful in a `preface`, the `acknowledgement`, etc.

**Comment by Alex-Jordan** [comment]
ORCCA and CLM have `paragraphs`s in `preface`s. It all seems to come out well, but is a schema violation.

**Comment by Alex-Jordan** [comment]
Hmm. In my use cases, what I really want is a title on subdivisions of the preface. I'm drawing a blank on existing ways to do that without bringing in something that permits numbered children. I can only think of something new, as you say a paragraphs-lite for use in the frontmatter (and backmatter?).

**Comment by rbeezer** [comment]
I've  done exactly this in FCLA, so 100% sympathetic.  Appendices get a letter, so can contain further divisions and paragraphs, all with numbered (lettered?) Items.

But we want light sectioning of prefaces, acknowledgements, foreword (planned), etc.  Maybe we should just bite the bullet and make a ParagraphsNoNumber in the schema?  I'll look closer when I have a bigger screen.

**Comment by Alex-Jordan** [comment]
Hmm. In my use cases, what I really want is a title on subdivisions of the preface. I'm drawing a blank on existing ways to do that without bringing in something that permits numbered children. I can only think of something new, as you say a paragraphs-lite for use in the frontmatter (and backmatter?).

**Comment by rbeezer** [comment]
Implemented at a9b2c93fea3d2d31e926e66708b4381610196101, back in January.

`preface/paragraphs` may be used, it must have a `title`, and in this context (front matter) it cannot contain numbered items.
