### ISSUE TITLE
enumitem

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#64]
The `enumitem` package appears to only load if there are exercises or references. But it is also needed for lists, since currently the `enumitem` optional argument is used in things like `\begin{itemize}[label=\textbullet]`. 

I can fix this. Just making a note here. I may work on a pull request to handle a bunch of these issues later, with a commit for each one.

**Comment by rbeezer** [comment]
Yes, I hit this one last week rushing to prepare for class, and never got back 
to trace it down and make an issue.  Thanks.

The  enumitem  package went in to support references and exercises and their 
presence in the sample article never caused the package to not load.

I'd just test additionally on

ul ol dl

I don't think dl is fully-formed but will likely need  enumitem  eventually.

Can you put each fix on a different branch/pull request?  Then we can merge or 
evolve them separately without getting them all hung up on one particular change?

Thanks,
Rob

**Comment by rbeezer** [comment]
Needed this, so fixed it.  At 16030f99.
