### ISSUE TITLE
video in sidebyside

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#642]
Consider whether to permit `video` as a child of `sidebyside`. Mentioned by @Jahrme in the [forum](https://groups.google.com/d/msg/mathbook-xml-support/dPYAUjtsvGI/_eKesRP5BAAJ). Also, within a `webwork`, since we are not permitting `figure`, this would be the only way to have a `video`.

**Comment by rbeezer** [comment]
Partially along on this one, for Rob Hutchinson also.   Along with "console", 
"listing", and something else (escaping me at the moment).

**Comment by rbeezer** [comment]
YouTube and author-hosted videos are working well in `sidebyside` now.  Author-hosted needs a print representation.  I'm going to open a new issue for that.
