### ISSUE TITLE
Scientific names markup needed

### ISSUE THREAD

**Issue by dbrianwalton** [rbeezer/mathbook#661]
https://groups.google.com/forum/#!topic/pretext-support/iPSlFnYVn8g

Possible tag for scientific name (suggested: taxon) with sub-tags for component parts.
genus -- should be italicized and capitalized. After first usage may be abbreviated
species -- should be italicized and lowercase

**Comment by rbeezer** [comment]
Done at b6bfef9a

We'll need to define exactly what "first use" is if we are going to get fancy with that.  Open a new issue for that, I'm closing this one.

See Section 8.6 of sample article for more.

http://mathbook.pugetsound.edu/examples/sample-article/html/section-8.html#subsection-17

CSS will be coming at #686
