### ISSUE TITLE
Investigate overfull and underfull hboxes with sidebysides

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#671]
The sample article produces .tex that gives lots of overfull \hboxes, most (not all) specifically 3.33pt too wide. This seems like something that could be cleaned up in mathbook-latex.xsl.

I'm not sure that the overfull boxes cause any noticeable bad visual effect. But their presence in the log is distracting, especially when combing through the log looking for overfull boxes that do make a difference.

**Comment by rbeezer** [comment]
Thanks, Alex.  If it "seems like something that can be cleaned up" could you 
investigate a bit more to confirm?  It would make it easier to actually fix the 
problem with a good lead on what it is.

Thanks.

**Comment by mitchkeller** [comment]
For my book, they all seem to be 2.500pt too wide. I'm too much of a n00b to LaTeX's box model to be much help with investigating, but I'm happy to test against my book once there's something ready for checking.

**Comment by Alex-Jordan** [comment]
I think I got it. It's a `%` character at the end of a line issue. Change the output of something like

```
\savebox{\panelboxUimage}{%
\includegraphics[width=0.2567\linewidth]{images/cross-square.png}
}
```

to 

```
\savebox{\panelboxUimage}{%
\includegraphics[width=0.2567\linewidth]{images/cross-square.png}%
}
```

Note the extra `%`. Without this, the saved box is saving what I think is some flexible white space that follows the image. Flexible, but not down to 0. So you have a box that is slightly wider than what you use it for later.

Sorry I can't implement and test this right now. Rob, can you?

As long as you are testing, I think it would be worth testing out making these things come out like:
```
\savebox{\panelboxUimage}[0.2567\linewidth]{%
\includegraphics[width=0.2567\linewidth]{images/cross-square.png}%
}
```
where I've added the optional width argument for the saved box. I think that this would make `latex-image-code` images in a sidebyside behave well with respect to their relative sizing and be harmless elsewhere. Perhaps it is a separate issue, but if someone is about to be looking at lots of sidebysides to see if the `%` has no ill side effects, maybe it is worth looking at this change simultaneously.

**Comment by rbeezer** [comment]
Thanks, that is what I needed - sleuthing and prototype testing of a suspected 
fix.  It should not be a big chore from here.

Thanks,
Rob

**Comment by davidfarmer** [comment]
> \savebox{\panelboxUimage}{%
> \includegraphics[width=0.2567\linewidth]{images/cross-square.png}%
> }

Those are good examples of:

a) When the % at the end of the line is actually necessary

b) LaTeX that a typical person would not write.

An alternate solution is to put it all on one line,
with no space next to the curly brackets.

**Comment by rbeezer** [comment]
`3.33252pt` for me.  Accounting for 79 of 136 of the `Overfull \hbox' from the sample article.

@davidfarmer I would have said exactly the same thing.  Maybe I even did.  But read on.

In chasing through all this I now understand the `lrbox` **environment** better.  And it strips leading and trailing whitespace.  So no additional percents.  Could maybe even get rid of some.

So, all 79 went away, by simply shunting `image` and `figure\image` in panels away from `\savebox`.  At a2033adb

@Alex-Jordan No width option on `lrbox`.  Sample `tikz` seem fine.  Do you mind checking to see if there are any **improvements**?
