### ISSUE TITLE
CSS for front colophon credits

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#674]
Front colophon items, at lest the real short ones, have very generic markup.  New credits are similarly generic.  They look fine as-is, but two ideas for improvement:

1.  Group the credits together with less spacing.  See sample book copyright page for how this might look in print.

2.  Add some markup to the "p" elements?  Send guidance, or specifics, and I can get it out easily,

**Comment by rbeezer** [comment]
Forgot URLs

http://mathbook.pugetsound.edu/examples/sample-book/html/colophon-1.html

http://mathbook.pugetsound.edu/examples/sample-book/sample-book.pdf

**Comment by davidfarmer** [comment]
Maybe put a class="license" on the license paragraph.

We need some type of class on the 4 lines that start with a bold word,
and those words should be a span with a class (or at
lease a class on the "b").

**Comment by sepvar** [comment]
I added some comments to https://github.com/rbeezer/mathbook/issues/118 that I think are relevant to Daivd's comment here.

Those comments would also require "shortlicense" to allow a daughter "p", and perhaps an "image" wrapped by a "url"...  or perhaps "sidebyside",   I'm not sure of the best solution.

**Comment by davidfarmer** [comment]
How about class="credit" on the p's containing the bold face words,
class="title" on the b's inside those p's,
and class="license" on the license paragraph.

We also should have more markup on the list with the copyright c symbol.
At minimum, class="copyright" on that paragraph.

That will enable styling that page in the sample-book.  May need more classes if
more features are added.

I'll do the CSS shortly after the sample-book HTML has that markup.

**Comment by rbeezer** [comment]
OK, David, front colophon items implemented as suggested (at 9be71ea82e6dedc756d64717f9d9861dbe1147b7).  HTML example live at same URL as above.

I removed the colons after the bold words, assuming styling would make distinction/separation obvious.  I left in a space at that location, on the principle that it should render semi-OK when no CSS is present/possible.

Close this once CSS is in place, or let me know, and I'll close it.

Thanks,
Rob

**Comment by davidfarmer** [comment]
I don't see that markup at the "same URL above" (which was 
http://mathbook.pugetsound.edu/examples/sample-book/html/colophon-1.html
)

The classes needed in various places are:
credit
title
license
copyright

**Comment by rbeezer** [comment]
`xml:id` changed.  Obviously, old file should be deleted.  New URL looks to me as intended.  Sorry for the mis-direction.

http://mathbook.pugetsound.edu/examples/sample-book/html/front-colophon.html

**Comment by davidfarmer** [comment]
I added some styling.  Nothing fancy.  Feel free to suggest
changes, and/or close this issue.

**Comment by rbeezer** [comment]
Is it so un-fancy that I can't tell any difference from just the "b" tag?  That is fine, it looks good.  I'm just checking that there is not something amiss.  I did a hard refresh, which normally does reload CSS changes.

Tell me if I should see anything particular?

**Comment by davidfarmer** [comment]
The CSS supplies a colon, with extra space after it,
on the b tags.

**Comment by rbeezer** [comment]
Got it.  So un-fancy, I did not even notice.  Thanks for the follow-through on this one.  I'll be more careful in the near future about configuring `rsync` to trash files when it syncs.  I had that off initially.  Maybe with a fresh website. ;-)
