### ISSUE TITLE
Ban a few strings as xml:id identifiers

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#681]
If an author sets `xml:id="main"` on the root element (eg `book`) than it conflicts badly with the HTML `id` with the same value used in the HTML/CSS/UI design.

We should warn about banned `xml:id` where we warn about using periods in them.  And perhaps also with Schematron rules.

Original report:
https://groups.google.com/d/topic/pretext-dev/5Jz2xGxVBrg/discussion

**Comment by rbeezer** [comment]
Implemented at b1800a95d9fc8573edd0748a80c90b80a044bb37

Banned HTML id are (as near as I can tell by auditing the XSLT code)  

`masthead`, `content`, `primary-navbar`, `sidebar-left`, `sidebar-right`, `toc`, `logo-link`

@davidfarmer I see `main` as an element and as a class, but not as an `id`.  This was the source of the original complaint.  Might there be an obsolete `#main` in the CSS/Javascript someplace?

**Comment by davidfarmer** [comment]
The selector #main occurs in the CSS.  I will remove it since
it is not used.
