### ISSUE TITLE
Add a lightweight "paragraphs" to the schema

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#682]
This more restricted version would allow for use in front-matter divisions, such as the `preface`.

**Comment by oscarlevin** [comment]
Indeed.  I would very much like to subdivide my preface, and paragraphs seems a reasonable division.  It currently works fine, but it's not part of the schema.

**Comment by rbeezer** [comment]
This will need a "no number" version of `paragraphs` in the schema, to prevent numbered items, like a `theorem`, from sneaking into the un-numbered `preface`.

**Comment by rbeezer** [comment]
See #345

**Comment by rbeezer** [comment]
Completed at a9b2c93fea3d2d31e926e66708b4381610196101, then a logical extension at af8fb21ca7c30b08acf6ff7d1142607a92ad1d0b.

Thanks for keeping after this one, Oscar.
