### ISSUE TITLE
Describe how to copy content for reuse

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#684]
Anything in the schema that allows `xml:base` can be xinclude'd into source multiple times.  Useful for huge chunks of `latex-image-code` and `input` for `jsxgraph` and similar.

Caveat: material included twice cannot have any `xml:id` within it, as it violates uniqueness, and where would an `xref` point anyway?

Do this before, or with, #619.

**Comment by davidfarmer** [comment]
With a slightly clever preprocessor you could have an xml:id
in included material and not violate anything if it were included twice.

Just sayin'...

**Comment by rbeezer** [comment]
This is in better shape at  378fac3003b3db3684229ea72b18cd3668dbcad8.  Still need to re-iterate when `image/@copy` gets deprecated.
