### ISSUE TITLE
open feedback link in new tab

### ISSUE THREAD

**Issue by mattboelkins** [rbeezer/mathbook#687]
Rob,

From my post on the -dev list:

I set up the new "feedback" link for Active Calculus, which appears in the
bottom left of every page at http://faculty.gvsu.edu/boelkinm/Home/AC/index.html.

If you click on it, you're taken to a Google form.  I really like this new
feature.  I'm wondering, however, if it would be better if it was set up so that
the feedback form opened in a new tab or window, rather than leaving the page.
I'm thinking of a user who wants to copy and paste and/or look carefully at the
displayed text while writing a comment.

Thanks,
Matt

**Comment by rbeezer** [comment]
Done at  e0855366.  Link will open in new tab or new window - which is under the control of the browser, we cannot influence it.

I rewrote the surrounding code, to have the same effect, but please report any odd behavior.

Thanks for the suggestion - that's another good little change.
