### ISSUE TITLE
Indent body of references

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#688]
HTML styling of a `biblio` element should match that of LaTeX for now.  In other words, the body should have a margin indented across the lines of the citation.  SoundWriting project needs this so students reading the writing handbook do not see bad examples.

@davidfarmer Is it simple enough to style `div.bibentry` as a box with some left padding/margin?  So the number hangs out, far left, by itself?

Model:  http://mathbook.pugetsound.edu/examples/sample-book/sample-book.pdf, p 16

Sandbox:  http://mathbook.pugetsound.edu/examples/sample-book/html/references-1.html

**Comment by davidfarmer** [comment]
Now the HTML references should more closely match the PDF.
http://mathbook.pugetsound.edu/examples/sample-book/html/references-1.html

**Comment by rbeezer** [comment]
Thanks! I've sent it on to the Sound Writing group.

**Comment by davidfarmer** [comment]
At some point we need proper markup of bibliographic entries.

**Comment by rbeezer** [comment]
Yep.  I want to leverage the CSL (Citation Style Language), so this will be a 
big project.  "biblio" is probably the worst-off part of PreTeXt.
