### ISSUE TITLE
Algorithm not in list of theorem-like environments

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#69]
More precisely, <theorem>, <corollary>, <lemma>, <proposition>, <claim>, and <fact>, all behave exactly the same, requiring a statement (as a sequence of paragraphs) followed by an optional proof, and may have an optional title. The elements <definition>, <conjecture>, <axiom>, and <principle> are functionally the same, barring a proof (since they would never have one!). Definitions are an exception, as it is natural to place <notation> within—see the source for Definition 2.2 for an example.

**Comment by rbeezer** [comment]
Right!  Thanks.  Soon.

**Comment by rbeezer** [comment]
Added at a5266fe7.  Thanks for the catch. -Rob
