### ISSUE TITLE
common template breaking PG extraction

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#693]
In trying to patch the WeBWorK server-based images issue, I wanted to examine PG output from `make sample-chapter-extract`. I get this error, followed by the build halting:
```
runtime error: file /Users/alex.jordan/mathbook/xsl/mathbook-common.xsl line 5355 element apply-templates
```

It gets part way through section 2. I would guess line 506 of the sample article has something to do with this, given what line 5355 in common is about.

**Comment by rbeezer** [comment]
The base "xref-link" template  should be doing a "copy-of", not an 
"apply-templates".  But it should not even be called at all.

I can't see immediately how we made cross-references during PG extraction.  Were 
they just the text, with nothing active?  In any event, I believe we need a 
*real* "xref-link" template for the PG extraction, even if it just duplicates 
the text.

Probably whatever was in -common before was good enough to do the right thing. 
I'm not in a position now to find the right commit to see what that was.  But 
does that sound plausible?

Rob

**Comment by Alex-Jordan** [comment]
Yes, I think that all we do is print the text and there is nothing active. Although it would help to not use nbsp, and just use regular space. Or we add nbsp to the character set that the base64 works with. Or the nbsp gets printed as `[$NBSP]`.

**Comment by rbeezer** [comment]
I think the least exceptional fix is to implement the (abstract) nbsp template 
as [$NBSP], which I can do along the way.

**Comment by rbeezer** [comment]
Fixed general (base) template at 35e2c7a8, implmented WW `xref` as just the text at 30cb7dbc.

Samples will be uddated later tonight.  `[$NBSP]` is already implemented as `[$NBSP]*`.  I presume the `*` is a good thing.

**Comment by Alex-Jordan** [comment]
Unsure if this recent edit is to blame, but no cross references at http://mathbook.pugetsound.edu/examples/sample-article/html/section-cross-referencing.html are providing links or knowls now.

**Comment by rbeezer** [comment]
Thanks, Alex.  Forgot to confine the change to xref within WW only.

Should be fixed now at b830b0ba.  Thanks for the heads-up!

**Comment by Alex-Jordan** [comment]
I don't think this is resolved.  It looks like b830b0b may have confined things too far.

Also, all _appears_ working if I view the output from the site. But that output is dated Aug 23 (or much earlier in the case of the PD output) and this is the same date as b830b0b. And there has been a commit 0dacffa since then too. So I'm basing all this on my own dev, which is at 0dacffa.

If I run `make sample-chapter-extract`, I get lines like this in a .pg file:

```
First, identify the coefficients for the quadratic equation using the standard form from [LINK: Theorem[$NBSP]*[XREFNUM]]
```

That's coming from `scratch/pg/local/Integrating_WeBWorK_into_Textbooks/2-The_Quadratic_Formula/2_2-Solving_Quadratic_Equations.pg` which is coming from the current line 506 of the sample chapter.

Since the bracket is a PGML control character, the whole cross reference ends up blank. It should be just:

```
First, identify the coefficients for the quadratic equation using the standard form from Theorem[$NBSP]*[XREFNUM]
```

**Comment by rbeezer** [comment]
The `mathbook-webwork-pg.xsl` file gets used twice: once for generating full-on HTML versions, and once for constructing a problem archives.

Certain templates need to be available for the latter, but then conflict (supersede) when used for the former.  Worse, an "xref" has a location and a target, possibly one inside `webwork` and one outside.

I'm telling you this so you can remind me later.  ;-)  Maybe the file should be split into two, to allow for dual purposes?

Anyway, try now.  Theorem 2.1 tested for problem extraction, HTML generation, and then regular sample article checked for breakage.

Thanks for the careful report, that helps a lot.

Rob

**Comment by Alex-Jordan** [comment]
Thanks Rob, it's doing what it should do now in ORCCA.

Trying to really simplify and streamline all webwork processing, so I'll think about the other things you said.

**Comment by rbeezer** [comment]
Shooting from the hip - maybe certain things go in a file that **only** gets used for archive creation.  Or maybe **only** for HTML creation.  Or both?

I'm not going to think about it too hard until your new stuff rolls out. ;-)

**Comment by Alex-Jordan** [comment]
A note: "archive" creation is not going to just be archival anymore. For print, the extracted .pg version is sent to the server, and returned as "static-ptx". And then static-ptx is used for print. And also, some day, for other static output formats, including HTML before you'd "make it live".

So the distinction would be more complicated. I almost decided it was static/not-static. But then I remembered the extracted .pg file is not static.
