### ISSUE TITLE
Left and right margins for side-by-side

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#698]
To push a `sidebyside` panel flush-right, it seems necessary to have asymmetric margins.

And then maybe the internal XML layout data structure should be `n` panel widths, with `n` preceding gaps (which should all add up to 100%).

**Comment by Alex-Jordan** [comment]
Is this about having _one_ panel be flush right? By doing things like `widths="47% 47%" margins="0%` I seem to be getting flush right (and left) panels.

**Comment by rbeezer** [comment]
Right.  I mean "correct."

Joe C is pushing a *single* panel far-right with an empty "p" as a faux first panel.

I've always meant to allow

margins="50% 0%"

but was saving the complication for later.

**Comment by rbeezer** [comment]
Implemented at 5ae4cbd9
