### ISSUE TITLE
Figure enumeration in LaTeX

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#70]
I have a `table`, and a `figure` that follows it right away. They are both in section 1.2. 

The `table` is Table 1.2.7, but the `figure` is Figure 1.8. This is only happening in the LaTeX side, not the HTML side (which has 1.2.7 and 1.2.8), so probably an issue with `mathbook-latex.xsl`.

**Comment by rbeezer** [comment]
Can you go

git checkout 0af94a68b5d

which is right before "side-by-side" (and is your whitespace patch) and see if 
the behavior is the same at that point?

git checkout dev

will put you back where you were.

**Comment by Alex-Jordan** [comment]
Yes, that made the numbering go back to 1.2.8. I'll alert @cmhughes who I think may be working on a patch to `sidebyside` already.

**Comment by rbeezer** [comment]
I just sent him some other patch-worthy material about an hour ago.  ;-)

**Comment by Alex-Jordan** [comment]
Never mind. My issue was due to a command that I had put into my `latex.preamble.late`.

**Comment by cmhughes** [comment]
Just to clarify, sidebyside didn't mess this up, correct?

**Comment by Alex-Jordan** [comment]
sidebyside does not, as far as I have seen, mess up figure enumeration. I had messed up figure enumeration all on my own :)
