### ISSUE TITLE
Only load jsxgraph when needed

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#703]
Several times (including right now!) I cannot load the sample article because the
connection with jsxgraph.uni-bayreuth.de is hanging.  

I think it is sufficient to only load it on those pages which actually need it
directly for the literal content on that page.  Needing it for knowl content
is not a likely use case.  (Maybe it is slightly more sophisticated to load it on all pages
provided a certain fraction of the pages need it.)

**Comment by rbeezer** [comment]
Me too.  Over the weekend.

I'll look into changes.

**Comment by rbeezer** [comment]
This would be worth doing carefully, and considering the effect on knowls along the way.

But for now, I found a better place to get `jsxgraph` from.  It seems quite fast.  So the immediate fustration should be relieved.

At 725ad01c

**Comment by davidfarmer** [comment]
Console tells me:

Loading failed for the <script> with source “https://cdnjs.cloudflare.com/ajax/libs/jsxgraph/latest/jsxgraphcore.js”.

Is JSXGraph working for you?

**Comment by rbeezer** [comment]
"latest" was a test that somehow got merged.

Fixing it now...

**Comment by rbeezer** [comment]
Working now, may require a hard refresh.  Not sure how that crept in, maybe on another commit.  Thanks for the notice.  (Could be a record turnaround.)
