### ISSUE TITLE
alert should have better HTML markup

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#705]
< alert > in PTX becomes < b >< i > in HTML.

It would be better to have it as < em class="alert" > .
(The CSS for that should already be in place.)

This would be a good issue for a someone who wants to start contributing to the xslt.
Maybe there could be an appropriate tag for such issues.

**Comment by rbeezer** [comment]
Done.  "beginner" label, in addition to existing "contributor project".

**Comment by rbeezer** [comment]
Advice for a beginner:  write "bare" HTML for the output, don't use the `<xsl:element name=...` approach.  The former is encouraged, and the latter is only necessary when parts of the output change programatically.

**Comment by davidfarmer** [comment]
Done
