### ISSUE TITLE
Should footnote knowls be in hidden-knowl-wrapper?

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#707]
I think the answer is 'no'.

For example, consider footnote 8 here:

http://www.math.ubc.ca/~andrewr/CLP/clp_1_dc/subsection-15.html

Opening the knowl splits the sentence.

Probably this is not usually noticeable, because footnotes often come at the end of paragraphs
(although I had thought it was weird when the period at the end of a sentence moved
when the knowl was opened).

If a footnote always appears in a paragraph or other block level element,
then the hidden-knowl-wrapper should not be needed.

This may be a beginner-worthy issue.

**Comment by rbeezer** [comment]
Definitely not beginner-worthy!

Resolved collaterally as part of 708be6a4c0c12f0443fe41c297c2086821fa85af
