### ISSUE TITLE
Error in MBX Script for Python 3

### ISSUE THREAD

**Issue by Pelonza** [rbeezer/mathbook#708]
See this discussion:
https://groups.google.com/d/topic/pretext-support/0mNh3Nx7CVA/discussion

Small error on the arg-parse for compatibility in Python3 vs. Python2

**Comment by rbeezer** [comment]
`None` value for args.verbose now considered at 242a6d3f.

@Pelonza Could you double-check at least your Anaconda setup?  And more, if possible?  On my system I've checked 6 combinations

`{-vv, -v, no flag} x {Python 2.7, Python 3.5}`

Thanks.
