### ISSUE TITLE
Allow references in titles

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#709]
Both internal, `xref`, and external, `url`.  Use matches on `*/title`.

* Implement as plain text, ie inactive links, due to use and movement.
* Maybe the `xref-link` macro needs the context and target switched as arguments?
* Schema then could be relaxed to allow `TextLong` in titles.  This would conform with the `Group` pattern.
* Generally, maybe schema needs variants of the recursive `Group` pattern.  It does not look like `TextShort` can be totally expunged.

**Comment by sepvar** [comment]
FYI: just voicing support: I am interested in having references that are inactive links.

**Comment by rbeezer** [comment]
Implemented specifically at a0866d26bfc1c2bfdede92d725907d90275a8280, pretty much as described above, but with several associated commits nearby.  Some discussion in a minute on a `pretext-support` thread:  https://groups.google.com/d/topic/pretext-support/HnfKBWy4m44/discussion
