### ISSUE TITLE
Vertical stacks in sidebyside panels

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#714]
Potentially two new elements, for use only in `sidebyside`.

* `stack` can go in any `sidebyside` and can hold non-captioned items.  It becomes a single panel, with contents stacked vertically.
* `panel` can go in a `sidebyside` that allows captioned items.  It can have `@xml:id`, `title`, and `caption`.  Contents are just like `stack` (what is allowed, how they behave), but visually the resulting panel looks and behaves like a `figure`.  It can be an  `xref` target, potentially sub-captioned, etc.

**Comment by rbeezer** [comment]
Maybe allow a title on `stack` and both a `title` and a `caption` on `panel`.

`paragraphs` as a titled container of multiple `p` could be replaced by these constructions.

**Comment by Alex-Jordan** [comment]
The schema currently permits `sidebyside/paragraphs/sidebyside/tabular`, but it should not. The proposed `stack` element should functionally replace this: `sidebyside/stack/tabular`. See [forum thread](https://groups.google.com/d/msg/pretext-support/VH6fEjftcXE/hy-48emZAwAJ)

**Comment by rbeezer** [comment]
A `stack` element is implemented at 0cf4e5f6e47b1b4df8b952d28d46f6ff55dbcc5f, and following.  No title, no caption.  Not so sure about the speculative `panel`.  Not even sure about any `title` at all in a side-by-side panel.

`sidebyside/paragraphs` will be deprecated shortly, so I think this can be closed now.
