### ISSUE TITLE
Chunking of .tex files

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#72]
Enhancement

Could we compartmentalize .tex output? There would be a switch like `latex.chunk.level` with options `<empty>`, `chapter`, `section`.

If `chapter` is used, then the output would be:

    `book.tex` (with instances of `\include{chapter1}`, `\include{chapter2}`)
    `chapter1.tex`
    `chapter2.tex`

If `section` is used, then the output would be:

    `book.tex` (with instances of `\include{chapter1}`, `\include{chapter2}`)
    `chapter1.tex` (with instances of `\include{section1.1}`, `\include{section1.2}`)
    `chapter2.tex` (with instances of `\include{section2.1}`, `\include{section2.2}`)
    `section1.1.tex`
    `section1.2.tex`
    `section2.1.tex`
    `section2.2.tex`

Also, there could be the switch `latex.include.only`, which could be a string like `chapter1,chapter3` and be used as the argument to `\includeonly{}`.

**Comment by rbeezer** [comment]
The hard part of this is done at 6dafc155 and see support list in just a minute.  I'm using `\input` to incorporate the subsidiary files.

`\include` is a bit brain-dead.  Cannot be nested, can only appear at the top-level and introduces extra `\clearpage`.  But I do understand the desire for `\includeonly` which should be easy to implement, though error-checking may not be too robust.  I'm going to put that on a new issue.
