### ISSUE TITLE
Refactor the TOC

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#724]
So that it is not a mix of h2 and ul.

**Comment by rbeezer** [comment]
Protypical example at

http://mathbook.pugetsound.edu/examples/sample-article/html/section-12.html#subsection-28

First list (First, Second, Third) is the first bit of content in a `p`.  HTML has empty paragraph right before it, presently with HTML `id` set to `p-312` (which can change over time).

This is basically the only way this can happen, unless someone just authors an empty paragraph, which we should prohibit in the schema anyway.

**Comment by davidfarmer** [comment]
Also make a way to number the sections in the TOC

**Comment by rbeezer** [comment]
> Also make a way to number the sections in the TOC

Introducing these numbers, with whatever markup you wish, should be trivial on the PTX -> HTML conversion.

**Comment by davidfarmer** [comment]
This has been done.
