### ISSUE TITLE
Eliminate empty HTML p

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#727]
Whatever is causing empty HTML p tags should be examined and then handled
in a different way.

Gather examples here, and then discuss what to do.
(Links to the HTML are preferred.)

I'd like the the solution to not involve wrapping a collection of items in a div,
because the things that can appear adjacent to that div may need to be handled
as a special case.  (But if we have to, we have to.)

**Comment by rbeezer** [comment]
Duplicated by #742
