### ISSUE TITLE
Empty title in assemblage

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#728]
In the small assemblage immediately above Section 4.6 in the sample article:

http://mathbook.pugetsound.edu/examples/sample-article/html/interesting-corollary.html

There is an h5.heading containing only an empty span.title .
This causes issues with the layout.

**Comment by rbeezer** [comment]
When the title is empty, I'll delete the "span".  Should the "h5.heading" go 
away entirely then?

**Comment by rbeezer** [comment]
The template doing this is also used for `aside` (presently title optional) and `paragraphs` (eventually title required).

**Comment by davidfarmer** [comment]
Yes, we also don't want and empty .heading.

**Comment by rbeezer** [comment]
Done at  e26e96e819ae3fb17706b1cad7dbb5550d4ee50e

Close if satisfied.

**Comment by davidfarmer** [comment]
Looks good.

Online HTML Sample Article needs to be updated.

**Comment by rbeezer** [comment]
On 09/22/2017 05:29 AM, David W. Farmer wrote:
> Online HTML Sample Article needs to be updated.

Right!  My upload script has been waiting all night for my password. ;-)
