### ISSUE TITLE
Relocate footnote hidden knowl content

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#731]
`fn` are only inside paragraphs.  Leave hidden knowl clickable at site, but when paragraph is finished, write knowl content in a `div` **outside** of the paragraph.  Even though a "p" gets busted up, it should be OK to put the content at the end of the author's logical paragraph.  It will open at first opportunity?  It should.

Then schema can be relaxed to allow `fn` content to have runs of (simple) paragraph-like material.

**Comment by davidfarmer** [comment]
And footnotes can have footnotes: a feature which scholarly books have had for centuries!

**Comment by rbeezer** [comment]
Evil.

I'll test, of course, but I'll guess right now that once the content gets ripped 
out, it may just be OK.

**Comment by rbeezer** [comment]
Have not addressed footnotes within footnotes.  And perhaps hope I never will.

But footnote content (born-hidden knowls) are being relocated in HTML (and in LaTeX).  Primary commit for HTML was about a year ago:  40df7a3d24f6626cad6f4d9d9d54a384e6717b5a
