### ISSUE TITLE
Rename .hidden-knowl-wrapper

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#733]
How about ".kohere" as in "knowl open here".

If that class is on the "a" tag, then you don't need a surrounding div.hidden-knowl-wrapper,
and the knowl will open after the "a".  (So put that class on the a tag of a born-hidden
example, but not on a footnote.)

That class can be used wherever we currently use .hidden-knowl-wrapper.  Eventually I'll
delete .hidden-knowl-wrapper from the knowls code.

Code is already in place.  I'll modify the code if we choose a different class name than kohere.

**Comment by rbeezer** [comment]
That all sounds great.  Thanks.  A bit of admin this morning, then I'll get to this.

**Comment by rbeezer** [comment]
Highly functional, and big code improvement (HTML, XSLT), but styling is not coming through.

http://mathbook.pugetsound.edu/beta/20170925-kohere/interesting-corollary.html

Correct me if some part of this is wrong (the `id` can move from `a` to `article`):

```html
<article class="example-like">
  <a knowl="" class="id-ref kohere" refid="hk-example-structured" id="example-structured">
    <h5 class="heading">
      <span class="type">Example</span>
      <span class="codenumber">4.5</span>
      <span class="title">An Example of Structure</span>
    </h5>
  </a>
</article>
```

**Comment by davidfarmer** [comment]
I need to rework all of that, because the CSS was assuming
the surrounding div.hidden-knowl-wrapper .

May take me a while.

**Comment by rbeezer** [comment]
On 09/25/2017 12:10 PM, David W. Farmer wrote:
>
> I need to rework all of that, because the CSS was assuming
> the surrounding div.hidden-knowl-wrapper .
>
> May take me a while.

OK, thanks.  I wasn't certain how much you had put in place.  Let me know if you 
want more than that one page.

**Comment by rbeezer** [comment]
I'm not finding `kohere` nor `hidden-knowl-wrapper` in current output, and this is 9 months old, and I think we've moved on.  So i am closing this, but it can be re-opened if necessary.
