### ISSUE TITLE
Files not really needed for WeBWorK

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#737]
Each WeBWorK question, including those born in a knowl, causes many css and js
files to be requested from the server.  (The same request multiple times.)

I cannot tell if any of them are really needed (probably not, because the WW problem is in a page
that already gets our CSS and JS).

A specific file I would like to not be requested is bootstrap.css , because
it contains styling that conflicts with ours.  But if we can eliminate that, we might as well
eliminate everything.  Maybe an "encapsulated" mode the just sends the contents?

**Comment by Alex-Jordan** [comment]
Each WW problem is contained in an iframe. I do not understand how CSS and JS works within an iframe, as to who inherits what. I believe that the MathJax being used in the webwork problem is the WW server's MathJax, not the PTX-loaded MathJax. I don't know if there is a way to make the iframe use the ambient MathJax. (To people who know better what they are talking about, that may be a silly thing to say.)

With the CSS, in principle we could make a new "outputformat" that omits the css call. Again, provided that it is totally normal to have the iframe use the ambient page's styling. But certain things in WW problems would require new styling to the PTX CSS. Like the table you see after you submit answers. And it would be taking on too much to change anything with the HTML in those things in service of smoother PTX styling, so whatever classes are in play now would have to be used.

**Comment by Alex-Jordan** [comment]
This should not be an issue with the new javascript insertion of a WW problem replacing iframe embedding. (ce976030d0b) Of course, it only works with WW 2.16, which is not released yet. But maybe this issue can be closed.

**Comment by Alex-Jordan** [comment]
The way WW is handled now with static preview and javascript dynamically building the live version when requested, this is no longer an issue. I do not have permission level to close this issue.

**Comment by rbeezer** [comment]
Thaks for the clean-up.  I really gotta move this over to the organization!
