### ISSUE TITLE
See and see also in index

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#738]
In the index, it would be better if "see" and "see also" were in 'em' instead of 'i',
and if that em had a class.  I suggest class="see".

This change would allow me to fix some other spacing issues,
which can't be fixed right now because there is nothing to distinguish
the different uses of em/i.

Also, on the first line of the index in the sample article, there is no space
between the H and the see or the F and the see.

In the sample article there are a couple of entries which are "em", because
that was done in the source.  Clarification is needed for what emphasis means in
an index entry, and maybe it needs a more semantic tag.

(Issue arose in discussions with Nathan Wintersgill @nwintersgill )

**Comment by rbeezer** [comment]
Thanks, David and Nathan.

On 09/28/2017 10:22 AM, David W. Farmer wrote:
> In the index, it would be better if "see" and "see also" were in 'em' instead of
> 'i',
> and if that em had a class. I suggest class="see".

Done.

> This change would allow me to fix some other spacing issues,
> which can't be fixed right now because there is nothing to distinguish
> the different uses of em/i.
>
> Also, on the first line of the index in the sample article, there is no space
> between the H and the see or the F and the see.

I put a leading space in front of each of the cross-references after the comma 
separating the heading.  This adds the spaces you need, but *also* puts a space 
before "a" tag for the clickable items.  These are new - let me know if they 
make styling harder and I can be cleverer.

> In the sample article there are a couple of entries which are "em", because
> that was done in the source. Clarification is needed for what emphasis means in
> an index entry, and maybe it needs a more semantic tag.

"em" had no class anywhere.  Now it is  em.emphasis  everywhere.  So that needs 
styling universally.

I think the only other "em" is "em.terminology".

I didn't see gross differences in the look of the index, so I pushed these 
changes and you can experiment with the sample article index.

Holler if anything needs to change - otherwise feel free to close once satisfied.

**Comment by kcrisman** [comment]
I'm looking forward to using a robust see/seealso in the future, thanks!

**Comment by davidfarmer** [comment]
> I put a leading space in front of each of the cross-references after the comma
> separating the heading. This adds the spaces you need, but *also* puts a space
> before "a" tag for the clickable items. These are new - let me know if they
> make styling harder and I can be cleverer.

There is supposed to be extra space before that "a".  Turn it off
and you will see it doesn't look so good.  I don't think this is new.

> "em" had no class anywhere. Now it is em.emphasis everywhere. So that needs
> styling universally.

What I was asking is, *why* are *those* words emphasized in the index?

> I think the only other "em" is "em.terminology".

How about em.taxon and em.foreign ?

I have taxonomy on the brain because Nathan and I used that as our first
example of indexing the sample article.  Indexing is hard!

**Comment by rbeezer** [comment]
On 09/28/2017 05:55 PM, David W. Farmer wrote:
>> I put a leading space in front of each of the cross-references after the comma
>> separating the heading. This adds the spaces you need, but *also* puts a space
>> before "a" tag for the clickable items. These are new - let me know if they
>> make styling harder and I can be cleverer.
>
> There is supposed to be extra space before that "a". Turn it off
> and you will see it doesn't look so good. I don't think this is new.

So it is *good* as-is, right?  Just confirming.

>> "em" had no class anywhere. Now it is em.emphasis everywhere. So that needs
>> styling universally.
>
> What I was asking is, *why* are *those* words emphasized in the index?

I wanted to make sure tags on the heading carried through all the sorting and 
torture of building the index.  So they are born inside "index" and so need to 
survive into the index heading.  So I can see "em" being a bad choice in the 
context - it was just a test.  <m> needs to behave identically.

General "em" *does* neeed a class - it is silly that I've let that one go so long.

>> I think the only other "em" is "em.terminology".
>
> How about em.taxon and em.foreign ?

i.foreign, span.taxon

I think you suggested I change the latter?  Former is real old.

> I have taxonomy on the brain because Nathan and I used that as our first
> example of indexing the sample article. Indexing is hard!

Yes, I dread indexing FCLA. I have a few old ones from the original LaTeX which 
have survived.

**Comment by davidfarmer** [comment]
> > How about em.taxon and em.foreign ?
> 
> i.foreign, span.taxon
> 
> I think you suggested I change the latter? Former is real old.

Let's find all uses of b and i, and decide what
those should be.  No hurry on that.

In the same way that we are using hN so that the page makes sense
even without the CSS, maybe it should be b.terminology ?

Then the same logic says that i.foreign is okay,
and maybe it should be i.taxon ?

Let's not be hasty.  There seems to be a general principle
lurking here.

**Comment by rbeezer** [comment]
On 09/28/2017 08:20 PM, David W. Farmer wrote:
> Let's not be hasty. There seems to be a general principle
> lurking here.

I think the body (not the UI) should be reasonably faithful even if no CSS is 
applied.  Of course, this has grave implications for spaces and punctuation in 
headings.

Why do I say this?  Peter K has told me that many ePub readers are miserable 
with CSS and some *ignore it entirely*.  I have seen some of this, especially 
with headings (h1, h2, etc).

But for a conversion to ePub, I can redo certain implementations.  And I've 
modularized many repetitive things, so sometimes it is not even hard.  So we 
shouldn't feel enslaved by such a principle.

**Comment by rbeezer** [comment]
I can't quite tell what (if anything) needs to be done here.

*  `see` and `seealso` are in good shape in the XSL.  We have a bit of CSS work outstanding to allow parentheses to go to the right places (following CMOS).
*  I see in HTML output  `i.foreign`, `em.emphasis`, `dfn.terminology` which should be good.
* `span.taxon` and `span.genus`.  Should we have better elements for these?
* `span.booktitle`, `span.articletitle`  Similarly?  These are for **outside** of a formal reference/citation.

I'm going to close this.  Let's put anything new/necessary on a focused issue.
