### ISSUE TITLE
Extra span on hint in knowlified example

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#743]
If you open a knowl for an exercise with a hint/solution,
there is an extra span around the "a" knowl for that solution.

See Exercise 4.2.4.1 in the sample article.

**Comment by rbeezer** [comment]
This looks fine now, given recent work on wrapping knowls for content born hidden.  Unsure just which commit did ghat, but latest iteration is at  a16b2afe7a45679193029042035d45df28954889 or vicinity.
