### ISSUE TITLE
Enumerate multiple hint/answer/solution in LaTeX format

### ISSUE THREAD

**Issue by sepvar** [rbeezer/mathbook#747]
From discussion (point 4)  https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/pretext-support/c6feirQqC-c
Aside: in that discussion, David has a good point for changing my use that initiated this request, but I still think that the request is reasonable:

When there are multiple hints, answers, or solutions, the HTML enumerates them but the LaTeX does not.  Can we enumerate them in both HTML and LaTeX?

I think the LaTeX could be done with:
\begin{list}{Answer \arabic{mycounter}}{}
\item ...
\end{list}

**Comment by rbeezer** [comment]
Thank, Joe.  The one exception is that if there is only one "hint", say, then we don't write "Hint 1" for the HTML version.  The numbers only surface when born if more than one to disambiguate (but are used in cross-references always).

**Comment by sepvar** [comment]
This seems relevant, but I am not sure if it helpful.

While wandering in my tex output for the other issues (discussed elsewhere), I noticed that the in the statement where it referenced "Answer~1", there is a hyerlink, but in the answer, where we lose the enumeration, we also lose the hypertarget so that the hyperlink becomes parentless (if that makes sense).

For example, the tex output is (trimmed as indicated with [...]):
\begin{exploration}[Out of gas]\label{cyoa-NI}
[...]
\hypertarget{p-355}{}%
On a long road trip [...] You can think of three options. \leavevmode%
\begin{description}
\item[{Plan A}]\hypertarget{c-parkandwalk}{}\hypertarget{p-356}{}%
Pull over, [...] read \hyperlink{a-parkandwalk}{Answer~1}.%
\item[{Plan B}] [...]
\item[{Plan C}] [...]
\end{description}
%
\par\medskip\noindent%
\textbf{Answer.}\quad \hypertarget{p-359}{}%
Just as planned, [...]%
\par\medskip\noindent%
\textbf{Answer.}\quad \hypertarget{p-360}{}%
[...]%
\par\medskip\noindent%

The hyperlink{a-parkandwalk} points to a hypertarget that should be at the {p-359} location.

**Comment by rbeezer** [comment]
Hint, answer, solution should be in much better shape now in LaTeX output.  Thanks, Joe, for recognizing this one and reporting it.  Some things have been wrong here for a very long time, like `answer` of an inline exercise was being dropped in LaTeX output.

If only one of something (`hint`, say), there is no "1" printed.  There needs to be multiple of a type for numbers to be employed.

Caveat: back matter solutions are a mess for LaTeX output.  It will wait for a massive overhaul of how parts of exercises migrate there.

Three commits: c34aacc6f8f2f22c1bddd2994b5717b88a7008ea, 9fe855762af3d71fc75e17f87162229138d1fb06, 73ecd40cea7284a9293d176656dc5f9fb8d458fa

@sepvar - would you mind checking again on this whole hypertarget business?  I suspect it was a symptom of lots of missing pieces, addressed here and also on 91c6067bd8e7c4e1851dc123eecaebd87106d423.  Open a new issue if it is still present?

**Comment by sepvar** [comment]
@rbeezer 
I did a quick once-over and it seems to be ship-shape!  Thanks.
I also see the enumeration of the multiple answers; thanks!
I also see the titles in the few hints that I tested for David in the other fix.  They look great in the pdf.

Thanks bunches!
