### ISSUE TITLE
images/sageplot-updown.png missing from repository

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#75]
The image that is used in the sample article, called `images/sageplot-updown.png`, is not part of the repository. Is this an oversight, or intentional? Whenever I compile the sample article to pdf, I need to skip over the error I get from 
```
! Package pdftex.def Error: File `images/sageplot-updown.png' not found.
```

**Comment by rbeezer** [comment]
Oversight.  Sorry for the annoyance.  Fixed at  b86657be.
