### ISSUE TITLE
Create a Publisher's Guide

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#750]
From @mitchkeller , in pretext-dev:

I was going to propose this in another thread, but this seems like a concise place to do it:
We should have a separate publisher’s guide in addition to the author’s guide. All of the things related to
producing different versions (both PTX features and some common “best” practices) belong there. I think
having an author’s guide and a publisher’s guide can help cement the separation of those ideas in our minds.

**Comment by rbeezer** [comment]
Initiated at 27bf0176d9f9e404468f64a5ef2146175760ae98

Thanks, @davidfarmer and @mitchkeller
