### ISSUE TITLE
hint/answer not implemented in LaTeX example?

### ISSUE THREAD

**Issue by sepvar** [rbeezer/mathbook#751]
I just noticed that in my examples, the HTML makes knowls for hint/answer/solution; but the LaTeX only gets solution.  The hint/answer do not get identified in the LaTeX output.

minimal-example2 is the PTX.
minimal is the TEX output.

I can temporarily fix this by making everything a solution, but these are an example of items that are short, specific results (answers) which I am trying to distinguish from longer explanations (solutions).

[minimal-example2.txt](https://github.com/rbeezer/mathbook/files/1353441/minimal-example2.txt)
[minimal.txt](https://github.com/rbeezer/mathbook/files/1353442/minimal.txt)

**Comment by rbeezer** [comment]
Thanks, Joe.  There was a time `example` only allowed `solution`.  Once `hint` and `answer` were allowed, I guess the LaTeX conversion never got the attention it needed.

Thanks, too, for the small example.  Fix at 91c6067bd8e7c4e1851dc123eecaebd87106d423

Rob
