### ISSUE TITLE
Don't overload 'paragraphs'

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#763]
The paragraphs tag has two different meanings:

1) It is (sub)subsection-like, in the sense that it can contain things a subsection can,
it has a required title, etc.

2) It is used for something slightly related in a sidebyside, but has a more restricted content.

I think it is too much for some people to understand that the same word is being used
for different things.  Since paragraphs is already being mis-used in other ways,
it will have long-term benefits to change the name of the thing inside a sidebyside.

Some possibilities are pgroup, or pargroup, or paragraphsgroup.

**Comment by rbeezer** [comment]
**Exactly.**  The second comment on #714 is the solution I'm proposing.

Consistent reuse of elements is generally a good idea for authors (eg `title`) but if it goes too far (`paragraphs`) it is bad.  Wrestling with two (maybe three) types of `introduction` right now, which I would put right on the line between convenience and headache.

I'm going to close this based on #714, which will cross-reference this anyway.  Thanks for the confirmation.
