### ISSUE TITLE
xsltproc halts onstring replacement in "mag" element

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#771]
The EXSLT `replace()` function says it will convert its third argument to a string.  But changes at e22a0bdcf03f8f57ab457b2dc9b14a576e0bd08f that made a variable three nodes, instead of one (perhaps that is the cause) will raise an error on Windows.

Original report:  https://groups.google.com/d/topic/pretext-support/9GZFb91TiPU/discussion

```
XPath error : Invalid type
xmlXPathCompiledEval: evaluation failed
runtime error: file C:///Users/christj/Desktop/Everything/mathbook/xsl/mathbook-html.xsl line 6048 element value-of
XPath evaluation returned no result.
```

**Comment by rbeezer** [comment]
Change made at  e1dee37b8582cf8fef23ee3ae925ecce5f2e7601

**Comment by sepvar** [comment]
Checked.  Seems to work on windows.
