### ISSUE TITLE
No HTML p after pre

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#776]
After the pre showing the xsltproc commands on this page:

http://mathbook.pugetsound.edu/doc/author-guide/html/processing-parameters.html

the following text is not wrapped in an HTML p.

**Comment by rbeezer** [comment]
And neither is the text just prior. ;-)  That is a `cd` PTX element, mid-paragraph.  Entirely analogous to `md`.

I need to close the first part of the HTML paragraph, then re-open the second part.  I think it is an easy fix, just piling on to what we do with `md` and width `ol`, etc.

**Comment by rbeezer** [comment]
That falls into the "oversight" category.  Fixed at  8e4cb9068b53306b50cd225cb167da1edd5a533e  and should look good with no new work on your part.  Live now on website samples.  Good catch.

See #777 inspired by this fix.
