### ISSUE TITLE
Format issue: Objectives get inappropriate colons

### ISSUE THREAD

**Issue by sepvar** [rbeezer/mathbook#778]
I am attaching a minimal example for this issue.
[minimal-titled-objectives.txt](https://github.com/rbeezer/mathbook/files/1483518/minimal-titled-objectives.txt)

Problem 1: If I include a title in my objectives, then it displays with a space ahead of the colon
--- untitled objectives ----
Objectives
--- titled objectives ---
Objectives  : Title

Problem 2:  If I open the objectives in a knowl, then the section number is automatically included (which is cool), but the section number comes with a colon, which is added to the colon included for a title, resulting in a double colon for knowlized titled objectives
--- knowl untitled objectives ---
Objectives X.Y:
--- knowl titled objectives ---
Objectives X.Y:  : Title

**Comment by davidfarmer** [comment]
All HTML layout questions need a real (non-minimal) live online
web page showing the problem.

**Comment by sepvar** [comment]
Sorry.  I thought that'd be too messy.
I've only just added objectives to all of my sections, many don't have any detail.  Only Chapter 7 is done
and I renamed "objectives" to "student outcomes".
In particular, you can view and compare the following pages:
http://physics.thomasmore.edu/ConnectedPhysics/c-force.html
to see a titled objectives that has an extra space ahead of it.  Also, while you are on that page, click the links in the fourth objective to see that when you create a knowl of a titled objective then you get the section number with a colon as well as the extra-space-and-new-colon for the title.

The extra space does not appear in the PDF, which you can find at
http://physics.thomasmore.edu/ConnectedPhysics/Connected.pdf

I will also ask you to ignore, among other unrelated errors, the fact that I created xref in my title of my objectives.  I am aware that that is inappropriate.  I was going to fix it before posting, but since you need a live example, you get one with (unrelated) errors.

Thanks.

**Comment by davidfarmer** [comment]
Should be fixed.  Please close the issue if you agree.

And when you fix (remove) the links in the title of your
objectives, check that the appearance is still correct.
