### ISSUE TITLE
Two levels in TOC by default

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#780]
Set the default depth in the TOC to show two levels.

I just pulled and built the sample article, and there are no subsections shown in the nav bar on the left.

**Comment by rbeezer** [comment]
Sorry, I **have** been meaning to do this for a while.  Ever since you said "please" three times.  That always works. ;-)

At 68118b233aebdb3ba46972ea3ec1c6945816256e, but no updates to website yet (it is two-deep now anyway).  Did you figure out you could set a switch to make this happen anyway?

**Comment by davidfarmer** [comment]
I knew there was a switch for that, but chose not to figure
out how to use it :)

**Comment by rbeezer** [comment]
Yes, I know your style. ;-)
