### ISSUE TITLE
Option for spacing around an em dash

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#783]
Make a publisher option for a thin space, or a full space, surrounding an em dash.  This should be a publisher option, so a command-line string parameter.  Documentation should advise no extra space in source, maybe XSL could remove any that exists in adjacent text nodes.

Default is no space, options could go
```
emdash.space  none|thin|full
```

Option should be an easy XSL exercise, stripping adjacent space is hard and could wait.

**Comment by kcrisman** [comment]
Make a publisher option for a thin space, or a full space, surrounding an
> em dash. This should be a publisher option, so a command-line string
> parameter. Documentation should advise no extra space in source, maybe XSL
> could remove any that exists in adjacent text nodes.
>
> Default is no space, options could go
>
> emdash.space  none|thin|full
>
>
> Should html have a space?  Fernando G. recommends it for MAA Reviews
because it looks different.

**Comment by daverosoff** [comment]
Are you sure about this, Rob? I learned that if spaces surround the dash, it should be an *en* dash rather than an em dash. Em dashes are flush with surrounding text.

**Comment by davidfarmer** [comment]
There is a difference between a full space -- as in this sentence,
and a little tiny bit of thin space, which some typographic styles use.
(And which I can't replicate in ascii.)

**Comment by rbeezer** [comment]
Implemented, with comments, on PR #821.  A full-space option could be added later if there is a real hue and cry.
