### ISSUE TITLE
Omit header around section titles

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#786]
Let's omit the "header" wrapping the hN.heading for the titles of sections and subsections,
and also the chapter title on the chapter pages of a book.

I am not sure if I made all the necessary CSS changes, but if not, I am close.
So, a temporary version of the sample article and sample book would be
helpful but not necessary if inconvenient.

The 
    header id="masthead"
at the top can stay.

Is there some type of header for lists (which I seemed to see in the XSLT,
starting line 993)?
If so, please let me know an example so I can see if it should be eliminated.

I will submit a pull request to make this change.

This is part of issue #741

**Comment by rbeezer** [comment]
Fixed at #787, but see also #788
