### ISSUE TITLE
Update "list-of" headings in HTML conversion

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#788]
These should look more like what is produced by the modal `section-header` template which has been evolving.  Even better would be to recycle as much as possible directly.

**Comment by rbeezer** [comment]
First pass might be eliminating `header` element at current line 984.

Sample use is "List of Results" in sample article:
http://mathbook.pugetsound.edu/examples/sample-article/html/appendix-results.html

**Comment by davidfarmer** [comment]
Looks okay to me.

**Comment by rbeezer** [comment]
Looks fine to me, too.

I just thought it was a place to remove superfluous HTML and be consistent with use elsewhere.

Go ahead and close this if you don't think it is worth the trouble.

**Comment by davidfarmer** [comment]
I was confused.  I thought you *had* removed the header.  I'll remove it,
build the sample article, and submit a pull request if it looks okay.

**Comment by rbeezer** [comment]
OK, back on the same page. ;-)

**Comment by rbeezer** [comment]
Last bit on #792, so we're done.
