### ISSUE TITLE
heading vs. type in captions

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#789]
The structure of an html section heading is

.heading
    .type
    .codenumber
    .title

The structure of a caption is

.figcaption
    .heading
    .codenumber

I'd like these to be more parallel: use .type instead of .heading inside of .figcaption 

There would be CSS consequences, but I can make those changes quickly and
so do not need a sample before deployment.

**Comment by rbeezer** [comment]
I'll make the change now.  Stay tuned.

**Comment by rbeezer** [comment]
Done, and live in website samples.

One case to discuss.  A sidebyside inside a figure gets usual caption, say Figure 5.12.

If the panels of the sidebyside have captions (figures, tables, listings, named lists), then they are "subcaptioned", so we might have a "Table" that is numbered 5.12(b).

The type ("Table") is not present now (no `.heading`), and the `codenumber` is just `b` (or maybe `(b)`).  Visually, the caption reads  "(b) Some data"  (or similar) -- no "Table", no 5.12.

Do you want the "type" information, even though it will not be shown in current rendering?  (We use "hide-type" elsewhere, but maybe this should be a styling decision?)

**Comment by davidfarmer** [comment]
Is there an example in the sample article?

**Comment by rbeezer** [comment]
Sorry, meant to include such a  thing.  Figure 22.2 is a good first example.

http://mathbook.pugetsound.edu/examples/sample-article/html/section-side-by-side.html

**Comment by davidfarmer** [comment]
I think those are okay now, but please check.

**Comment by rbeezer** [comment]
Looking good - and I cruised lots of other captions (tabled, figures, etc).  Looking real nice.

Keep 'em coming.

For the record: change at 14edebfa719fce9ba83ef02ca7d70d819eeee4b0
