### ISSUE TITLE
line height in lists

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#791]
At http://mathbook.pugetsound.edu/examples/webwork/sample-chapter/html/section-1.html, in the intro to Exercise 1.4, there is a `ul`. Note this is the WW sample chapter, but the list I'm referring to is not in a webwork.

If you look very closely (at least in Firefox 57.0.1) the bottom of the upper lines in each item is cut off. Things like the tails of y's and g's. Not on the last line of a paragraph.

As suggested in #221, turning off `inline` on the `p`s here is one way to make the issue go away.

**Comment by davidfarmer** [comment]
I thnk this is fixed, and we also can close #221.

**Comment by Alex-Jordan** [comment]
It looks like David fixed this long ago.
