### ISSUE TITLE
"Skip to Main Content" ineffective

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#794]
This has been "not working" since at least mid-November (during talk at UBC).  Experimenting with Firefox and Chrome at:

http://mathbook.pugetsound.edu/examples/sample-book/html/section-sets-and-equivalence-relations.html

Tab brings up "Skip to main content" slide-in, source points to `#content`, which exists and is in the right place.

But hover and click go to the top-level of the book.

**Comment by davidfarmer** [comment]
The intended use case is for people who are doing keyboard navigation:

    hit 'tab' to bring up the "Skip to main content" link

    hit 'return' to go to the main content

It still works like that.

It seems like a odd use case to hit 'tab' and then switch to
using the mouse.  Please elaborate if there is a genuine use case
for that.

Maybe there is an easy way to also let that link be clicked with
the mouse, but if not, I think the current behavior is adequate.

**Comment by rbeezer** [comment]
Right!  ;-)  I first hit this during a demo, and then didn't get that drill out of my head.  Sorry for the noise.
