### ISSUE TITLE
Comprehensive test/sample pages

### ISSUE THREAD

**Issue by mxdubois** [rbeezer/mathbook#8]
I've brought this up in a couple of email chains, but I'm going to make an issue for it, so it doesn't get lost in the shuffle. 

I think some comprehensive test pages would make it a lot easier to ensure styling and markup is working as intended across all features. They'd also double as great examples for prospective authors.

We need...
 * A page for each supported layout
    * has-sidebar-left, has-sidebar-right (?), both (?), neither
 * A page for each level of chunking that contains all the environments/features allowed in that chunk
    * whatever subsections make sense
    * minimal [lorem ipsum](http://www.lipsum.com/) text
    * theorem-like, example-like, exercise-like, proof-like, etc.
    * knowls
    * code block, code inline, sagecells
    * tables
    * figures (with and without caption)
    * images
    * blockquotes
    * author information, summary-links, terminology, references, etc
    * Mathjax displays (short and wide)
    * any special cases where something weird happens when one element comes after another (we can add these as they come up).
 * Instructions in the README for generating them all.

[Here's an example from a premium wordpress theme](http://organique.demo.proteusthemes.com/elements/). It's not exactly like what we need, but it gives you an idea of how this could be extremely useful both as a test page and a demo. 

[Here's another example](http://themeforest.net/item/oldpaper-ultimate-magazine-blog-theme/full_screen_preview/7431822) that also displays the code for generating each item right above the item. Something like that might make it a handy guide for authors.

**Comment by rbeezer** [comment]
I've borrowed the first three chapters of Judson's abstract algebra text and fashioned a sample book from that.  At 3a0a038f

There is also a very, very minimal "Hello, World" example now at 35173579

I will close this now, though these will continue to improve.  There are enough ongoing projects out there now that can also provide examples.
