### ISSUE TITLE
jing-trang appendix list looks weird

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#807]
See any live version of mathbook/doc/author-guide/schema-install.xml such as http://mathbook.pugetsound.edu/doc/author-guide/html/jing-trang.html 

The list parts with `JAVA_HOME` and so forth are not aligned properly.

**Comment by davidfarmer** [comment]
Fixed (assuming the only problem was the first line
of the term lining up with the first line of the definition).

**Comment by kcrisman** [comment]
Commit?

**Comment by davidfarmer** [comment]
It is a CSS change, already live.  Reload to see it.

**Comment by kcrisman** [comment]
Got it

**Comment by kcrisman** [comment]
No, upon further review I think we are talking about two different things.  I would call this a coding error or something.  After "Installation notes for jing and trang follow." we get a `<dl>` or something, but in the middle of it are _numbered_ items, and the numbers are not aligned - with each other or the items.  So in a definition list I get it, but that is not the right tool here.  If I am understanding the intent of these steps properly.

**Comment by davidfarmer** [comment]
The numbers should not be there, and I have already
submitted a pull request deleting them.

**Comment by kcrisman** [comment]
Well, in some sense they should be there, "observing the following notes keyed to the four steps" and then they are numbered as in the readme file.  Some better (perhaps two-level) formatting is necessary, I think.  But that can be discussed at #808 where you did it, so I'll close this.

**Comment by rbeezer** [comment]
See a607798c3023b8f7dca711902db42af81af49fd1
