### ISSUE TITLE
give exact command in jing-trang

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#812]
In http://mathbook.pugetsound.edu/doc/author-guide/html/jing-trang.html Installation notes for jing and trang follow.  But they don't: please give _exact_ syntax for cloning a random github repo, such as `git clone https://github.com/relaxng/jing-trang`.  (Perhaps also suggest a place to do it, i.e. probably not in your `mathbook` directory.)

**Comment by rbeezer** [comment]
This has been addressed at a607798c3023b8f7dca711902db42af81af49fd1

Thanks!
