### ISSUE TITLE
Extra space in type-global with content

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#813]
At the end of the 2nd row of Table 6.4.1,
https://mathbook.pugetsound.edu/doc/author-guide/html/topic-cross-referencing.html
you can see a space after the word "Extra".  It should not be there.

The space is not in the xml source.

**Comment by rbeezer** [comment]
I think it is waiting for a number!

And will then be useful.  ;-)

**Comment by rbeezer** [comment]
The space is now significant, the number following it was missing.  See f30b1655775b6b8d9e69a672a011902b96684014

Thanks for the catch, all the same.
