### ISSUE TITLE
Author's Guide: warn against <m> inside \text{}

### ISSUE THREAD

**Issue by daverosoff** [rbeezer/mathbook#815]
In LaTeX it's fairly natural to do something like this:

```
\begin{equation*}
    \zeta(s) = \sum_{n=1} \frac{a_n}{n^s}  \quad \text{(converges for $\Re{s}$ large enough)}
\end{equation*}
```

Leaving aside the discussion of whether it's the best writing style, this sort of thing is fairly common and perfectly legitimate LaTeX. However, `<m>` inside `\text{...}` inside `<mrow>`, e.g., is not legitimate. 

Please warn authors against this construction and advise an alternative in the Author's Guide. I'm not sure what the best alternative is.

**Comment by rbeezer** [comment]
Thanks, Dave, for the report.

Does the existing Subsection 6.6.5 do an adequate job?

https://mathbook.pugetsound.edu/doc/author-guide/html/topic-mathematics.html

Validating one's source against the schema should produce the desired warning.  Does it?

Thanks,
Rob

**Comment by Alex-Jordan** [comment]
I've never had an issue from doing like:
```
<me>\zeta(s)=\sum_{n=1}\frac{a_n}{n^s}\quad\text{(converges for $\Re{s}$ large enough)}</me>
```
However I recall Rob and David F leaning toward 
```
<me>\zeta(s)=\sum_{n=1}\frac{a_n}{n^s}\quad\text{(converges for }\Re{s}\text{ large enough)}</me>
```
as preferable. 

The existing section has an example of math-text-math within a math environment. But I think it would benefit from an example like Dave R has here, where there is math logically nested inside text. It could either keep that logical nesting with dollar signs, or if that is determined to be bad, it could break the logical nesting and use two `\text{}`s.

**Comment by daverosoff** [comment]
I'm sorry, I should have noted that I did read and think about the existing 6.6.5 before opening the issue here. Alex has anticipated my thinking, that I believe it would be appropriate for the AG to suggest which alternative is preferred PreTeXt style: end the `text` command and begin another, or embed inline math `$...$` within `text`.

**Comment by rbeezer** [comment]
Dollar signs used like this will likely break a situation like Jupyter notebooks or CoCalc that control their own MathJax configuration.

**Comment by davidfarmer** [comment]
Both of Alex's version work, and look pretty much the same.  A while ago, MathJax would
not handle math inside text inside math.  But just because it handles it now, does not mean
that we should allow that to appear in the HTML.  Especially if it is a problem in Jupyter or
other places.

But note my careful wording: not in the HTML.  It is not obvious to me that it is bad PTX to
put a small amount of math inside \text{}.

And if we can detect and warn against that, can't we also just do the right thing
so it works in the chosen output format?

**Comment by rbeezer** [comment]
The original post was about the "m" element.  The schema can detect that it is employed **anywhere** in an "mrow" and thus is a violation.  The schema will **never** detect that an "m" is only employed in a `\text{}`.

I think it will be very dangerous to suggest the use of dollar signs for math **anywhere**.  I've been encouraged to look at KaTeX, and even with the most preliminary review it is clear that the less we assume about certain behaviors, the more adaptable we will be.

The relevant documentation says:

> Do not place any mathematics inside the `\text{}` macro

I will add a more explicit example on some future pass through issues tagged with `documentation`.

Thanks, Dave, for bringing this one up.

**Comment by davidfarmer** [comment]
Let's think a bit more expansively.

PTX *could have* been set up to use < text >...< /text > instead
of \text{...} inside < me >.  That can even become the official way to do
the markup, especially once we have the preprocessor that can
convert the LaTeX-like syntax to XML syntax.

Then it would be possible to allow < m > inside < text > inside < me >.
And it would be possible to convert it to whatever appropriate markup
is needed for the chosen output format.  (And even if that does not
become the official PTX way to do that markup, an evil (or merely
mischievous) person could add that feature to the preprocessor,
and so authors can do it however they want).

To repeat the point of my previous posting:  let's not give too much
weight to the limitations of certain output formats.  What *should* the
proper semantic markup look like?  I don't see why a first-principles
view would ban < m > inside < text > inside < me >.

ps.  I already am using code that detects inline math inside \text inside
display math, and splits the \text apart appropriately.

**Comment by rbeezer** [comment]
Yes, that approach was part of my consideration of this one.

Could you put the possibility of `mrow/text` and `mrow/text/m` (and similar for `me`) onto a new issue?  This one has drifted away from a documentation issue.  You can point back here for some of the discussion.  Thanks.

**Comment by rbeezer** [comment]
With another look at the current

https://pretextbook.org/doc/author-guide/html/topic-mathematics.html

I think the current practices are adequately addressed.  #816 can be used as a place to discuss/implement alternate approaches.  So as a documentation issue, I'm closing this one.
