### ISSUE TITLE
dfn tag for terminology

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#819]
Since HTML has a dfn tag that is specifically for indicating a word is
being defined, we should use it.

If b.terminology is changed to dfn.terminology then everything should look the same.

**Comment by rbeezer** [comment]
Good catch.  I had not seen that one before.  The more of these we can do, the better for screen readers and CSS-hostile environments, like EPUB.

Implemented at 058d95e7f16d675f6000ee2da117f79ec44e949d, limited testing, live on website versions.
