### ISSUE TITLE
autoname="no" leading to inaccurate numbering

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#82]
When I have references that should end up like *Exercises 1.1.3--1.1.6*, I use `autoname="plural"` for the first and `autoname="no"` for the second. I'm finding that often, the second number in the LaTeX version ends up being something like say 1.1.10 instead. It still hyperlinks to 1.1.6, but is just labeled wrong. I haven't seen this behavior except when `autoname="no"`, and I haven't noticed it in the HTML output.

**Comment by rbeezer** [comment]
Thanks for the careful reports (here and at #83).  Soon I will get my head back 
into numbering and see what is going on here with these.

Rob

**Comment by rbeezer** [comment]
An `exercise` inside of `exercises` (directly, or in an `exercisegroup`) was only partially plugged in to the autonaming scheme.  That has been corrected at 11b56b50.  See sample at the end of "Cross-Referencing" chapter.

I cannot duplicate your numbering error.  Are these exercises in the narrative or in the exercise sections - they behave differently?  I was not even getting the "Exercise" string before I started this current change, which makes me think it was in the narrative.

Can you look at the labels in the LaTeX output to see if you can identify the problem (mine or yours)?  Or, can you embed a MWE into the sample article and post it here?   (Just as a comment is fine, I can move it.)

**Comment by Alex-Jordan** [comment]
I'm actually only seeing the issue now with references to Tables and Figures. I may have mistakenly assumed it occurred for references to Exercises. I'll make a MWE and post here when I get a chance.

**Comment by Alex-Jordan** [comment]
I've tracked this down to my own customization layer. I had something in there fiddling with the ref-id mode template to try to reduce the verbosity of exercise references. It inadvertently caused this issue. Sorry!

**Comment by rbeezer** [comment]
OK, thanks for the update.  I'll be starting back into cross-references today, so be sure to double-check your custoimizations once I announce those changes (which all may be totally transparent, I hope).
