### ISSUE TITLE
Unused file

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#838]
The file source-formatting.xml in the author-guide does not seem to be used.

That is bad because when you grep for something, you can find it in that file
and then not notice it isn't what you really want.

I will delete that file in an upcoming pull request and am making this issue as
a reminder, just in case there was some reason to keep the file.

And also as a suggestion to delete other unused files.

**Comment by rbeezer** [comment]
And `introduction.xml`, too.  Should have been deleted as part of bb75afed9645accf0b79cf1bb15f1008868024bc from about two years ago.

I took care of both of them, since I was in the neighborhood.  Thanks for the report.
