### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#84]
A student just said that the online version of a MBX book would be even MORE awesome if you could just type something in a search bar and not have to page through for finding a term/definition/whatever.  I concur!

**Comment by rbeezer** [comment]
Yes, definitely!

For the record, we put a lot of work into experimenting with Google Search on 
books, but the knowls totally confuse Google's bots and the output was worthless 
(too much extraneous clutter).

But we can now embed knowl content onto pages, so that may solve the problem.

**Comment by kcrisman** [comment]
See also #96 for something closely related.

**Comment by rbeezer** [comment]
Implemented at f59d1bae

**Comment by kcrisman** [comment]
Awesome!  I was definitely not expecting this so soon - will read the other additions to documentation about it this morning.
