### ISSUE TITLE
paragraphs section in author guide

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#851]
It would be more friendly to new users, and probably better for everyone,
if the long subsection on characters was moved to the end of the section.

**Comment by rbeezer** [comment]
Even better - once moved, the second section, on simple grouping (like quotes and emphasis) is **way more instructive**.

Move made at:  be8f13fde497fe0038a38473ca2e95ce57f21658

Thanks for the review and suggestion.
