### ISSUE TITLE
Allow tasks inside exercises (and examples)

### ISSUE THREAD

**Issue by oscarlevin** [rbeezer/mathbook#864]
Tasks are used to break up project-like elements currently, allowing for hint/answer/solution to be tied to these parts of the project.  It would be nice to have a similar feature for exercises.  Examples could also use this.  The benefit: students can check their work on one part without spoilers for the subsequent parts.

This has been discussed on the old mathbook groups, but I don't think it every made it into an issue.  Any chance this is likely by August?

**Comment by Alex-Jordan** [comment]
I believe this is done now. (Except if the exercise is webwork.) If you agree, would you like to close this and open a WW-specific issue?

**Comment by rbeezer** [comment]
`exercise` at bddee227849a0c596194e0a19763c784776cdaef

`EXAMPLE-LIKE` AT 4048804909ea5d1130db2f830245e2239d26d990

Only about two years later than desired.  Sorry about the slow pace.
