### ISSUE TITLE
Validation of minimal example

### ISSUE THREAD

**Issue by nyraghu** [rbeezer/mathbook#868]
I am getting an error when trying to validate the minimal example.

``` bash
$ jing schema/pretext.rng examples/minimal/minimal.xml 
/home/raghu/Downloads/mathbook/examples/minimal/minimal.xml:70:23: error: element "introduction" not allowed here; expected element "section"
$ git rev-parse HEAD
a4041adfe0d02b4745130ac833543180880d8e8d
```
Is the `article` element allowed to have an `introduction` child?

**Comment by davidfarmer** [comment]
According to GitHub, the minimal example is 10 months old.

So this is probably just an oversight of updating when things change.
(Validating the examples as part of testing new code could be
automated.  Probably "should", but I don't know how to do that.)

**Comment by nyraghu** [comment]
> Validating the examples as part of testing new code could be automated. Probably "should", but I don't know how to do that

You can use Travis CI to automatically validate and transform some test documents whenever a commit is pushed, or a pull request is made, to your GitHub repo.

**Comment by rbeezer** [comment]
Thanks, Raghu.  The sample article is often in front of the schema, while the sample book usually validates and it should also be the case for the minimal article.  I saw recently that the schema for "article" needs some work, so I'll get this sorted then.

I've used Travis CI but for now I prefer to do this locally with a script I run for every major push.

**Comment by rbeezer** [comment]
I've added `introduction` to the schema, so the minimal article now validates fully.  I made some other improvements to allow a minimally structured (short-form) article that is basically just a run of `p` paragraphs, and similar, plus `paragraphs` for lightweight sectioning.

At 8899560f39a586e9b829f7288f4e4656038c89a6

Thanks again for taking the time to report this!
