### ISSUE TITLE
webwork title and idx

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#873]
The schema says a `webwork` can have a `title` and `idx` children. I no longer see a need for either. We could remove from the schema and patrol the style sheets to confirm they do not employ these.

**Comment by rbeezer** [comment]
Working on this one, and likely too hard to patrol just which `title` and `idx` might be in play.  So I made one of each in the sample chapter, with distinctive content, and then grep'ed for that.

* Both came through in the `authored` version in the extraction file.  No surprise there.
* The `title` came through in the `static` version in teh extraction file.  Maybe that suggests removing some code from the WW server?

Nothing in HTML, PDF, or problem sets.  So in any event, a reader will never see it.  So I think we are good.

**Comment by Alex-Jordan** [comment]
#1214 addressed this.
