### ISSUE TITLE
Description list item xref knowls

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#881]
If you xref an item from a description list, the knowl's header is like "Item Title-of-item". I think it would be better to just be "Title-of-item".

**Comment by rbeezer** [comment]
Right.  Thanks.

Fixed now and live.  Search the sample article section on "Cross-Referencing" for `in a description` to see an example.

Change at 0274f9faf5e2e541a76aa2c975225191d9fa032b

**Comment by rbeezer** [comment]
Went a bit too far on this one.  Fixed at 84b79e110924568ee4292416041552603eed4bef
