### ISSUE TITLE
knowl and refid attributes

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#891]
knowl and refid attributes are attributes that were just invented to help with knowl javascript. To pass HTML5 validation, they need to be changed to something like data-knowl and data-refid.

**Comment by rbeezer** [comment]
I've got validator errors and warnings down to about 800.  Roughly half of those would go away with the proposed change.

**Comment by rbeezer** [comment]
Javascript was changed to implement this, work at #997 and f4003302c4a7e5265f292a8bf1774b0d551753d0.  Validator errors are down to about 200.
