### ISSUE TITLE
Dedication doesn't appear in pdf

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#90]
Also, searching the .tex source reveals no word like 'dedication', so it seems completely ignored by that script.   But I do have `dedication-1.html`, so it's not like it's completely ignored.

**Comment by kcrisman** [comment]
line 1029, in fact, now reads

    

I note that foreword isn't handled there either.

**Comment by rbeezer** [comment]
Right - I just noticed that as I fixed preface titles.  About to tackle dedication.

I think foreword can be easily plugged-in as well.

**Comment by rbeezer** [comment]
Foreword enabled at  a510bea5

Continuing to make progress on front matter...

**Comment by rbeezer** [comment]
Dedications are now fully enabled for LaTeX and HTML at:  a4cd56c2

The HTML output is legible, but still needs CSS to match the realization in the PDF.  It'll catch up eventually.
