### ISSUE TITLE
Exercise number incorrectly appears in backmatter

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#903]
When attempting to only put exercise answers in backmatter for LaTeX, an exercise that has a hint or solution but no answer in the PTX source has its number output in the LaTeX code.

**Comment by mitchkeller** [comment]
After some further testing, this bug also rears its head in HTML production.

**Comment by rbeezer** [comment]
This production has been totally revamped the past few months (in the vicinity of 435bb0ea114c3c8ce573645f429f147c3d004a78), and I've not seen any problems of this magnitude.   Feel free to re-open if I'm mistaken.
