### ISSUE TITLE
project-like, example-like beginning with sidebyside

### ISSUE THREAD

**Issue by mitchkeller** [rbeezer/mathbook#922]
When a project-like or example-like (and probably other things) begins with a sidebyside, the LaTeX result is bad. Specifically, the sidebyside is put before the "Example 1.2.3" or "Activity 2.3.4" line of text.

**Comment by rbeezer** [comment]
I'm guessing this is another situation where "\leavevmode" is necessary.  We've 
had to do that with lists and tables.

I'll investigate in a bit.  Though I wish I was more of a TeXnician and 
understood this better.

Rob

**Comment by Alex-Jordan** [comment]
> I'm guessing this is another situation where "\leavevmode" is necessary.

Bingo. I have been sedding in such leavevmodes in my production script for ORCCA, as needed these past few weeks. Sorry for not reporting.

**Comment by rbeezer** [comment]
On 07/22/2018 05:41 PM, Alex Jordan wrote:
> Bingo.

Thanks for confirmation.  Just in front of "sidebyside" and after a division 
heading?

> I have been sedding in such leavevmodes in my production script for 
> ORCCA, as needed these past few weeks. Sorry for not reporting.

Do I need to assign penance now?  ;-)

**Comment by rbeezer** [comment]
Dear Mitch,

(A) A non-trivial example I tried did not produce a bad result.  Can you 
post/send an example I can use?  I hope this isn't like last time.  ;-)

(B) Ideally a \leavevmode could go into the "sidebyside" latex environment 
definition and always be there.  But a "sbsgroup" has the simplest possible 
implementation - it is just a sequence of "sidebyside", and the \leavevmode 
produces very conspicuous extra vertical space between each row.

Solutions to (B):

1.  Refactor "sbsgroup".  One-day minimum, and likely another LaTeX 
page-breaking conundrum.  That sort of time is suddenly not available to me.

2.  Insert \leavevmode into body where first item of a division is a 
"sidebyside" or "sbsgroup".  Not so clean, but we are doing that already elsewhere.

Rob

**Comment by rbeezer** [comment]
This should be fixed now, and for `sbsgroup`.  Code in e06d138dd471ed20b598869561cedbc8b5e4c601 and testing in 085798b018958c66192c269c946549b2d68199d6.

Confirmation of the fix for your case would be appreciated.  Thanks for the report and for waiting.

**Comment by mitchkeller** [comment]
The test case I submitted works as intended now. We didn't wind up needing this construct in Active Calculus, so I don't have anything larger than that to test on. Maybe @Alex-Jordan has something live in one of his projects to give it another test?

**Comment by rbeezer** [comment]
Thanks for the confirmation.
