### ISSUE TITLE
Authors of chapters, or other subdivisions

### ISSUE THREAD

**Issue by rbeezer** [rbeezer/mathbook#93]
An `<author>` may be placed on a `<chapter>`, `<section>`, or other subdivision.  It is marginally formatted in the HTML, and simply bleeds through to the PDF.  So this needs some work.  It will of course, be totally necessary for a `<foreword>` that would have an author other than the main author.

**Comment by kcrisman** [comment]
:+1:

**Comment by kisonecat** [comment]
I also need this for a multiauthor volume (where I'd be targetting print and epub).

**Comment by rbeezer** [comment]
Fixed at 730866290195881fb8aab8588da67bb3e0bc96e9 and see some explanation at  https://groups.google.com/d/topic/pretext-dev/3Ax46W-kWhw/discussion
