### ISSUE TITLE
LaTeX message for missing xref in mrow

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#939]
When you have an xref in an mrow, and the target is missing (say, because you have commented out a large chuck of your book) it is a problem, because the "Unresolved xref" message is surrounded by `$\langle\langle$` and `$\rangle\rangle$`. The dollar signs within a math environment break compilation.

Stepping back, it seems like some sort of abuse to use math mode to get the angle brackets around text, even outside of the mrow xref. Could something else be done in general? If not, then for the mrow xref case, wrapping it all in `\text{}` might work without much fuss.

**Comment by rbeezer** [comment]
Fixed.  Went with triple parentheses.  Renders poorly in  `mrow/xref` case, but does not halt LaTeX compilation.

This really belongs in Schematron rules (only), but it seems an uphill battle to get folks to validate.

At c3ff47ea0b42a48b3f6993eb1b613ff155abc12f once I push later tonight.  Thanks for reporting this one - that was **very old** code.
