### ISSUE TITLE
Indentation in exercisegroup with title in PDF

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#946]
When an exercisegroup has a title, the first row of exercises (or first exercise if there is only one column) is not indented the same as those that follow. See http://spot.pcc.edu/~ajordan/temp/orcca.pdf, which as of 8/25/18 is made with unadulterated PTX and no post-processing. Page 20 has the first example. Unsure what happens if this exercisegroup has a title _and_ an introduction.

**Comment by rbeezer** [comment]
What happens if you put an "introduction" (with substance) between the "title" 
and the first "exercise" of the group?

**Comment by rbeezer** [comment]
OK, that helps.  Better, I guess.

(a) Exercises need consolidation.  Four types should become two.  A semi-major 
refactor.

(b) We need a lightweight division for "exercises"  (I don't like the name 
"exercisesdivision"!), which seems to be what you are doing with lots of these 
groups (when not in columns).

**Comment by Alex-Jordan** [comment]
subexercises?

**Comment by rbeezer** [comment]
Better!

**Comment by rbeezer** [comment]
This should be improved in response to the main deficiency of the report, plus some other improvements in the vicinity.  Mostly indentation and vertical spacing.  Plus titles, of course.

At  fa6125c9943d44b24a0152ee65921ce5264c8e71

@Alex-Jordan: would you be able to survey ORCAA?  With a super-critical eye?  Look for stray 1-character indentations, and the like?  You have way more combinations than the sample article ever will.  Thanks.

**Comment by Alex-Jordan** [comment]
I built one chapter of ORCCA with this and unadulterated PTX, which you can temporarily see at:
http://spot.pcc.edu/~ajordan/temp/orcca.pdf

The indentation issue is fixed, thank you.

Something is off with vertical alignment in certain "rows" of an exercisegroup. Take a look at page 21, exercises 29, 30, 31. [I know it's too cramped there for three columns, but in the production run we used narrower margins.] You can see the same (or similar) thing happening more places on that page.

**Comment by rbeezer** [comment]
On 08/28/2018 04:17 PM, Alex Jordan wrote:
> Something is off with vertical alignment in certain "rows" of an exercisegroup. 
> Take a look at page 21, exercises 29, 30, 31. [I know it's too cramped there for 
> three columns, but in the production run we used narrower margins.] You can see 
> the same (or similar) thing happening more places on that page.

Can you put the source for that entire "exercisegroup" here as an attachment? 
I'll generate, and play with, the LaTeX to see what the cause is.

Always the final "column", no?

Thanks,
Rob

**Comment by Alex-Jordan** [comment]
Not always the final column. Look at page 21, numbers 38, 39. I don't see a way to post an attachment, so here is the thing pasted:

```
\textbf{Multiplying/Dividing Fractions}\space\space\hypertarget{exercisegroup-13}{}%
\begin{exercisegroup}{3}
\begin{egexercise}{17}\hypertarget{exercise-88}{}
\hypertarget{p-1269}{}%
Multiply: \(\displaystyle{ \frac{1}{7} \cdot \frac{3}{8} }\)%
\end{egexercise}%
\begin{egexercise}{18}\hypertarget{exercise-89}{}
\hypertarget{p-1274}{}%
Multiply: \(\displaystyle{ \frac{3}{7} \cdot \frac{3}{8} }\)%
\end{egexercise}%
\begin{egexercise}{19}\hypertarget{exercise-90}{}
\hypertarget{p-1279}{}%
Multiply: \(\displaystyle{ \frac{6}{11} \cdot \frac{13}{6} }\)%
\end{egexercise}%
\begin{egexercise}{20}\hypertarget{exercise-91}{}
\hypertarget{p-1285}{}%
Multiply: \(\displaystyle{ \frac{7}{11} \cdot \frac{3}{14} }\)%
\end{egexercise}%
\begin{egexercise}{21}\hypertarget{exercise-92}{}
\hypertarget{p-1291}{}%
Multiply: \(\displaystyle{3\cdot \frac{3}{10} }\)%
\end{egexercise}%
\begin{egexercise}{22}\hypertarget{exercise-93}{}
\hypertarget{p-1298}{}%
Multiply: \(\displaystyle{6\cdot \frac{4}{5} }\)%
\end{egexercise}%
\begin{egexercise}{23}\hypertarget{exercise-94}{}
\hypertarget{p-1305}{}%
Multiply: \(\displaystyle{-\frac{20}{7} \cdot \frac{7}{25}}\)%
\end{egexercise}%
\begin{egexercise}{24}\hypertarget{exercise-95}{}
\hypertarget{p-1311}{}%
Multiply: \(\displaystyle{-\frac{18}{5} \cdot \frac{13}{28}}\)%
\end{egexercise}%
\begin{egexercise}{25}\hypertarget{exercise-96}{}
\hypertarget{p-1317}{}%
Multiply: \(\displaystyle{28\cdot\left( -{\frac{9}{7}} \right)}\)%
\end{egexercise}%
\begin{egexercise}{26}\hypertarget{exercise-97}{}
\hypertarget{p-1323}{}%
Multiply: \(\displaystyle{6\cdot\left( -{\frac{1}{3}} \right)}\)%
\end{egexercise}%
\begin{egexercise}{27}\hypertarget{exercise-98}{}
\hypertarget{p-1329}{}%
Multiply: \(\displaystyle{ {{\frac{7}{4}}} \cdot {{\frac{5}{49}}} \cdot {{\frac{6}{25}}} }\)%
\end{egexercise}%
\begin{egexercise}{28}\hypertarget{exercise-99}{}
\hypertarget{p-1334}{}%
Multiply: \(\displaystyle{ {{\frac{5}{9}}} \cdot {{\frac{14}{25}}} \cdot {{\frac{3}{4}}} }\)%
\end{egexercise}%
\begin{egexercise}{29}\hypertarget{exercise-100}{}
\hypertarget{p-1339}{}%
Multiply: \(\displaystyle{ {{\frac{14}{3}}} \cdot {{\frac{1}{4}}} \cdot {15} }\)%
\end{egexercise}%
\begin{egexercise}{30}\hypertarget{exercise-101}{}
\hypertarget{p-1345}{}%
Multiply: \(\displaystyle{ {{\frac{7}{5}}} \cdot {{\frac{2}{49}}} \cdot {15} }\)%
\end{egexercise}%
\begin{egexercise}{31}\hypertarget{exercise-102}{}
\hypertarget{p-1351}{}%
Divide: \(\displaystyle{ \frac{3}{7} \div \frac{7}{4} }\)%
\end{egexercise}%
\begin{egexercise}{32}\hypertarget{exercise-103}{}
\hypertarget{p-1359}{}%
Divide: \(\displaystyle{ \frac{4}{5} \div \frac{7}{4} }\)%
\end{egexercise}%
\begin{egexercise}{33}\hypertarget{exercise-104}{}
\hypertarget{p-1367}{}%
Divide: \(\displaystyle{ \frac{7}{10} \div \left(-\frac{5}{4}\right) }\)%
\end{egexercise}%
\begin{egexercise}{34}\hypertarget{exercise-105}{}
\hypertarget{p-1375}{}%
Divide: \(\displaystyle{ \frac{1}{20} \div \left(-\frac{5}{12}\right) }\)%
\end{egexercise}%
\begin{egexercise}{35}\hypertarget{exercise-106}{}
\hypertarget{p-1383}{}%
Divide: \(\displaystyle{-\frac{3}{2} \div (-15)  }\)%
\end{egexercise}%
\begin{egexercise}{36}\hypertarget{exercise-107}{}
\hypertarget{p-1393}{}%
Divide: \(\displaystyle{-\frac{3}{8} \div (-9)  }\)%
\end{egexercise}%
\begin{egexercise}{37}\hypertarget{exercise-108}{}
\hypertarget{p-1403}{}%
Divide: \(\displaystyle{20 \div \frac{5}{3} }\)%
\end{egexercise}%
\begin{egexercise}{38}\hypertarget{exercise-109}{}
\hypertarget{p-1411}{}%
Divide: \(\displaystyle{4 \div \frac{2}{3} }\)%
\end{egexercise}%
\begin{egexercise}{39}\hypertarget{exercise-110}{}
\hypertarget{p-1419}{}%
Multiply: \(\displaystyle{{3 {\textstyle\frac{8}{9}}} \cdot {2 {\textstyle\frac{1}{10}}} }\)%
\end{egexercise}%
\begin{egexercise}{40}\hypertarget{exercise-111}{}
\hypertarget{p-1428}{}%
Multiply: \(\displaystyle{{1 {\textstyle\frac{5}{9}}} \cdot {6 {\textstyle\frac{3}{4}}} }\)%
\end{egexercise}%
\end{exercisegroup}
```
