### ISSUE TITLE
Markup for some icons

### ISSUE THREAD

**Issue by davidfarmer** [rbeezer/mathbook#948]
Either there should be a built-in way to incorporate certain icons,
for example:

settings (gear)
menu (hamburger)

Or else the authors' and publishers' guides should explain how to do it.

**Comment by rbeezer** [comment]
LaTeX, with gear and menu icon, and more:

https://ctan.org/pkg/fontawesome?lang=en

**Comment by rbeezer** [comment]
And HTML:

https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css

https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by rbeezer** [comment]
FontAwesome has about 3,000 symbols/icons.  Each has a (standard) name.  The name can be used in HTML/CSS it appears.  Each also seems to map to the LaTeX macro of the package referenced above.  (Though that mapping will be a small fiddle in XSL.)  So we might go

```xml
<icon fontawesome="bars"/>
```

as a way to get the menu/hamburger icon.  `gear` exists also.

**Comment by rbeezer** [comment]
OK, not as sematic as your suggestion.  But a boatload of icons all at once, rather than repeated requests to implement new ones.

**Comment by davidfarmer** [comment]
Maybe implement some of them in PTX, such as
< menu />
< settings />
and describe these in the authors guide?

I'd like to know if there are use cases for PTX "knowing"
the meaning of the icon.  Accessibility, for example.

**Comment by rbeezer** [comment]
Code at a2999f75aca1306438afb7fcc249d64a1785ec54

Discusison on originating thread at: 
https://groups.google.com/d/msg/pretext-support/IpdSgFq6yJU/hD2hrxeoEgAJ

Accessibility is a good point, I'll make a new issue for that (and reference back here), because I'm going to close this now that a base implementation is in place.
