### ISSUE TITLE
code and commas didn't quite mix in latex

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#95]
I get 

    More precisely, <theorem>, <corollary>, <lemma>, <algorithm>, <proposition>
    , <claim>, and <fact>, all behave exactly the same, 

in the pdf version.  Note that the comma is on the next line.  In html this doesn't happen.  Probably it is something about how code (or whatever it's processed into) is handled separately from other syntactic items in latex itself?

**Comment by rbeezer** [comment]
That was a bit subtle, apparently there is some space after the verbatim text.  But the fix was easy.

http://tex.stackexchange.com/questions/64750/avoid-line-breaks-after-lstinline

At 4d80b683.  Good catch - and it fixed up some other bad spacing (unintentional ragged left text).

**Comment by kcrisman** [comment]
Awesome, thanks for that.
