### ISSUE TITLE
Exercisegroup exercises do not resepect exercise.divisional.solution

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#952]
Experiencing this with ORCCA. But you can see in the sample article that if you:

1. find an exercisegroup/exercise
2. add to it a hint, answer, and solution
3. run `xsltproc --stringparam exercise.divisional.hint no --stringparam exercise.divisional.answer no --stringparam exercise.divisional.solution no ../../xsl/mathbook-html.xsl sample-article.xml`

The output will be showing the hint, answer, and solution despite all the "no"s. This is probably HTML only, since I recently built ORCCA's PDF and the solutions were not appearing in print. Solutions are appearing in HTML. Curiously, it seems they only appear in HTML for non-WW exercises. Since most ORCCA exercises are WW, it took a while for us to notice this.

**Comment by rbeezer** [comment]
Thanks for the confirmation of the fix over on #953.
