### ISSUE TITLE
Implement index in html

### ISSUE THREAD

**Issue by kcrisman** [rbeezer/mathbook#96]
Probably a hard request to fulfill, but should be here anyway.  (The sample article documents that this isn't done in html, so I assume that's correct.)  See #84 for a closely related issue.

**Comment by rbeezer** [comment]
This one is low on my list.  Mostly I want to ask "what is the point"?  Yes, being faithful to the print edition would be a good thing.  But I definitely want to see how a search bar (#84) goes and then re-evaluate.  Done right, a search bar should be *way* better than an index.

I think I did look at some tools for making indices as HTML pages.  It gets complicatred quickly, so not a place to reinvent the wheel.

**Comment by kcrisman** [comment]
I agree that #84 is far more important.  But there certainly are web resources that have them.  One reason it is useful is because of the same reason browsing the stacks is sometimes better than using the library search page - you never know what you will find!

(Heck, I'd be willing to chip in to help fund a search bar, if I didn't know it would cost more than I have to chip in!)

**Comment by rbeezer** [comment]
@davidfarmer convinced me that an index was something a human should do and it was different than a search tool.  (A search tool will still be good.)

So this was implemented a while ago at ea8d6676

Just brought the sample article in line at ef5ce0f5
