### ISSUE TITLE
extra space in a p with a list

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#971]
With source like
```
    <example permid="yFd">
      <title>The Alternate Definition of Absolute Value: <m>\abs{x}=\sqrt{x^2}</m></title>
      <statement>
        <p permid="ejJ">
          Simplify the following expressions using the fact that <m>\abs{x}=\sqrt{x^2}</m>.

          <ol label="a." cols="2" permid="jKA">
            <li permid="Zlv">
              <p permid="pen">
                <m>\sqrt{x^{14}}</m>
              </p>
            </li>
```

The output HTML has an extra space at the end of the p:

```
<p>Simplify the following expressions using the fact that \(\abs{x}=\sqrt{x^2}\text{.}\) </p>
```

Note that closing `</p>` is not in source. It is introduced by the process that carves up a single PTX `p` when there are lists inside. If the source opens the `ol` on the same line as the `p` (instead of two line breaks later) then the output HTML does not have the extra space.

**Comment by rbeezer** [comment]
See #975.

**Comment by rbeezer** [comment]
Inserted in sample article, completed elements, and see absolutely no extra spaces at the location reported in HTML output.
