### ISSUE TITLE
punctuation, units, and a line break

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#974]
With this source:
```
          and zinc has a density of
          <quantity>
            <mag>7.1</mag><unit base="gram" /><per prefix="centi" base="meter" exp="3" />
          </quantity>.
```
The HTML comes out as:
```
and zinc has a density of 7.1 <sup>g</sup>⁄<sub>cm<sup>3</sup></sub> .
```
with an extra space at the end before the period. Looks like the `quantity` transform needs some trimming of white space.

**Comment by rbeezer** [comment]
I can't see **anything** happening after the closing `</sub>` in the code.  can you provide more context?  Double-check?  Have a look yourself?

**Comment by Alex-Jordan** [comment]
I just checked this and now the output is:
```
and zinc has a density of 7.1 <sup>g</sup>⁄<sub>cm<sup>3</sup></sub>.
```

so for me it got better. Are you saying for you there was no period at all? For me the original issue was an extra space before the period. Since it seems to work now, I'll close the issue.
