### ISSUE TITLE
idx introcing extra p in HTML

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#975]
This source:
```
      <dl permid="rcn">
        <li permid="TMn">
          <title>Standard Form</title>
          <p permid="YKB">
            <m>f(x)=ax^2+bx+c</m>, with <m>y</m>-intercept <m>(0,c)</m>.
          </p>
        </li>

        <li permid="zTw">
          <title>Vertex Form</title>
          <p permid="ERK">
            <m>f(x)=a(x-h)^2+k</m>, with vertex <m>(h,k)</m>.
          </p>
        </li>

        <li permid="gaF">
          <title>Factored Form</title>
          <p permid="kYT">
            <m>f(x)=a(x-r)(x-s)</m>,
            with <m>x</m>-intercepts <m>(m,0)</m> and <m>(n,0)</m>.
          </p>
        </li>
      </dl>
          <idx><h>quadratic function</h><h>forms</h></idx>
    </p>
  </subsection>
```
leads to this HTML:
```
<dt>Standard Form</dt>
<dd><p>\(f(x)=ax^2+bx+c,\) with \(y\)-intercept \((0,c).\)</p></dd>
<dt>Vertex Form</dt>
<dd><p>\(f(x)=a(x-h)^2+k,\) with vertex \((h,k).\)</p></dd>
<dt>Factored Form</dt>
<dd><p>\(f(x)=a(x-r)(x-s),\) with \(x\)-intercepts \((m,0)\) and \((n,0).\)</p></dd>
</dl>
<p></p></section>
```
which has an extra `p` at the end, probably because of the `idx`.

**Comment by rbeezer** [comment]
Even better than what I posted recently on ORCAA repository.  I think the culprit is constructions like:

```xml
</ol>
whitespace
<idx/>
whitespace
</p>
```
and in reverse order with opening `p` and opening `ol`.  And when the first whitespace is actually a chunk of text, then I think the symptom is #971.

For pretty-printed AATA, I "fixed" 488 extra spaces, and 4 empty paragraphs with a temporary change to simply accomodate `ol`.  Fix will need to apply to `ul` and `dl`.

**Comment by rbeezer** [comment]
And see #972.

**Comment by rbeezer** [comment]
Work at 3b155c9abbb6691f60b0b988e7e1628b6c954c68 will definitely improve the situation around lists.  I think `idx` that are on their own line will definitely still cause some extra spaces (one only).  I'm not sure about empty paragraphs, but expect they are gone near lists, and maybe universally?

@Alex-Jordan Are you willing to test again?

**Comment by rbeezer** [comment]
Took original text, added leading `subsection` and `p`, inserted in sample article, and see absolutely no extra material after the end of the description list in HTML output.
