### ISSUE TITLE
webwork muliple choice list item knowls

### ISSUE THREAD

**Issue by Alex-Jordan** [rbeezer/mathbook#989]
When there is a `webwork//var[@form='buttons']/li`, HTML processing is making a knowl reference file. Such things do not have a number for cross-referencing, and it leads to an "error" in the HTML processing. The error is not hurting anything because such knowl files never get used. But the error message is either annoying or alarming, depending on how much you know about this issue.

**Comment by rbeezer** [comment]
This is the root cause of #951, see some details there on fix.  Actual changes at cb26a5a3f7e7e924b791aea58fa2d51b251cefe5  Thanks for the sleuthing.
